[metadata]
file_name = "《成年人阻塞性睡眠呼吸暂停低通气综合征筛查：美国预防临床服务指南工作组推荐声明》解读.md"
processed_at = "2024-12-27 20:09:32"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-27 20:08:20"
message = """

[隶属文件名]
《成年人阻塞性睡眠呼吸暂停低通气综合征筛查：美国预防临床服务指南工作组推荐声明》解读.md
[隶属文件分块名]
《成年人阻塞性睡眠呼吸暂停低通气综合征筛查：美国预防临床服务指南工作组推荐声明》解读/001-完整文档.md
[文本块]
# 《成年人阻塞性睡眠呼吸暂停低通气综合征筛查:美国预防临床服务指南工作组推荐声明》解读
曾凌枫1,张慧2,雷思1,卓慧1,叶云1,许琰1,罗荧荃1\\*  

1.410001 湖南省长沙市,中南大学湘雅二医院全科医学科2.410001 湖南省长沙市,中南大学湘雅二医院老年医学科\\* 通信作者:罗荧荃,主任医师;E-mail:luoyingquan@csu.edu.cn曾凌枫和张慧为共同第一作者  

【摘要】 成年人阻塞性睡眠呼吸暂停低通气综合征(OSAHS)是一种常见的睡眠呼吸障碍,与高血压、糖尿病、心血管疾病和其他健康问题紧密相关。尽管OSAHS 对全球人民的健康有着广泛影响,OSAHS 的筛查和诊断在临床实践中的普及率仍不高。在此背景下,美国预防临床服务指南工作组(USPSTF)最近发布了一项最新的成年人OSAHS筛查推荐,以帮助更多人识别和治疗潜在的睡眠呼吸障碍。本文将解读最新推荐,结合我国实际情况,为我国成年人OSAHS 筛查提供参考。  

【关键词】 阻塞性睡眠呼吸暂停低通气综合征;睡眠呼吸暂停,阻塞性;美国预防临床服务指南工作组;筛查;成年人  

【中图分类号】 R 749.79 【文献标识码】 A DOI:10.12114/j.issn.1007-9572.2023.0850  

基金项目:湖南省自然科学基金资助项目(2023JJ60438)  

成年人阻塞性睡眠呼吸暂停低通气综合征(OSAHS)是一种常见却常被低估的睡眠障碍,表现为在睡眠期间呼吸暂停和上呼吸道阻塞[1],其主要症状包括持续打鼾、呼吸停顿和短暂的醒来,导致患者夜间多次出现低氧血症和日间嗜睡。然而,OSAHS 不仅是“打鼾问题”,其已被证实与高血压、冠心病、脑卒中、糖尿病、肥胖等全身性疾病密切相关[2]。成年人OSAHS 的筛查和治疗备受关注。美国预防临床服务指南工作组(USPSTF)是一家负责评估临床预防证据,并发布筛查推荐的非营利组织。2022 年,USPSTF 对2017 版成年人OSAHS筛查推荐进行了更新,发布了最新的成年人OSAHS 筛查推荐3,该推荐指出对于18 岁以上的无症状成年人,目前没有足够的证据去评估OSAHS 筛查的获益与风险。结合我国实际情况,本文对该推荐提出的建议进行解读,以期为我国成年人OSAHS 的筛查以及防治提供有力参考。
# 1 成年人OSAHS 流行病学
成年人OSAHS 是常见的睡眠呼吸疾病,以呼吸暂停低通气指数 $({\\mathrm{~AHI~}})\\,\\geq\\,5$ 次 $/\\mathrm{h}$ 为诊断标准[4]。我国有1.76 亿OSAHS 患者,居全球首位,鉴于医疗负担巨大,高危人群筛查、早期诊断和管理至关重要[5]。目前,OSAHS 治疗主要依赖三级甲等综合医院。由于医疗资源限制,OSAHS 就诊的患者数量也有限,同时公众对OSAHS 的认知度也较低,这导致了OSAHS 的预防及治疗存在一定的困难。多数OSAHS 高危患者未被及时发现及诊治,这会导致其出现并发症从而增加治疗的难度。仅靠医院的诊治不足以满足对OSAHS 公共卫生管理的需求,还需要配合早期的筛查以提前介入OSAHS 的防治。
# 2 USPSTF 最新推荐
目前没有足够的证据支持或反对在成年人中进行OSAHS 筛查,临床医生应根据临床经验判断OSAHS 筛查的必要性及如何筛查OSAHS[5],评估理论依据见表1。
# 3 USPSTP 成年人OSAHS 筛查推荐概要

# 3.1 适用人群
USPSTF 推荐适用于无症状的成年人( $\\geqslant18$ 岁),也适用于未被识别出有OSAHS 症状(例如,打鼾、目击到呼吸暂停、日间嗜睡过多、认知功能障碍、情绪变化,或在睡觉时呼吸困难或窒息)的成年人,包括未察觉自己有上述症状或没有将症状反馈给医生的成年人。此推荐不适用于已经出现OSAHS 症状或高度疑似OSAHS 的人,或有可能诱发OSAHS 发作的急性疾病(例如卒中)的人。此推荐也不适用于儿童、青少年或孕妇。
# 3.1 OSAHS 的定义
OSAHS 是一种睡眠障碍,其特征是尽管努力呼吸,但在睡眠期间依然存在咽喉气道狭窄和阻塞引起的呼吸气流减少或停止,总的气道阻塞持续时间超过 $10~\\mathrm{s}$ 被定义为呼吸暂停,而低通气是部分气道阻塞,至少导致血氧饱和度下降 $3\\%$ 或呼吸努力相关微觉醒。阻塞性睡眠呼吸暂停被定义为呼吸暂停、低通气或呼吸努力相关微觉醒事件 $\\geqslant5$ 次 $/\\mathrm{h}$ 。睡眠AHI 用于定义OSAHS的严重程度,轻度OSAHS:AHI 为 $5{\\sim}{<}15$ 次 $/\\mathrm{h}$ ,中度OSAHS:AHI 为 $15{\\sim}{<}30$ 次 $/\\mathrm{h}$ ,重度OSAHS: $\\mathrm{AHI}\\geqslant30$次 $/\\mathrm{h}$ 。亦有研究推荐使用氧减饱和度指数(ODI)诊断OSAHS,其建议以 $\\mathrm{AHI}\\geqslant15$ 次 $/\\mathrm{h}$ 且 $\\mathrm{ODI}{>}4\\%$ (每次氧减事件血氧降低 $\\geqslant4\\%$ )来诊断成年人OSAHS,并建议对于 $\\mathrm{AHI}\\geqslant10\\$ 次 $/\\mathrm{h}$ 且 $\\mathrm{ODI}~>~4\\%$ 的患者行进一步评估以确诊OSAHS[1]。OSAHS 的常见临床体征和症状包括日间嗜睡过多、尽管睡眠时间足够仍然觉得休息不够、大声或不规则的打鼾,以及在睡觉时窒息或呼吸困难[6]。
# 3.3 高危人群的识别
成年人OSAHS 的高危人群包括但不限于以下因素:(1)年龄因素,USPSTF 推荐指出,40 岁及以上的成年人更容易受到OSAHS 的影响。这可能是由于上呼吸道肌肉松弛和组织松弛在年龄增长过程中的增加,导致呼吸道阻塞更为常见[7]。(2)肥胖和超重,肥胖或超重的个体,尤其是 $\\mathrm{BMI}\\geqslant30~\\mathrm{kg/m}^{2}$ 的成年人,面临更高的OSAHS 风险。这是因为过多的脂肪沉积在颈部和喉部周围可能导致上呼吸道狭窄,增加了呼吸道阻塞的可能性[8]。(3)高血压,高血压与OSAHS 之间存在双向的关联。高血压患者更容易患上OSAHS,反之亦然。OSAHS 导致呼吸暂停和低氧血症,这会对心血管系统产生负面影响,进一步加重高血压[9]。(4)2 型糖尿病,2 型糖尿病与OSAHS 密切相关。糖尿病患者更容易患上OSAHS,而OSAHS 也可以加重糖尿病症状。这种相互影响可能与胰岛素敏感性和胰岛素抵抗之间的复杂关系有关[9-10]。(5)心血管疾病,已有证据表明,OSAHS 与心血管疾病如冠心病和卒中之间存在紧密联系。呼吸暂停导致低氧血症和交感神经活性增加,这可能增加冠状动脉疾病的风险[9-10]。(6)性别差异,USPSTF 推荐指出尽管OSAHS 在男性中更常见,但绝经后妇女也为高危人群。更年期后雌激素水平下降,这可能导致上呼吸道肌肉松弛,增加OSAHS 发生风险[11]。(7)家族史,家族史也会影响OSAHS 发生风险,如果家族中有OSAHS 患者,个体可能具有遗传上的易感性。  

这些高危因素共同影响了OSAHS 的发病。对于医生和卫生保健专业人员来说,理解这些高危因素对于识别OSAHS 患者以及推荐适当的筛查和治疗方法至关重要。此外,关注这些因素也有助于提高公众意识,使人们更加警觉,如果存在高危因素,应主动寻求医疗建议。高风险人群的筛查和干预对于减少OSAHS 的潜在健康影响至关重要[12]。 O
# 3.4 筛查工具的选择
USPSTF 推荐强调了在筛查成年人OSAHS 时选择合适筛查工具的重要性。这些工具在确定高危人群和识别潜在OSAHS 患者方面起着关键作用[12]。关于USPSTF推荐的一些筛查工具:有几种筛查问卷和临床预测工具旨在识别OSAHS 高危人群。许多工具需要结合有关临床发现(例如,BMI 和颈围)以及与OSAHS 相关的症状。潜在的筛查问卷和临床预测工具包括Epworth 嗜睡量表(ESS)、STOP 问卷(打鼾、疲劳、观察到的呼吸暂停、高血压)、STOP-Bang 问卷(STOP 问卷加BMI、年龄、颈围和性别)、柏林问卷等筛查方法[13]。一项荟萃分析结果显示,相比较于其他的问卷,STOP-Bang 问卷对于OSAHS 筛查具有最高的灵敏度[14]。此外国内外研究表明动态心电图等可穿戴设备可用于OSAHS 初筛[13,15]。然而,这些工具在从基层医疗卫生服务中招募的无症状人群中尚未得到充分验证。高度怀疑OSAHS 的人常需要通过多导睡眠图来明确诊断,该图结合了多种测量数据,包括脑电图、眼动图、下颌电肌电图、气流监测、血氧饱和度、呼吸频率、心电图或心率、体位监测和腿动监测等。多导睡眠图期间测得的AHI 代表事件发生的频率,常用于描述疾病或病情的严重程度。
# 3.5 潜在的干预措施
USPSTF 推荐不仅关注成年人OSAHS 的筛查和识别,还强调了潜在的干预措施,以帮助患者管理和治疗这一疾病[16],USPSTF 推荐的干预措施包含但不仅限于以下几种。  

3.5.1 体质量管理和生活方式改变:(1)体质量管理,肥胖是OSAHS 的主要危险因素之一。因此,对于肥胖或超重的患者,重要的干预措施之一是体质量管理,包括饮食控制和适度的体育锻炼,旨在减轻体质量。即使是适度的体质量减轻也可以显著改善OSAHS 症状,包括减轻打鼾和减少呼吸暂停的发生次数[17]。(2)生活方式改变,除了体质量管理,生活方式改变也可以对OSAHS 患者产生积极影响,包括戒烟、限制酒精摄入、避免晚餐过量饮食、规律作息和改进睡眠环境等。这些生活方式可能影响OSAHS 的严重程度和发生频率。医生可以为患者提供支持和指导,以帮助他们在日常生活中实施这些建议[17]。 C  

3.5.2 正压通气(PAP)治疗:(1)PAP 设备,对于确诊为OSAHS 的患者,特别是那些症状较为严重的患者,PAP 设备是一种有效的治疗方法,最常见的PAP设备是持续气道正压通气(CPAP)。这些设备通过面罩或鼻罩提供气道正压,防止气道坍塌,确保患者在夜间呼吸通畅。这一治疗方法通常能够显著减少呼吸暂停的发生,改善氧饱和度,减轻日间嗜睡和提高生活质量[18]。(2)自动调节压力正压通气(APAP)设备,可以根据患者的呼吸情况进行调整,以提供更个性化的治疗。APAP 设备能够动态调整气道正压,以适应不同睡眠阶段的需要,提供更加舒适和有效的治疗[19]。  

这些干预措施的目标是减轻OSAHS 症状、改善患者的生活质量,并降低与OSAHS 相关的全身性健康风险。在确定患者的治疗方案时,医生应综合考虑患者的临床情况、病情严重程度和个体差异,以提供最佳的医疗服务。通过这些干预措施的实施,可以帮助患者更好地管理OSAHS,降低疾病负担,提高其未来的生活质量。  

此外,USPSTF 推荐提出未来需要聚焦于以下几方面的临床研究:(1)针对无症状人群OSAHS 筛查的设计研究,探索OSAHS 筛查对患者重要结局事件(例如死亡、心血管疾病事件、车祸事故、生活质量等)的影响;(2)在社区人群中,尤其是在未被识别OSAHS 或症状轻微的人群中,评估筛查工具的准确性;(3)开发准确的风险评估工具识别最有可能从OSAHS 筛查中受益的人群;(4)针对OSAHS 自然进程的研究,尤其是关于从轻度OSAHS 进展至重度OSAHS 方面的研究,以及OSAHS 被早期识别及治疗的临床获益方面的研究[5]。  

目前国内外关于OSAHS 的筛查方法及后续的治疗措施无显著的区别,但是针对一般人群的筛查方案,尚无明确定论[20]。目前国内相关指南认为[20],尽管当前暂未有高质量的证据支持OSAHS 全面筛查,但鉴于我国OSAHS 患病群体庞大,且人口老龄化加剧带来的OSAHS 患病率进一步升高,预防和确诊严重不足的状况,筛查我国高危人群中无症状OSAHS 将对疾病的防控起到积极作用。因此,国内指南建议对具有OSAHS典型症状、体征、相关合并疾病以及围术期的OSAHS高危人群进行筛查。对不具备典型症状的和/ 或自己未意识到OSAHS 症状的高危人群也应进行筛查。对于一些OSAHS 可能危及公共安全的职业人群(如职业司机、飞行员、消防员)、从事危险工作(如高空作业、伐木等)均应进行OSAHS 筛查。  

国内有研究探索了应用各类问卷包括STOP-Bang问卷等在国内人群中筛查OSAHS 的有效性[21-22]。但是这些研究均局限于OSAHS 高危人群如肥胖人群或者伴有高血压及糖尿病的人群,或者是特殊人群如术前人群。关于在一般人群中进行OSAHS 筛查的相关研究,目前仍鲜有报道。虽然2018 年出版的《成人阻塞性睡眠呼吸暂停基层诊疗指南(实践版·2018)》并不推荐在无症状的普通人群中进行OSAHS 筛查[23]。但是有国内学者认为,OSAHS 的早发现、早诊断和早治疗尤为关键,但由于人群普遍对自己打鼾情况关注度低,常忽略了对该病的常规检查,导致病情发展,延误了干预的最佳时机,但随着国家不断推进健康中国建设,人们对健康的关注度及要求日益提升,常规健康体检也越来越受到重视,将睡眠问卷评估及整夜睡眠呼吸监测等检查列入常规体检中,不仅可以早期发现OSAHS,进一步达到早期诊断和处理、干预自然病程进展的目的,还可以减轻上级医院的工作压力,减少医患矛盾的发生[24]。但是一项在公务员人群中进行的OSAHS筛查研究显示,即使给予免费的睡眠筛查及疾病干预模式,睡眠筛查、CPAP 治疗的接受度仍较低[25]。因此对于全科医生,首先应该做好OSAHS 的科普工作,提高公众对OSAHS的认知;其次在临床工作中应结合患者实际情况来判断OSAHS 筛查的必要性,进一步达到早期诊断与处理、干预疾病进展的目的,此外全科医生应该积极开展大规模人群研究来探索我国成年人OSAHS 筛查的风险与获益,以及探索最适合社区成年人OSAHS 筛查的工具,从而为指南提供高级别的证据支持。
# 4 总结
OSAHS 是一种常见但易被忽视的睡眠障碍,USPSTF 推荐认为目前没有足够的证据评估成年人OSAHS 筛查的受益与风险,呼吁更多的关于OSAHS 筛查获益与风险的研究,以及开发能够准确检测无症状人群中OSAHS 风险增加的筛查工具。通过结合国内与USPSTF 推荐,医生和卫生保健提供者可以综合使用不同的筛查工具和方法,根据患者的具体情况和需求,以更好地识别和治疗OSAHS(表2)。这种综合筛查策略有望提高我国成年人OSAHS 的早期诊断率,确保患者能够及时获得合适的治疗和护理,从而改善其生活质量,减轻相关全身性健康问题的风险。  

表1 USPSTF 评估理论依据Table 1 Rationale for USPSTF assessment  

注:OSAHS $\\lvert=$ 阻塞性睡眠呼吸暂停低通气综合征。  

表2 关于USPSTF 成年人阻塞性睡眠呼吸暂停筛查的总结 Table 2 Summary of recommendations for obstructive sleep apnea hypopnea syndrome screening of adults in USPSTF   

注:USPSTF $\\backslash=$ 美国预防临床服务指南工作组。

"""
response = """
// 节点更新
MERGE (n:Disease {name: '阻塞性睡眠呼吸暂停低通气综合征'})
SET 
    n.description = coalesce(n.description, '一种常见的睡眠呼吸障碍，表现为在睡眠期间呼吸暂停和上呼吸道阻塞'),
    n.severity = coalesce(n.severity, '中等');

MERGE (n:Symptom {name: '打鼾'})
SET 
    n.description = coalesce(n.description, '夜间睡眠时发出声响'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '呼吸停顿'})
SET 
    n.description = coalesce(n.description, '在睡眠期间出现的呼吸停止情况'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '日间嗜睡'})
SET 
    n.description = coalesce(n.description, '白天感到过度困倦'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Examination {name: '多导睡眠图'})
SET 
    n.description = coalesce(n.description, '用于诊断OSAHS的睡眠检查方法'),
    n.method = coalesce(n.method, '综合多项生理数据监测'),
    n.requirement = coalesce(n.requirement, '住院观察');

// 关系更新
MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停低通气综合征'
MATCH (to) WHERE to.name = '打鼾'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.95),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停低通气综合征'
MATCH (to) WHERE to.name = '呼吸停顿'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停低通气综合征'
MATCH (to) WHERE to.name = '日间嗜睡'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停低通气综合征'
MATCH (to) WHERE to.name = '多导睡眠图'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '高'),
    r.mandatory = coalesce(r.mandatory, 'true');

"""
