[metadata]
file_name = "中国快速眼球运动睡眠期行为障碍诊断与治疗专家共识.md"
processed_at = "2024-12-18 16:48:29"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-18 09:55:56"
message = """

[隶属文件名]
中国快速眼球运动睡眠期行为障碍诊断与治疗专家共识.md
[隶属文件分块名]
中国快速眼球运动睡眠期行为障碍诊断与治疗专家共识/001-完整文档.md
[文本块]
# 中国快速眼球运动睡眠期行为障碍诊断与治疗专家共识
中华医学会神经病学分会睡眠障碍学组  

快速眼球运动睡眠期行为障碍(rapid-eye-movement sleep behavior disorder,RBD)是一种以REM睡眠期间伴随梦境及肢体活动为特征的睡眠疾病,发作时的暴力行为可造成自身及同床者伤害并破坏睡眠[。RBD 通常发生在50 岁以上的人群,但也有 15 岁发病的报道2。在普通人群中发病率为 $0.\\,4\\%\\,\\sim0.\\,5\\%^{\\,[3-4]}$ ,70 岁以上人群发病率为$7\\%\\sim8\\%$ [。据中国香港地区的流行病学调查报道,70 岁以上人群中 RBD 患病率为 $0.\\:38\\%^{\\:[6]}$ ;中国大陆人群中,基于RBD量表的大规模社区调查发现可疑 RBD 的患病率在 $4\\%\\sim5\\%$ [”。RBD 患者中男性明显高于女性,为 $2\\colon1\\sim5\\colon1$ ,女性发病及诊断年龄可能均晚于男性[]。既往认为 RBD 仅是一种独立的睡眠障碍,但越来越多的临床随访研究显示,其与帕金森病、多系统萎缩、路易体痴呆等多种神经系统变性疾病有着密切关联[\"。目前认为,RBD 对于神经系统变性疾病的早期预警有重要意义。  

本篇中对治疗方案的推荐,主要参考已有的循证医学证据,经专家讨论达成共识。推荐等级分为$\\mathrm{A}\\,.\\mathrm{B}\\,.\\mathrm{C}\\,.\\mathrm{D}\\ 4$ 级(A级最强,D级最弱):A级推荐:基于循证医学I级证据或获得大多数认可的II级证据,若无禁忌则可直接用于临床实践;B级推荐:基于II级循证医学证据或高度一致的专家共识,适应证充分时可应用;C级推荐:基于循证医学III级证据或专家共识,可在与患者讨论后应用;D级推荐:可选择性方案,需告知患者可能潜在的危险,不用于无适应证的患者。
# RBD 定义
RBD是以REM睡眠期肌肉失弛缓并出现与梦境相关的复杂运动为特征的发作性疾病。其特征为:在REM睡眠期出现持续或间歇性肌张力增高、多梦及梦境演绎行为,从肌肉抽动到各种复杂剧烈的行为动作均可出现,如讲话、唱歌、喊叫、挥拳、抓取、钳制、跳跃、坠床等[10]。多数梦境都有暴力内容,常常伴随与梦境相关的暴力行为,可导致患者自伤或伤及他人[1]。
# RBD分类
RBD 作为一种具有独特表现的睡眠期疾病,在临床上十分常见,既可以是原发性疾病,也可以继发于其他神经系统疾病,根据病因不同可分为特发性RBD(idiopathicRBD,iRBD)及继发性RBD(secondary RBD,sRBD)[5}。据统计 iRBD 患者约占RBD总数的 $60\\%$ ,而sRBD患者约占 $40\\%$
# 一、特发性 RBD
RBD 作为一种独立症状单独出现,无其他伴随症状[12},但 iRBD 可能是突触核蛋白病的一个危险因素,这类患者在数年或数十年后最终可能出现神经系统变性疾病。
# 二、继发性 RBD
1.药源性RBD:抗精神病药、三环类抗抑郁药及5-羟色胺再摄取抑制剂、苯二氮草类镇静催眠药、单胺氧化酶抑制剂、苯乙肼、乙醇、咖啡等,均可引起RBD的发生[13]  

2.症状性 RBD:为与正常 REM 睡眠期肌张力缺失相关的脑干相应部位损害(如血管性、炎症、肿瘤、变性等)导致的 RBD 表现[14,如某些可影响脑干功能的神经系统疾病,包括发作性睡病、Machado-Joseph病、肌萎缩侧索硬化、癫痫、多发性硬化、吉兰-巴雷综合征等[15}]。RBD 仅为这些疾病的部分症状。  

3.与神经系统变性疾病相关的 RBD: $\\upalpha$ 突触核蛋白( $\\upalpha$ -synuclein)异常沉积可导致多种神经系统变性疾病,如帕金森病、路易体痴呆(DLB)、多系统萎缩(MSA)等,RBD 常为这类疾病的前驱/早期症状或伴随的临床表现。有 $33\\%\\sim46\\%$ 的帕金森病患者[12] $75\\%$ 的 DLB 患者[13]、近 $100\\%$ 的MSA患者可合并 RBD[3]。RBD 也可见于 tau 蛋白相关的疾病,如阿尔茨海默病(AD)、进行性核上性麻痹(PSP)、皮质基底节变性(CBD)和额颞叶痴呆(FTD)[4]有研究显示,RBD可以作为DLB的核心临床症状,有助于与AD 鉴别[16]  

2. Mayo 睡眠问卷(Mayo Sleep Questionnaire)。  

3.RBD 问卷-香港版(RBD questionnaire -HongKong)。  

4.RBD单问卷筛查(RBDSingle-QuestionScreen)。  

其中 RBD 问卷-香港版在经过调整后,更适合亚洲人群的睡眠习惯特点,临床操作更简单易行[24-25 ] O
# RBD 临床表现
在出现典型RBD症状之前数年或数十年,患者常表现有睡眠期间的不安定,如梦和肢体活动频繁等现象。RBD临床症状主要包括鲜活或暴力的梦境及其与梦境相关的行为或情感反应。典型临床表现是睡眠期间出现不同程度的行为动作甚至是暴力行为,如殴打同床者,甚至下床活动、伤人或毁物,患者在清醒后可清晰回忆梦境内容,但对睡眠中出现的异常行为活动无记忆。绝大多数患者仅主诉睡眠期间身体受伤,严重者可出现硬脑膜下血肿、腰椎骨折等。女性RBD患者相对来说有暴力内容的梦境少见,但在梦境中多为受害者角色1]。虽然REM睡眠表现个体差异明显,但仅少数患者主诉白天思睡。
# RBD 的诊断
根据AASM修正的睡眠障碍国际分类第三版( International  Classification  of Sleep   Disorders-3rdedition,ICSD-3)[26]的定义,RBD 的诊断标准如下。  

一、REM睡眠期出现RWA  

二、有明确的梦境行为演绎(dreamenactmentbehavior,DEB),有临床发作史或PSG监测记录到明确的发作  

三、REM睡眠期脑电无痫样放电  

四、症状不能被其他病因解释,包括其他类型睡眠行为异常、神经/精神疾病、药物、内科躯体疾病或者物质滥用等  

RWA(PSG 监测) $^+$ DEB(临床症状)是 RBD最主要的诊断标准。
# 辅助检查

# 一、神经电生理
多导睡眠图(polysomography,PSG)监测可发现RBD 最显著的电生理特征表现为 REM 睡眠期存在持续甚至亢进的骨骼肌活动,检查时应同时监测上下肢的肌电图。通过PSG检查,对于帕金森病患者的RBD检出率可提高 $56\\%$ [18]  

美国睡眠医学学会(American Academy of SleepMedicine,AASM)关于RBD中 REM 睡眠期骨骼肌失弛缓现象(REM-sleep without atonia,RWA)的PSG监测特征规定包括[1]:  

1.紧张性活动(持续性肌张力增高):每帧(30s) $>50\\%$ 的下颜肌电幅度增高,比NREM睡眠期的最小肌电图还高;  

2.时相性活动(爆发性肌电活动):每帧(30s)$>\\!50\\%$ 的爆发性肌电活动,时间 $0.\\;1\\sim5.\\;0\\,\\mathrm{~s~},$ 幅度 $>$4倍背景肌电活动。  

二、筛选量表[20-23]  

1. RBD 筛查问卷(RBD screeningquestionnaire)。
# 鉴别诊断

# 一、睡眠期癫痫
临床表现为癫痫发作,复杂部分性发作在夜间比较少见,一般不能够回忆生动梦境,其自动症比较简单,多为一些重复活动如脱衣、解纽扣等,少有攻击行为,常伴有强直或阵挛样活动。PSG监测或睡眠脑电图监测显示痫性放电,可发生于任何睡眠期。而RBD很少有局灶性运动,所表现的攻击行为比癫痫发作的随意动作更加复杂。
# 二、意识模糊性觉醒
意识模糊性觉醒是指不能从睡眠中很快觉醒,从睡眠到觉醒的过程中有一段较长的意识模糊期,但没有暴力行为,PSG监测显示从NREM睡眠中觉醒,脑电图有特征性改变。
# 三、睡惊症
在睡眠中突然发生,发作时有极度恐惧表现,常伴有令人毛骨悚然的尖叫,存在明显自主神经功能紊乱。PSG监测显示多发生于刚人睡时或 NREM睡眠1期。  

四、睡行症  

大多发作于儿童期,临床主要表现为睡眠中起床行走,PSG监测显示发生于 NREM 睡眠期。
# 五、梦魇
梦魔多发生于儿童期,常常发生在一个内容恐怖且长而复杂的梦境之后,表现为患者从睡眠中突然惊醒,伴有强烈的恐怖焦虑等情感体验,但不伴有暴力性运动。惊醒后患者的意识清楚,且很难再次人睡。无 REM睡眠期行为障碍的特征性 PSG 表现。
# 六、创伤后应激障碍
患者有强烈的创伤经历,症状表现与创伤经历密切相关。清醒时有创伤性应激障碍的其他表现,如持续警觉性增高、持续回避,并伴有社会功能损害。
# RBD 治疗

# 一、防护措施
安全的睡眠环境(A级推荐):RBD临床症状中的伤害性行为可高达 $30\\%\\sim81\\%^{\\frac{\\bigstar}{27}}$ ,严重威胁患者健康及生存质量,其中以体表淤斑、撕裂伤、骨折的发生频率最高。为伴有伤害性行为的RBD患者提供相对安全的睡眠环境,应作为非药物治疗的标准化治疗手段[2\"。推荐的方法包括在地板上放置床垫、将家具的边角用软物包裹、对玻璃窗进行安全性保护、睡前移去潜在的危险物品,如利器、玻璃、水杯水壶等。此外,建议患者的同床者与患者分室居住,直到患者RBD 症状得到有效的控制。同时 RBD 患者需规律作息时间,避免有精神兴奋作用药物的使用和酒精的刺激。如果同时伴有其他睡眠问题需及时处理,如阻塞性呼吸睡眠暂停综合征(OSAS)、不宁腿综合征等[29]。
# 二、药物治疗
1.氯硝西泮(B级推荐):氯硝西泮是治疗RBD的有效药物。氯硝西泮可显著减少RBD行为和外伤的发生,对于控制RBD症状的效果如下:剧烈活动及大叫 $>$ 复杂的非剧烈活动 $>$ 简单的肢体活动和躯干活动 $>\\mathrm{REM}$ 睡眠中的过度肌束颤动。但慎用于 RBD 伴有痴呆、步态异常以及 OSAS 患者[30]在用药过程中应严格监控,尤其是对于伴有神经退行性疾病、OSAS以及肝功能异常的患者。建议剂量为 $0.\\;25\\sim2.\\;00\\mathrm{~mg}$ ,睡前 $15\\ \\mathrm{min}$ 服用,最高不超过$4.\\:0\\mathrm{~mg}^{[31-32]}$ 。氯硝西泮的不良反应主要包括日间过度镇静、阳痿、运动失调、意识模糊、记忆缺失等,尚缺乏此药成瘾性的客观证据[33]。 $0.\\,5\\sim1.\\,0\\mathrm{~mg}$ 的氯硝西泮有加重OSAS的风险, $2.\\;0\\,\\mathrm{~mg~}$ 剂量有可能增加意识模糊和摔倒的风险[34]  

2.褪黑素(B级推荐):褪黑素治疗RBD优势明显且不良反应较少,该药对于治疗合并 DLB、帕金森病、MSA 的 RBD 患者有明确疗效[35]。睡前服用$3\\sim12\\,\\mathrm{~mg}$ 褪黑素对于控制 RBD 症状效果显著,不良反应少而轻;剂量相关的不良反应主要包括:晨间头痛、白日困倦、妄想和幻觉等[36] 。  

3.多巴及多巴受体激动剂(C级推荐):目前认为,左旋多巴对 RBD 治疗效果尚不肯定[37];多巴受体激动剂普拉克索治疗RBD有一定疗效;PET研究证实一些原发性 RBD患者存在多巴胺能的黑质纹状体通路障碍,轻度原发性RBD患者部分有效,但对于治疗伴有帕金森病的RBD可能无效,与氯硝西泮联合的效果优于左旋多巴或普拉克索单药的疗效[3。因此,此药可用于治疗未明确诊断为神经退行性疾病的RBD患者及用于氯硝西泮的替代治疗,每日最大剂量不超过 $0.\\:7\\:\\:\\mathrm{mg}^{[39]}$ 。多巴受体激动剂罗替高汀能提高帕金森病伴RBD患者睡眠质量并改善其 RBD 相关运动行为的频率和严重程度[24] ,仍需要积累更多的临床证据。  

4.帕罗西汀(C级推荐):帕罗西汀治疗效果尚不肯定,甚至有诱发或加重RBD 症状的可能。此药可通过抑制 REM 睡眠来达到缓解 RBD 的临床症状[40],一般用量为睡前服用 $10\\sim40\\ \\mathrm{mg}$ ,不良反应主要包括恶心、头晕、腹泻、口渴等,故在治疗RBD中使用相对较少。  

5.多奈哌齐(C级推荐):有报道称乙酰胆碱酯酶抑制剂多奈哌齐 $10\\sim15\\,\\mathrm{~mg}$ 晚上睡前服用,可能对RBD症状有缓解作用,但对于治疗RBD的疗效尚存在争议[4],不过对于一些伴有共核蛋白病的RBD患者有一定治疗效果,其拟胆碱作用可能引起惊厥,用药时应注意观察及鉴别。  

6.镇静催眠药物(C级推荐):右佐匹克隆与佐匹克隆是一种可以兴奋GABA能神经元的镇静催眠药物。在治疗RBD 时,小剂量睡前服用。不良反应主要包括皮疹、恶心等,但临床仍缺乏充足证据[42]。除氯硝西泮外的苯二氮草类药物也有治疗RBD 的临床报道,但存在争议。三唑仑治疗 RBD有效,但是目前没有标准化的治疗疗程[43],阿普唑仑的使用剂量为 $1\\sim3\\mathrm{~mg}/\\mathrm{d}^{[44]}$ 。替马西泮的使用剂量为 $10~\\mathrm{mg/d^{\\,[45]}}$ ,亦可与佐匹克隆联合使用。  

7.其他(证据较少的药物):地昔帕明可以有效抑制周期性的REM睡眠,一般使用剂量为每晚50mg,共服用3 周[46]。有研究表明氯氮平可用于治疗伴有痴呆的RBD患者,但是目前尚未有标准化的治疗疗程[47]。卡马西平用于缓解 RBD 症状效果肯定,可以单独使用,或与苯二氮草类药物联用[48]。卡马西平可以控制RBD中剧烈的伤害性行为,通常剂量为 $0.\\ 1\\ \\mathrm{g/}$ 次,3次/d。有研究报道某些中药“抑肝散”(茅苍术、茯苓、川芎、当归、柴胡、甘草、钩藤)可对RBD有缓解作用[4\"」,机制可能与影响了GABA能和5-羟色胺能神经的活性有关,可与氯硝西泮联合应用缓解症状,但用法用量缺乏足量证据。  

目前,治疗RBD的各种药物的剂量及标准化疗程尚有争议,但在临床工作中,多数专家认为治疗持续时间应根据RBD 患者的具体发作情况进行调整。RBD 本身就是一类复杂的睡眠疾病,又因其特殊的病理生理特点与神经系统变性疾病关系密切,使其治疗更加复杂。

"""
response = """
// 节点更新
MERGE (n:Disease {name: '快速眼球运动睡眠期行为障碍'})
SET 
    n.code = coalesce(n.code, 'RBD'),
    n.description = coalesce(n.description, '以REM睡眠期间伴随梦境及肢体活动为特征的睡眠疾病'),
    n.category = coalesce(n.category, '睡眠障碍'),
    n.severity = coalesce(n.severity, '中等');

MERGE (n:Symptom {name: '与梦境相关的肢体活动'})
SET 
    n.description = coalesce(n.description, '在REM睡眠期出现持续或间歇性肌张力增高、多梦及梦境演绎行为'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '高');

MERGE (n:Symptom {name: '暴力行为'})
SET 
    n.description = coalesce(n.description, '在发作时可能对自己或他人造成伤害'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '高');

MERGE (n:Complication {name: '帕金森病'})
SET 
    n.description = coalesce(n.description, '神经系统变性疾病'),
    n.severity = coalesce(n.severity, '严重');

MERGE (n:Complication {name: '多系统萎缩'})
SET 
    n.description = coalesce(n.description, '神经系统变性疾病'),
    n.severity = coalesce(n.severity, '严重');

MERGE (n:Complication {name: '路易体痴呆'})
SET 
    n.description = coalesce(n.description, '神经系统变性疾病'),
    n.severity = coalesce(n.severity, '严重');

MERGE (n:NonDrugTreatment {name: '安全的睡眠环境'})
SET 
    n.description = coalesce(n.description, '为伴有伤害性行为的RBD患者提供相对安全的睡眠环境'),
    n.duration = coalesce(n.duration, '持续'),
    n.frequency = coalesce(n.frequency, '每日'),
    n.contraindication = coalesce(n.contraindication, '无'),
    n.equipment = coalesce(n.equipment, '床垫、软物包装家具边角');

MERGE (n:DrugTreatment {name: '氯硝西泮'})
SET 
    n.description = coalesce(n.description, '治疗RBD的有效药物'),
    n.dosage = coalesce(n.dosage, '0.25-2.00 mg'),
    n.frequency = coalesce(n.frequency, '睡前15分钟'),
    n.duration = coalesce(n.duration, '持续'),
    n.route = coalesce(n.route, '口服'),
    n.contraindication = coalesce(n.contraindication, '伴有痴呆、步态异常、OSAS的患者');

MERGE (n:DrugTreatment {name: '褪黑素'})
SET 
    n.description = coalesce(n.description, '对治疗合并DLB、帕金森病、MSA的RBD患者有明确疗效'),
    n.dosage = coalesce(n.dosage, '3-12 mg'),
    n.frequency = coalesce(n.frequency, '睡前'),
    n.duration = coalesce(n.duration, '持续'),
    n.route = coalesce(n.route, '口服'),
    n.contraindication = coalesce(n.contraindication, '无');

MERGE (n:DrugTreatment {name: '多巴受体激动剂'})
SET 
    n.description = coalesce(n.description, '对RBD治疗效果尚不肯定，部分有效'),
    n.dosage = coalesce(n.dosage, '每日最大剂量不超过0.7 mg'),
    n.frequency = coalesce(n.frequency, '每日'),
    n.duration = coalesce(n.duration, '持续'),
    n.route = coalesce(n.route, '口服'),
    n.contraindication = coalesce(n.contraindication, '伴有神经退行性疾病的RBD患者');

// 关系更新
MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '与梦境相关的肢体活动'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '高'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '暴力行为'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '高'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '帕金森病'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 0.33),
    r.timeframe = coalesce(r.timeframe, '数年或数十年');

MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '多系统萎缩'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 0.75),
    r.timeframe = coalesce(r.timeframe, '数年或数十年');

MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '路易体痴呆'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 1.0),
    r.timeframe = coalesce(r.timeframe, '数年或数十年');

MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '安全的睡眠环境'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.8),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '初始治疗');

MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '氯硝西泮'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.9),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '药物治疗');

MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '褪黑素'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.85),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '药物治疗');

MATCH (from) WHERE from.name = '快速眼球运动睡眠期行为障碍'
MATCH (to) WHERE to.name = '多巴受体激动剂'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.75),
    r.priority = coalesce(r.priority, '中'),
    r.stage = coalesce(r.stage, '药物治疗');

"""
