[metadata]
file_name = "中国帕金森病睡眠障碍管理专家共识.md"
processed_at = "2024-12-27 20:09:32"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-27 20:08:46"
message = """

[隶属文件名]
中国帕金森病睡眠障碍管理专家共识.md
[隶属文件分块名]
中国帕金森病睡眠障碍管理专家共识/001-完整文档.md
[文本块]
# 中国帕金森病睡眠障碍管理专家共识
中华医学会神经病学分会帕金森病及运动障碍学组中国医师协会神经内科医师分会帕金森病及运动障碍学组  

通信作者:刘春风,苏州大学附属第二医院神经内科,苏州215004,Email:liuchunfeng@suda.edu.cn;陈海波,北京医院(国家老年医学中心)神经内科,北京100730,Email:chenhbneuro@263.net;王丽娟,广东省人民医院神经科,广州510080,Email : wljgd68@163.com  

【摘要】睡眠障碍是帕金森病的一种常见非运动症状。近年来,对于帕金森病睡眠障碍的发病机制、临床评估、治疗方法均取得新进展。为更好指导我国医师的临床实践,基于当前的循证医学证据,制订了《中国帕金森病睡眠障碍管理专家共识》。通过系统评价国内外近年来发表的帕金森病睡眠障碍领域相关循证医学研究证据,旨在进一步规范我国帕金森病睡眠障碍的诊断与治疗。  

【关键词】帕金森病;睡眠障碍;不宁腿综合征;REM睡眠行为障碍;失眠;日间思睡;睡眠呼吸障碍  

帕金森病(Parkinson's disease)是一种常见的中老年人神经系统退行性疾病,临床特征包括动作迟缓、震颤、肌强直等运动症状和非运动症状。睡眠障碍是帕金森病患者最常见的非运动症状,总体发生率约为 $47.66\\%{\\sim}89.10\\%^{[1]}$ ,并随病程逐年增加。  

帕金森病睡眠障碍的表现多种多样,常见的有失眠、日间过度思睡(excessive daytime sleepiness,EDS)、快速眼球运动睡眠期行为障碍[rapid eyemovement (REM) sleep behavior disorder,RBD]、周期性肢体运动(periodic leg movements in sleep,PLMS)、不宁腿综合征(restless legs syndrome,RLS)、睡眠呼吸障碍(sleep-disordered breathing,SDB)等[2。在中晚期帕金森病患者中,其睡眠障碍明显重于早期帕金森病患者,严重影响患者生活质量3。尽管帕金森病睡眠障碍在临床很多见,但却易被忽视。夜尿增多、日间思睡和睡眠维持困难可能是最常见的临床主诉4。规范评估和管理帕金森病的睡眠障碍,对于提高帕金森病的整体诊疗质量、改善患者预后具有重要的意义\"。为规范帕金森病睡眠障碍的诊断和治疗,中华医学会神经病学分会帕金森病及运动障碍学组和中国医师协会神经内科医师分会帕金森病及运动障碍学组组织专家编制了适合中国帕金森病患者睡眠障碍的专家共识,以期对帕金森病睡眠障碍的临床规范化处理起到一定的指导作用。  

本共识专家委员会参考睡眠障碍国际分类第3 版 (international classification of sleep disorders -thirdedition,ICSD-3)6、2018年中国帕金森病睡眠障碍的专家共识英文版\",同时借鉴2020年帕金森病非运动症状管理专家共识(2020)[7、国际帕金森病及运动障碍协会(InternationalParkinson andMovement Disorder Society,MDS)2011 及 2019 年非运动症状治疗循证指南[9],并通过检索国内外的主要电子数据库回顾2000年1月至2021年8月发表的文献资料,电子数据库包括PubMed、EMBASE、Cochrane Library、万方数据库、中国知网和中国生物医学文献数据库(China BiologyMedicinedisc,CBM),检索词为“帕金森病”“睡眠障碍”“失眠”“思睡”“快速眼动睡眠期行为障碍”“不宁腿”“不安腿”“睡眠呼吸”“夜尿”“异态睡眠”“睡眠发作”及相对应的英文检索词。  

根据2016年中华医学会发布的《制定/修订<临床诊疗指南 $\\ '>$ 的基本方法和程序》10],本专家共识采用的推荐等级分为 $\\mathrm{A}_{\\setminus}\\mathrm{B}_{\\setminus}\\mathrm{C}_{\\setminus}\\mathrm{D}4$ 级(A级最强,D级最弱)\":A级推荐:基于循证医学I级证据或获得大多数认可的II级证据,若无禁忌则可直接用于临床实践;B级推荐:基于II级循证医学证据或高度一致的专家共识,适应证充分时可应用;C级推荐:  

基于循证医学III级证据或专家共识,可在与患者讨论后应用;D级推荐:可选择性方案,需告知患者可能潜在的危险,不用于无适应证的患者。
# 一、失眠
失眠是帕金森病常见的睡眠障碍类型,发生率为 $30.0\\%{\\sim}86.8\\%$ [。失眠是指尽管有合适的睡眠机会和睡眠环境,依然对睡眠时间和(或)质量感到不满足,并且影响日间社会功能的一种主观体验。主要症状表现为人睡困难(人睡潜伏期超过$30\\;\\mathrm{min}\\,\\mathrm{.}$ )、睡眠维持障碍(整夜觉醒次数 $^{\\geqslant2}$ 次,每次觉醒时间 ${>}5\\;\\mathrm{min}$ ;或总觉醒时间 ${>}30\\ \\mathrm{min}$ )、早醒、睡眠质量下降和总睡眠时间减少(通常少于 $6.5\\;\\mathrm{h}$ ),同时伴有日间功能障碍[12]。中国帕金森病患者多以睡眠维持困难、睡眠结构紊乱为主[13]  

帕金森病失眠的常见因素包括性别、病程、抑郁焦虑、导致睡眠破碎的因素(如夜间运动症状、精神症状、夜尿、疼痛、肌张力障碍)以及内源性昼夜[ ] 4 15别是晚上使用时,均可能增加失眠风险[4,15]。多巴胺能药物可以改善夜间运动功能障碍,但也可能使睡眠质量恶化\"。研究发现较高剂量的多巴胺受体激动剂与早醒、夜间频繁觉醒、主观的睡眠不足有关,主要影响睡眠维持,因此须考虑多巴胺能药物使用的时间和剂量[1]]  

F帕金森病失眠的评估需要结合临床病史、睡眠问卷及客观监测,如多导睡眠图(polysomnography,PSG)、体动记录仪。临床上可选用一些量表进行筛查,如匹兹堡睡眠质量指数量表(PittsburghSleepQualityIndex,PSQI)、帕金森病睡眠量表(Parkinson Disease Sleep Scale ,PDSS 或 PDSS2)[18]帕金森病失眠的治疗[\"主要包括:  

1.非药物治疗:(1)失眠认知行为治疗(cognitive-behavioral therapy for insomnia, CBT-1) :无论帕金森病失眠病因如何,应首先采取CBT $\\cdot\\!\\!\\!\\int^{[20]}$比如睡眠卫生教育、刺激控制治疗、限制睡眠、矛盾意念(反向意念控制,转移对人睡过度关注)、放松疗法等。该治疗被美国睡眠医学学会作为失眠治疗的A级推荐。音乐疗法同样可以作为治疗方法之一。(2)体育锻炼:最近一项荟萃分析纳人10项随机试验、2项非随机对照试验(690例患者),结果显示体育锻炼,尤其是中-高强度体育锻炼对帕金森病睡眠质量有改善作用2。PSG也证实了高强度体育锻炼对改善睡眠的有效性[22。其他治疗,如太极[23]、气功[24]对帕金森病患者失眠也可能有效。  

(3)强光治疗:日间和(或)睡前接受强光治疗对帕金森病患者失眠可能有效[25-27]。(4)重复经颅磁刺激:通过刺激或抑制不同大脑区域的神经活动来改变皮质兴奋性,可改善主观睡眠质量和失眠症状[28-29]。(5)脑深部电刺激(deep brain stimulation,DBS)疗法:双侧丘脑底核脑深部电刺激(subthalamic nucleus deep brain stimulation,STN-DBS)能显著改善患者夜间睡眠质量,部分获益于运动症状的改善及焦虑情绪缓解[30]  

2.药物治疗:包括原发性失眠的治疗和(或)因为帕金森病进展而出现的继发性失眠的治疗。(1)失眠与夜间帕金森病运动症状加重或夜间剂末现象有关,应首先优化多巴胺能治疗药物:睡前加用复方左旋多巴缓释剂或日间加用长效多巴胺受体激动剂(如罗替高汀贴剂[31-32]、普拉克索缓释片[3-34]、罗匹尼罗缓释片[35])、单胺氧化酶B抑制剂如雷沙吉兰[3]、恩他卡朋双多巴片[3]等。(2)针对帕金森病原发性失眠的药物治疗可参照《中国成人失眠诊断与治疗指南(2017版)》[12}。但目前仅有右佐匹克隆[38]、褪黑素[39-41]、阿戈美拉汀[42]多塞平[43]在帕金森病患者中进行了相关小样本临床研究。右佐匹克隆适用于原发性人睡困难和睡眠维持障碍的帕金森病患者;褪黑素和阿戈美拉汀可考虑用于同时合并失眠、RBD的帕金森病患者及昼夜节律失调性睡眠觉醒障碍。(3)帕金森病疾病常常伴随抑郁、焦虑症状,这也能诱发和加重失眠。一项荟萃分析纳人18个随机对照研究,共有1789名参与者,发现普拉克索可显著改善帕金森病患者伴发的抑郁症状,提高生活质量\"。如果夜间运动症状改善,但失眠症状并未见好转,且存在抑郁或焦虑情绪,可以考虑使用具有改善睡眠作用的抗抑郁、抗焦虑药物,以期改善帕金森病抑郁、焦虑共病的失眠\"。(4)中药和针灸:乌灵胶囊、养血清脑颗粒、复方蓉益智胶囊、归脾丸以及针灸等可能有效[45-47]。  

推荐意见:(1)对于有明确病因导致失眠的帕金森病患者,首先针对病因进行治疗,如调整相关药物使用剂量及时间、改善夜间运动症状、治疗焦虑抑郁等(A级推荐)。(2)非药物治疗:包括CBT-I、中-高强度体育锻炼(A级推荐)、强光治疗、重复经颅磁刺激(C级推荐)。(3)药物治疗:对于夜间帕金森病运动症状控制不佳有关的患者可选用罗替高汀贴剂、普拉克索缓释片、罗匹尼罗缓释片(B级推荐);复方左旋多巴缓释释剂、雷沙吉兰、恩他卡朋双多巴片(C级推荐)。原发性失眠患者可选用褪黑素、右佐匹克隆(B级推荐);阿戈美拉汀(C级推荐)。
# 二、EDS
EDS指在日间应该维持清醒的主要时段难以持续保持清醒和警觉状态,出现难以抑制的困倦欲睡甚至突然人睡。帕金森病伴EDS的发生率为$21\\%{\\sim}76\\%$ ,我国报告约为 $13.2\\%{\\sim}46.9\\%^{[1]}$ 。EDS可出现在帕金森病运动症状之前,随着病程的进展出现增加。对早期帕金森病患者随访5年,EDS的发生率可从 $11.8\\%$ 上升至 $23.4\\%$ 。EDS的发生率易受男性、高龄、非震颤亚型、自主神经功能障碍、认知损害、精神状态及帕金森病疾病的严重程度、病程影响[48]。  

帕金森病合并EDS主要原因有睡眠-觉醒周期改变、多巴胺激动剂的不良反应、夜间睡眠质量差、遗传因素、食欲素水平降低、苯二氮草类药物使用、自主神经功能障碍和抑郁\"  

帕金森病合并EDS的诊断主要依据病史,应详细询问患者及家属睡眠相关情况,包括日间思睡及夜间睡眠情况、用药史、合并症以及其他可能的影响因素。临床上可以选择相关量表进行评估,如Epworth 嗜睡量表、Stanford评分、PSQI和PDSS[49]  

1.非药物治疗:可用一些非药物治疗,如CBT改善失眠继发的EDS[20]、强光治疗[50-51]、重复经颅磁[]  

2.药物治疗:如EDS与药物使用有关,抗组胺作用的药物、苯二氮草类及其他具有镇静作用的抗抑郁药应减量或停用。减少多巴胺能药物剂量及改变多巴胺受体激动剂类型,选择司来吉兰与左旋多巴联合使用均可一定程度减轻EDS。莫达非尼[53]、哌甲酯[54]、肾上腺受体激动剂(如咖啡因[55]伊曲茶碱56)、羟丁酸钠57均有病例报道显示可改善帕金森病患者的EDS,但需要大样本随机双盲对照试验验证。阿托莫西汀可考虑用于治疗伴有抑郁的帕金森病患者的EDS[58]  

推荐意见:(1)明确EDS的诊断,建立良好的睡眠卫生,识别并治疗共存的睡眠障碍及药物相关的EDS(A级推荐)。(2)非药物干预:包括CBT、强光治疗、重复经颅磁刺激(C级推荐)。(3)药物治疗:可选用莫达非尼、哌甲酯、伊曲茶碱、羟丁酸钠、阿托莫西汀(C级推荐)。
# 三、RBD
RBD是一种以 REM睡眠期间伴随梦境及肢体活动为特征的睡眠疾病,发病时暴力行为可造成自身及同床者伤害并破坏睡眠。临床表现主要包括生动或暴力的梦境及其与梦境相关的行为或情感反应,可出现不同程度的行为动作甚至是暴力行为,如殴打同床者,甚至下床活动、伤人或自伤,严重时可导致硬膜下血肿、骨折等。约 $22.2\\%{\\sim}60.0\\%$的帕金森病患者合并RBD,其临床症状较不合并RBD的帕金森病患者相对更重[59]。约 $33\\%{\\sim}65\\%$ 的RBD存在睡眠相关伤害行为。  

目前RBD确切发病机制还不清楚,可能与调节REM睡眠的脑干相应部位损害有关。此外,也有学者认为与 $\\upalpha$ -突触核蛋白的异常聚集、帕金森病相关基因(GBA、LRRK2、SNCA)多态性有关[]  

PSG监测对于RBD的诊断非常重要,可以鉴别SDB导致的假性RBD(pseudo-RBD)。PSG最显著的电生理特征为REM睡眠期持续甚至亢进的骨骼肌活动,可分为时相性和紧张性活动。但由于PSG设备复杂、费用高,对睡眠技师要求高,临床上可选择相关量表对RBD进行筛选,常用的有RBD筛查问卷(RBDSQ),Mayo睡眠问卷,RBD问卷-香港版(RBD-HK)和 PDSS[611]  

1.非药物治疗:对伴有伤害性行为的RBD患者,及药物治疗仍有RBD残余症状的患者,提供安全的睡眠环境是非药物治疗的标准治疗手段\"创造一个安全的睡眠环境,包括在床边设置围栏或放置柔软地毯、避免尖锐或易碎物品放置在床边,若患者帕金森病病情允许,可建议患者单独就寝或使用独立卧室,以避免对同床者造成伤害。患者需要保持规律作息时间,避免有精神兴奋作用药物的使用和酒精的刺激。对于一些可能导致或加重RBD的药物,可减量、停用或替换,常见需要注意的药物,如选择性5-羟色胺再摄取抑制剂、选择性5-羟色胺/去甲肾上腺素再摄取抑制剂、三环类抗抑郁药物、单胺氧化酶抑制剂、米氮平、胆碱酯酶抑制剂、β阻滞剂、曲马多、咖啡因、乙醇、苯二氮草类、巴比妥类药物、甲氧基氨基甲酸盐、喷他佐辛等[62]。有学者发现吡贝地尔可能会诱发帕金森病患者出现RBD症状,目前尚需进一步证实。低强度纯音听觉刺激也可作为非药物治疗的一种选择[63]  

45 32. $3{\\sim}12~\\mathrm{mg}$睡前服用。根据临床RBD研究结果,共137例RBD患者接受褪黑素单药治疗,其中45例 $32.9\\%$ )明显获益,37例( $27.0\\%$ )部分获益,50例 $(40.1\\%)$ )未获益[4]。然而最近一项随机双盲、安慰剂对照试验发现采用褪黑素缓释剂 $4~\\mathrm{mg}$ 连续8周干预并未改善该组患者的RBD症状[65]。(2)氯硝西泮:推荐剂量为 $0.25{\\sim}2.0\\ \\mathrm{mg}$ ,睡前服用。氯硝西泮治疗特发性RBD的疗效较肯定,但在帕金森病合并RBD中的疗效并未证实。最近一项随机安慰剂对照试验发现氯硝西泮和安慰剂均能改善帕金森病患者可能的RBD症状,但该研究样本量小,RBD也并未经过PSG验证[\"。由于氯硝西泮增加了帕金森病患者跌倒风险,当其他药物效果不明显时氯硝西泮可以作为一个替代性选择,通常从小剂量开始,根据治疗效果调整剂量,但一定要告知患者和家属氯硝西泮的不良反应,包括日间过度镇静、阳痿、运动失调、意识模糊、记忆缺失等。褪黑素和氯硝西泮是目前临床上改善帕金森病合并RBD的首选药物[]。(3)多巴胺受体激动剂:如罗替高汀透皮贴[68]和普拉克索,有小样本研究结果显示有效,也可作为临床治疗考虑,适合同时需要改善运动症状或者合并夜间运动症状的帕金森病患者。(4)其他:小样本研究发现褪黑素受体激动剂(雷美替胺[70-71]阿戈美拉汀[2)对RBD有一定改善作用。  

推荐意见:(1)PSG监测是RBD诊断的必要手段,在条件允许的情况下,应该进行PSG检查明确RBD诊断;优化RBD治疗方案,减少或停用可能加重RBD的药物(A级推荐)。(2)非药物干预:提供安全的睡眠环境(A级推荐)。(3)药物治疗:可选用褪黑素、氯硝西泮(B级推荐);多巴胺受体激动剂(C级推荐);雷美替胺、阿戈美拉汀等褪黑素受体激动剂(C级推荐)。  

四RLS  

RLS是一种常见的神经系统感觉运动障碍,帕金森病患者出现RLS的风险是一般人群的3倍,平均发生率 $12\\%$ ,尤其在已接受治疗的帕金森病患者中其患病率较初诊未治者更高。在我国,帕金森病合并 RLS 总体发生率约 $33\\%^{[73]}$ 。帕金森病患者RLS发生的危险因素包括:失眠、抑郁、认知障碍、病程、多巴胺能药物的使用、帕金森病起病年龄、RLS起病年龄、帕金森病疾病严重程度等[74]。  

PSG通过检测周期性肢体运动指数(periodicleg movement index,PLMI)可作为帕金森病合并RLS 的支持诊断依据[75]。PSG研究结果显示,相较于原发性RLS患者,帕金森病合并RLS患者在睡眠中PLMI计数上更低,这一现象可能是由于治疗帕金森病的多巴胺能药物同时改善了RLS症状[76]临床上,帕金森病伴发的RLS症状尤其需注意与夜间腿痉挛、异动症、晨起肌张力障碍以及帕金森病相关的疼痛进行鉴别。  

对合并RLS的帕金森病患者需询问可能导致RLS的药物,主要包括抗抑郁药物(如米氮平、西酞普兰等)抗精神病药物(如奥氮平、喹硫平等)和抗癫痫药物(如托吡酯、唑尼沙胺等)[75]。检测血常规及贫血相关指标除外铁缺乏所致的RLS。还需要除外肾功能不全、糖尿病、周围神经病等。  

1.非药物治疗:非药物治疗一般可作为轻症患者的主要干预[77-78]。主要包括:(1)规律作息,坚持良好的睡眠卫生,睡前温水浴或进行简单的活动可能有效,尽可能避免睡眠剥夺,创造安静就寝环境;(2)避免或减少咖啡因、茶、能量饮料、尼古丁、酒精等摄入,加用富含维生素和铁的饮食;(3)有氧运动、抗阻力训练;(4)慎用可能诱发或导致RLS症状加重的药物如多巴胺受体拮抗剂、抗抑郁药、抗组胺药、钙离子通道阻滞剂等。  

2.药物治疗:目前缺少帕金森病合并RLS的前瞻性干预治疗研究,主要治疗药物参照原发性RLS的治疗方案,根据帕金森病病情情况进行合理调整。考虑到RLS症状恶化的风险,应避免将左旋多巴作为治疗帕金森病中RLS的主要药物。对于高龄、合并认知障碍或无法耐受多巴胺受体激动剂的帕金森病患者,最优剂量下添加夜间左旋多巴给药可改善RLS症状,同时减少日间RLS的症状反跳[77,79-80]  

RECOVER研究描述了多巴胺受体激动剂罗替高汀对帕金森病和RLS的疗效[\"。与安慰剂相比,罗替高汀透皮贴剂可同时改善帕金森病运动症状和夜间腿动症状,有助于帕金森病合并RLS患者的治疗,在另 4项研究中也得到证实[82-85]。推荐罗替高汀起始剂量为 $2~\\mathrm{mg/d}$ ,逐步滴定至最佳剂量[75]。我国多中心、随机双盲、安慰剂对照研究纳人306例RLS患者,结果显示普拉克索可显著改善RLS症状]。其他非麦角类多巴胺受体激动剂,包括罗匹尼罗、吡贝地尔也可以用于帕金森病合并RLS患者的治疗,治疗策略可参照原发性RLS治疗推荐及方案进行选择[75,7]。上述多巴胺受体激动剂调整剂量时需谨慎,警惕幻觉、撤药综合征、冲动控制障碍等不良反应。  

为降低RLS症状恶化发病风险,帕金森病患者可选用 $\\alpha-2-8$ 钙通道配体如加巴喷丁-恩那卡比、加巴喷丁和普瑞巴林[\\*7],但目前在帕金森病患者中直接证据欠缺。对于伴有严重RLS感觉症状或合并有神经病理性疼痛的帕金森病患者,此类药物或可改善患者症状。当症状进一步加重时,可选择阿片类药物作为二线治疗[88]  

此外,当患者血清铁蛋白水平 ${<}75~\\upmu\\mathrm{g/L}$ 和(或)转铁蛋白饱和度 $<\\!20\\%$ 时,建议补充铁剂。推荐首选口服铁剂联合维生素C治疗3个月,并评估铁蛋白水平[78。若口服铁剂无效,可考虑将静脉注射铁剂作为替代治疗方案,但建议在院内进行。荟萃分析结果显示STN-DBS手术治疗对帕金森病患者睡眠质量和RLS有显著改善[9]。对伴有中重度RLS症状的帕金森病患者可考虑STN-DBS[9091],但也有报道指出 STN-DBS 可诱发RLS[92]。因此术后在多巴胺受体激动剂药物减量时需严密评估。  

推荐意见:(1)对合并RLS的帕金森病患者要完善相关检查除外继发因素,包括相关药物(如抗抑郁药、抗癫痫药等)和相关疾病(如缺铁性贫血、糖尿病周围神经病、肾功能不全等)(A级推荐)。(2)罗替高汀用于改善帕金森病运动症状和RLS症状(B级推荐);其他多巴胺受体激动剂如普拉克索、罗匹尼罗、吡贝地尔在帕金森病合并RLS患者中由于缺少大样本的临床研究,需要积累证据(C级推荐) $\\mathbf{\\varepsilon}_{\\circ}(3)\\alpha\\mathbf{-}2\\mathbf{-}8$ 钙通道配体如加巴喷丁-恩那卡比、加巴喷丁和普瑞巴林可作为帕金森病合并RLS的可选治疗方案,症状恶化风险相对低(C级推荐)。(4)阿片类药物作为其他治疗方案无效或难治性RLS的治疗(D级推荐)。  

五、SDB  

SDB是一组睡眠中呼吸异常的疾病,伴或不伴清醒期呼吸功能异常。包括阻塞性睡眠呼吸暂停(obstructive sleep apnea,OSA)及中枢性睡眠呼吸暂停、陈-施呼吸、睡眠低通气综合征及与呼吸努力相关的觉醒障碍如上气道阻力综合征等一系列临床综合征。  

帕金森病中OSA的发生率约为 $20\\%{\\sim}60\\%$ 。高龄、男性可增加 OSA 发病风险[93]。合并 SDB 的帕金森病患者日间可感觉疲劳、困倦、精神萎靡、晨起头痛、迟钝,以及记忆力、注意力、判断力和警觉性下降。可出现抑郁、焦虑、易激惹、口干、性欲减退和高血压等。严重者可发展为肺心病、心律失常等,可发生夜间猝死。研究发现,帕金森病患者的OSA与思睡、认知功能障碍甚至运动症状密切相关,对帕金森病患者长期预后产生不利影响[4]。  

帕金森病中OSA的发病机制目前尚未明确,可能与疾病本身的退行性改变累及脑干、导致呼吸中枢的功能损害有关。其次,帕金森病运动症状累及上呼吸道肌肉结构导致睡眠期上气道阻塞及通气量异常以及自主神经系统功能障碍影响呼吸调控也可引发OSA。此外,失眠与睡眠中断、多巴胺激动剂也会增加OSA的风险[95]  

PSG是诊断OSA的“金标准”。但详细的病史采集也必不可少,重点询问打鼾、睡眠期呼吸暂停、晨起头痛、高血压以及日间思睡的频率及严重程度等。体格检查应包括以下方面:身高及体重、体重指数、颈围、血压、心率及详细的上呼吸道检查。  

1.非药物治疗:包括改变生活习惯、减肥、控制体重与饮食、适当锻炼、停止或减少饮酒与吸烟、慎用镇静药物以及其他会导致或加重OSA的药物(比如氯硝西泮)、侧卧睡眠、抬高床头及避免日间过度劳累。  

持续气道正压通气(continuouspositive airwaypressure,CPAP):CPAP是治疗帕金森病合并OSA最有效的方法[],有利于改善OSA相关的EDS[97]有随访研究发现接受CPAP治疗OSA的帕金森病患者运动症状相对更稳定[8。其他非药物治疗包含伺服式通气以及氧疗。悬雍垂聘咽成形术[\"、下颌前伸矫治器有望成为治疗手段之一-  

2.药物治疗:相关研究较少,药物对OSA的影响并不明确。左旋多巴对上气道梗阻可能有帮助[1°2]。有研究结果显示,睡前服用息宁[13]减轻帕金森病患者夜间OSA症状。需要更多前瞻性研究证实OSA治疗中多巴能药物作用。  

推荐意见:(1)改变不良生活习惯、控制体重、适当锻炼、慎用镇静药物以及其他会导致或加重OSA的药物、侧卧睡眠、抬高床头、避免日间过度劳累(A级推荐)。(2)CPAP是帕金森病合并OSA的一种有效治疗措施(A级推荐)。
# 六、其他异态睡眠
目前缺少除RBD之外的帕金森病其他异态睡眠的高质量研究。帕金森病其他异态睡眠的表现形式包括夜间遗尿、梦魔、夜惊、睡行症和睡眠相关性进食障碍等[14],以非快速眼球运动(non-rapideye movement,NREM)异态睡眠多见。帕金森病中各种异态睡眠可同时伴随出现,称异态睡眠重叠障碍[105]。其中,睡行症是一种发生于NREM期的异态睡眠,正常人群发生率约 $1.0\\%{\\sim}2.3\\%$ ,而在帕金森病患者中可达 $10\\%^{[106]}$ 。伴有睡行症的帕金森病患者有以下特点:病程长、睡行症状在成年出现、与  

RBD关系紧密[10]。约 $80\\%$ 具有睡行症病史的帕金森病患者完成PSG后最终诊断为RBD。帕金森病的NREM异态睡眠与运动症状恶化、认知功能减退和抑郁有关[105,107]。但由于目前帕金森病相关的非RBD异态睡眠研究极少,其发病情况及机制有待深人研究。  

帕金森病其他异态睡眠的诊断可根据ICSD-3进行识别。PSG有助于鉴别其他异态睡眠与RBD,或发现多种异态睡眠共存的情况,同时客观评估睡眠中的微觉醒情况、睡眠结构与异常睡眠事件。  

1.非药物治疗:异态睡眠患者中约1/3并不需要药物治疗。必要的安全保证措施和良好的睡眠卫生应作为NREM异态睡眠患者的一线治疗方案。催眠疗法、CBT有助于改善一部分NREM异态睡眠或异态睡眠重叠障碍患者的症状[108]  

2.药物治疗:单药或多药联合治疗可改善大部分患者的症状。褪黑素可通过改善睡眠结构降低成人异态睡眠事件的发生率。苯二氮草类药物为普通人群异态睡眠治疗最常用药物 $(47.1\\%)$ ),对于存在致伤风险的患者,氯硝西泮可作为首要选择,但应用时需关注药物滥用及跌倒风险[108]  

推荐意见:(1)建议将保证安全措施和良好的睡眠卫生作为帕金森病NREM异态睡眠的首选治疗方案(A级推荐)。(2)氯硝西泮为治疗帕金森病异态睡眠的一种可选择性药物,但要注意其用药风险(C级推荐)。  

目前帕金森病睡眠障碍的研究结果,缺少高质量的大样本随机、前瞻性研究,故本共识的推荐仅供参考。临床医师应遵循指南,重视个体化治疗,结合临床治疗经验,识别并积极干预帕金森病的睡眠障碍,以提高患者生活质量。

"""
response = """
// 节点更新
MERGE (n:Disease {name: '帕金森病'})
SET 
    n.description = coalesce(n.description, '一种常见的中老年人神经系统退行性疾病，临床特征包括动作迟缓、震颤、肌强直等运动症状和非运动症状。'),
    n.severity = coalesce(n.severity, '中等');

MERGE (n:Symptom {name: '失眠'})
SET 
    n.description = coalesce(n.description, '尽管有合适的睡眠机会和睡眠环境，依然对睡眠时间和质量感到不满足，影响日间社会功能的主观体验。'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '30.0%-86.8%');

MERGE (n:Symptom {name: '日间过度思睡'})
SET 
    n.description = coalesce(n.description, '在日间应该维持清醒的主要时段难以持续保持清醒和警觉状态，出现难以抑制的困倦欲睡。'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '21%-76%');

MERGE (n:Symptom {name: 'REM睡眠行为障碍'})
SET 
    n.description = coalesce(n.description, '以REM睡眠期间伴随梦境及肢体活动为特征的睡眠疾病，发病时暴力行为可造成自身及同床者伤害。'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '22.2%-60.0%');

MERGE (n:Symptom {name: '不宁腿综合征'})
SET 
    n.description = coalesce(n.description, '患者在休息时感到腿部不适，会有一种强烈的想要移动的冲动。'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '12%');

MERGE (n:Symptom {name: '睡眠呼吸障碍'})
SET 
    n.description = coalesce(n.description, '是一组睡眠中呼吸异常的疾病，包括阻塞性睡眠呼吸暂停和中枢性睡眠呼吸暂停等。'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '20%-60%');

MERGE (n:Symptom {name: '周期性肢体运动'})
SET 
    n.description = coalesce(n.description, '患者在睡眠中会出现反复的肢体不自主运动。'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '不详');

// 关系更新
MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '帕金森病'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '日间过度思睡'
MATCH (to) WHERE to.name = '帕金森病'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.85),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = 'REM睡眠行为障碍'
MATCH (to) WHERE to.name = '帕金森病'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '不宁腿综合征'
MATCH (to) WHERE to.name = '帕金森病'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.8),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '睡眠呼吸障碍'
MATCH (to) WHERE to.name = '帕金森病'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.8),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

"""
