[metadata]
file_name = "中国6岁以下儿童就寝问题和夜醒治疗指南（2023）.md"
processed_at = "2024-12-18 16:48:29"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-18 09:55:57"
message = """

[隶属文件名]
中国6岁以下儿童就寝问题和夜醒治疗指南（2023）.md
[隶属文件分块名]
中国6岁以下儿童就寝问题和夜醒治疗指南（2023）/001-完整文档.md
[文本块]
# 中国6岁以下儿童就寝问题和夜醒治疗指南(2023)
中国医师协会睡眠专业委员会儿童睡眠学组中华医学会儿科学分会儿童保健学组中国医师协会儿童健康专业委员会中华儿科杂志编辑委员会  

通信作者:江帆,国家儿童医学中心上海交通大学医学院附属上海儿童医学中心发育行为儿科,上海200127,Email:fanjiang@shsmu.edu.cn  

【摘要】就寝问题和夜醒是6岁以下儿童失眠的主要表现,可对儿童生长发育和家长身心健康造成不良影响。为了规范我国这类儿童常见睡眠问题的临床治疗决策,中国医师协会睡眠专业委员会儿童睡眠学组、中华医学会儿科学分会儿童保健学组、中国医师协会儿童健康专业委员会、中华儿科杂志编辑委员会特制订“中国6岁以下儿童就寝问题和夜醒治疗指南(2023)”。基于当前可得证82073568 82071493 81773443 20226岁以下儿童就寝问题和夜醒的治疗水平,促进儿童睡眠健康。  

基金项目:国家自然科学基金(82073568、82071493、81773443);上海市教育委员会专项(2022幼1-2)  

就寝问题和夜醒是儿科门诊中家长常见的就诊主诉之一,国外报道在6岁以下儿童中的发生率为 $20\\%{\\sim}30\\%^{\\left[1\\right]}$ ,而我国为 $30\\%{\\sim}40\\%^{[2-4]}$ 。依据诊断标准,6岁以下儿童就寝问题和夜醒属于失眠障碍的诊断范畴,相关睡眠问题及其日间功能受损(如过度困倦、注意力不集中、多动、情绪问题等)每周出现 $_{\\geqslant3}$ 次并持续 $\\geqslant3$ 个月为慢性失眠障碍,而短期或急性失眠障碍为持续6 $<\\!3$ 个月[]。一般而言,婴儿3\\~6月龄时睡眠才逐渐发育成熟,形成夜间连续睡眠,因此临床上仅对6月龄以上的儿童诊断就寝问题和夜醒,并首先应排除器质性疾病如睡眠呼吸障碍、胃食管反流以及疼痛等[5]。就寝问题主要评估指标是人睡潜伏期,即在合适的作息时间安排下,从家长准备安顿儿童睡觉(通常以关灯时间开始计算)到儿童真正人睡的时间,一般认为 ${>}20\\ \\mathrm{min}$具有临床意义\"。夜醒问题的临床界定尚未统一,美国国家睡眠基金会的专家共识认为1岁以上儿童每晚 $_{\\geqslant2}$ 次夜醒(每次醒来 $\\geq\\!5\\;\\mathrm{min}$ ),学龄前期儿童总夜醒时间 ${>}20\\ \\mathrm{min}$ 具有临床意义\"。年幼儿童就寝问题和夜醒的成因复杂,与睡眠调节能力和睡眠连续性发育较慢或不稳定有关,受内在因素(如气质)和外在因素(如睡眠环境、父母行为)的交互影响\\*\"。就寝问题主要与家长对儿童就寝行为的约束力不足有关,表现为就寝抗拒和拖延;而夜醒通常与不恰当的人睡条件依赖(如拍睡、抱睡、奶睡等)有关,主要表现为频繁地、长时间地夜间醒来,并且人睡需要家长干预或满足依赖条件[5]  

就寝问题和夜醒得不到及时干预会对儿童生长发育和家长身心健康造成不良影响[。目前美国睡眠医学会、西班牙儿科学会和睡眠研究会等多个组织制订了相关指南[8-1\"。但因社会经济文化和家庭养育观念不同,这些国外指南并不完全适用我国情况且存在诸多局限性。我国长期缺乏对就寝问题和夜醒这类常见儿童睡眠问题治疗的循证指南10]。2016年中国睡眠研究会制订的“中国失眠症诊断和治疗指南”未涉及6岁以下儿童[2};2017年中国卫生行业标准“0岁~5岁儿童睡眠卫生指南”以推荐睡眠卫生习惯为主,未涉及就寝问题和夜醒的治疗[13]。而近年来,相关研究证据不断涌现,也亟待纳人系统评价。鉴于此,中国医师协会睡眠专业委员会儿童睡眠学组、中华医学会儿科学分会儿童保健学组、中国医师协会儿童健康专业委员会和中华儿科杂志编辑委员会组织多学科临床医师、研究人员及方法学专家,自2021年12月起历时16个月制订了“中国6岁以下儿童就寝问题和夜醒治疗指南(2023)”(以下简称“本指南”),基于当前可获得证据,采用推荐分级的评价、制订与评估(grading   of   recommendations   assessment,development and evaluation,GRADE)系统,并充分考虑我国国情及患儿家属意愿和价值观,针对10个重要临床问题给出循证推荐意见,以期提高我国就寝问题和夜醒这类儿童常见睡眠问题的治疗水平,强化多学科专业人员的标准化临床服务和实践能力,促进高质量研究工作开展。
# 一、指南形成方法
本指南严格遵循临床实践指南制订方法学,符合美国医学科学院临床实践指南概念,参考“中国制订/修订临床诊疗指南的指导原则(2022版)”“世界卫生组织指南制订手册”及中国临床实践指南评价体系[4-15],采用GRADE方法进行证据质量及推荐意见分级(表1)[16],并按照卫生保健实践指南的报告条目(reporting items for practice guidelines inhealthcare,RIGHT)进行报告[17]。本指南已在国际实践指南注册平台(InternationalPracticeGuidelines Registry Platform, http ://guidelines-registry.cn)完銀成銀注銀册(IPGRP-2022CN304),指南计划书在2023年中华儿科杂志第2期刊出[8。通过专家组征询和指导委员会讨论构建初始临床问题,再经我国东、中、西和东北地区8个省、直辖市各级医疗机构271名医护人员进行重要性评价,最终避选出10个临床问题。进一步通过证据检索评价、2轮德尔菲调研和面对面专家讨论达成共识(同意率 $_{>2/3}$ ),最终形成指南推荐意见,并提交指导委员会和外部同行专家评审,经批准、发布、发表后,本指南将按计划传播、实施、评价并定期更新。  

表1证据质量和推荐分级的评价、制订与评估  

本指南适用于各级医疗机构儿童保健科、发育行为儿科、儿童精神心理科、儿科护理等多学科相关医师、护士、技术人员(如心理咨询或治疗师)和教研人员以及公共卫生、教育及心理健康机构等从事相关工作的专业人员。目标人群为6岁以下发育正常的儿童,不包括共患躯体疾病、神经发育障碍或其他精神障碍的儿童。以下临床问题及推荐意见中的儿童,如无特殊说明均指6岁以下儿童。  

二、推荐意见  

临床问题1:行为治疗对改善儿童就寝问题和夜醒有效吗?  

推荐意见1:行为治疗对改善儿童就寝问题和夜醒有效,推荐作为一线方案(1B)。  

行为治疗主要包括标准消退法、渐进消退法、randomized controlled trial  RCT [,]证据共纳人涉及就寝问题的6篇随机对照试验(randomized controlled trial,RCT)研究(干预组462例,对照组 328例)[19-24],结果显示行为治疗可以缩短儿童的人睡潜伏期[标准化均数差(standardized mean difference , $S M D)\\!=\\!-0.44\\,,\\,95\\%C I$$-0.81{\\sim}{-}0.07]$ ;涉及夜醒时间共纳人7项RCT研究-0.49\\~-0.07 8 RCT行为治疗可以减少夜醒时间 $(S M D{=}{-}0.28\\,,95\\%C I$$-0.49{\\sim}{-}0.07\\,)$ 。此外,涉及夜醒次数的有8项RCT95% -0.83\\~-0.13 [ , ]显示行为治疗可以减少夜醒次数 $(S M D{=}{-}0.48$ ,$95\\%C I-0.83{\\sim}{-}0.13\\,)$  

现有指南和共识均将行为治疗作为一线治疗方案[8,。但需要根据儿童睡眠问题特征、气质类型、家长意愿及可接受度等综合考虑,选择不同类型的行为治疗技术[28-29]。建议行为治疗应由具备儿童睡眠医学背景知识的医护或心理健康专业人员与家长共同商定方案,并在实施过程中给予家长指导[30-31]  

临床问题2:早期睡眠卫生习惯指导能否减少儿童就寝问题和夜醒发生?  

推荐意见2:早期(母亲孕期或婴儿3月龄内)睡眠卫生习惯指导可以减少儿童就寝问题和夜醒的发生且父母接受程度较高,推荐作为改善儿童就寝问题和夜醒的干预方法(1B)。  

早期睡眠卫生习惯指导通常包含睡眠的基本知识、睡眠环境、睡床方式、规律作息、睡前活动、人睡方式及睡眠姿势等,可结合个体或团体、面对面或远程等不同形式,在母亲孕期检查、儿童定期健康检查与家庭访视时进行[13]  

8项RCT研究从母亲孕期或婴儿3月龄内开始实施睡眠卫生指导,结果显示虽然不能显著降低婴儿人睡潜伏期 $>\\!15\\;\\mathrm{min}$ 的发生率[32],但婴儿16和40周龄时睡前程序耗时 ${>}45\\ \\mathrm{min}$ 的发生率明显降低,且更可能自我安抚入睡[32]。1项RCT研究未发现早期睡眠卫生习惯指导能够减少婴儿夜醒时间[33],但在7篇报告夜醒次数的研究中[32-38],4篇显示婴儿6周龄至6月龄夜醒次数明显减少[335-36, 38]1项RCT研究将孕晚期母亲随机分为常规护理(对照组)、食物-活动-母乳喂养干预、睡眠干预以及食物-活动-母乳喂养-睡眠联合干预4组,其中睡眠和联合干预组在母亲产前进行1h的睡眠宣教,产后3周加强睡眠培训,结果显示干预内容中含睡眠干预的婴儿6月龄时客观评估夜醒次数较少[33]。此外,儿童1.0、2.0、3.5和5.0岁时跟踪随访发现,接受睡眠指导的父母,在4\\~6月龄持续采用干预策略的概率较高(睡眠组: $\\scriptstyle O R=1.63\\,,\\,95\\%C I\\ 1.14\\sim2.33$ ;联合组: $O R{=}1.45\\,,95\\%C I\\,1.01{\\sim}2.07\\,)$ ,儿童至3.5岁时发生就寝抵抗、睡眠启动及夜醒等睡前行为困难减少[几何均值比(ratio of geometric means, $R G M)=$$0.97\\,,95\\%C I\\,0.95{\\sim}0.98\\,]$ ,睡眠时间增加( $\\scriptstyle{\\beta=0.15}$ ,标准误 $=\\!0.02$ )[39]。1篇RCT研究分别在婴儿4周龄(小册子和DVD)8周龄(电话咨询)和13周龄(团体)时给予家庭婴儿睡眠和哭吵模式、处理方案、哭吵原因及父母自我护理的指导信息,虽然父母报告的婴儿夜间睡眠问题未明显下降,但 $90\\%$ 以上的家长反馈在接收到的各种婴儿照护信息中,婴儿睡眠相关的信息对育儿最有帮助[4]。  

3项RCT研究从婴儿3\\~12月龄时开始实施睡眠卫生宣教。其中1项RCT研究包含127名3月龄婴儿(干预组33名,对照组94名),在婴儿3月龄时给予母亲或家庭 $20{\\sim}30~\\mathrm{min}$ 的现场培训并提供培训笔记,并在6、9、12和18月龄重复宣教,结果显示婴儿12月龄时人睡潜伏期短 $5\\ \\mathrm{min}\\,,9$ 和12月龄时夜醒后再次入睡时间少 $5~\\mathrm{min}$ ,但夜醒次数差异无统计学意义[41]。另1项含有82名2\\~4月龄婴儿(干预组41名,对照组41名)的RCT研究,给予干预组$90\\;\\mathrm{min}$ 睡眠课程,8周后随访,结果未发现夜醒次数减少,但最长睡眠时间显著延长[ $(4.3{\\pm}1.1)\\$ 比( $3.0\\pm$$0.7\\,)\\mathrm{h}\\,,P{<}0.001\\]^{[42]}$ 。在157名6\\~12月龄婴幼儿(干预组66名,对照组91名)的RCT研究中,对照组给予基本睡眠卫生建议(如规律作息、积极就寝程序),而干预组增加了婴幼儿睡眠结构、睡眠需求及人睡技巧等方面的睡眠教育,结果显示3个月后两组婴幼儿夜醒时间和夜醒次数均显著减少,但两组之间差异均无统计学意义[43]  

表26岁以下儿童就寝问题和夜醒常见行为治疗技术  

临床问题3:睡前抚触可以改善儿童就寝问题和夜醒吗?  

推荐意见3:睡前抚触可以改善儿童就寝问题和夜醒,推荐作为儿童就寝程序的活动之一(1B)。  

抚触是指用双手对儿童皮肤进行有次序、有技巧的接触来提供良性刺激的护理方法。抚触可作为就寝程序活动的一部分,持续时间一般为$15\\;\\mathrm{min}^{[44]}$ 425 RCT 1 14015\\~20  

共纳人2项RCT研究,其中1项是针对140名15\\~20日龄婴儿的研究[46],另1项为123例3\\~18月龄有睡眠问题婴幼儿的研究[47],结果显示睡前抚触持续1周后婴幼儿的人睡潜伏期缩短[均数差(mean difference, $M D)=-3.85~\\mathrm{min}$ , $95\\%C I$ $-6.04\\mathrm{\\sim}$$-1.67\\;\\mathrm{min}\\,,$ ],就寝问题评分降低 $(M D{=}{-}0.40,95\\%C I$$-0.68\\mathrm{\\sim-0.12})$ ,夜醒次数减少( $\\langle M D{=}{-}0.25$ 次/晚,$95\\%C I-0.46{\\sim}{-}0.03$ 次/晚),但夜醒时间未见缩短$\\mathit{M D}{=}{-}1.9\\ \\mathrm{min}$ n $95\\%C I-4.69{-}0.89\\mathrm{~min})^{\\,!4}$ 6-7。睡前抚触持续2周可进一步缩短婴幼儿的人睡潜伏期$\\langle M D{=}{-}7.25\\ \\mathrm{min}$ , $95\\%C I-9.40{\\sim}-5.09\\ \\mathrm{min})$ ),降低就寝问题评分 $(M D{=}{-}0.58\\,,95\\%C I\\,{-}0.86{\\sim}{-}0.30)$ ,减少夜醒次数 $\\langle M D{=}{-}0.42$ 次/晚, $95\\%C I$ $-0.63\\sim$$-0.20$ 次/晚),但不能显著缩短夜醒时间( $M D{=}$$-1.72\\,\\mathrm{{min}}$ $\\ln,95\\%C I-4.45{\\sim}1.00\\ \\mathrm{min}\\ )^{[46-47]}$  

临床问题4:使用安抚奶嘴是否能够改善儿童就寝问题和夜醒?  

推荐意见4:证据未显示安抚奶嘴能改善儿童就寝问题和夜醒,不推荐使用安抚奶嘴作为改善儿童就寝问题和夜醒的干预方法(2D)。  

安抚奶嘴常常被用来安抚儿童人睡。纳人11783名新生儿的法国出生队列研究发现,1岁时仍使用安抚奶嘴的婴幼儿频繁夜醒问题更多( $O R{=}$1.39,95%CI1.12\\~1.71),但对人睡困难无显著影响( $(O R{=}0.84\\,,95\\%C I\\,0.65{-}1.08)^{\\,[48]}$ 。104名0\\~11月龄儿童的横断面调查显示儿童是否使用安抚奶嘴与夜醒次数( $M D{=}0.28$ 次/晚, $95\\%C I$ $-0.44\\mathrm{\\sim}$1.00次/晚)和夜醒时间( ${\\mathrm{~}}M D{=}0\\ \\mathrm{min}$ , $95\\%C I-16.04\\sim$$16.04\\;\\mathrm{min}\\,\\mathrm{,}$ )均无显著关系[49]  

临床问题5:使用白噪声是否能改善儿童的就寝问题和夜醒?  

推荐意见5:白噪声可能可以缩短儿童的人睡潜伏期,减少夜醒。但需注意不恰当使用白噪声可能损伤儿童听力,不推荐没有就寝问题和夜醒的儿童使用白噪声装置;仅针对有睡眠问题儿童,推荐家长在专业人员的指导下,使用符合安全标准的装置,并尽可能远离儿童,音量调低,使用时间不宜过长,在儿童人睡后应关闭(1C)。  

白噪声是指所有频率具有相同能量密度的随机噪声,通常由听觉刺激装置发出,一般认为可屏蔽环境声音,帮助放松和获得良好睡眠。发出白噪声的听觉刺激装置在国外婴儿中应用较为常见,家长的接受度也比较高[50]。共纳人2篇新生儿就寝=12 95%  2.7\\~53.3 1 RCT $\\scriptstyle{n=40}$ =现,白噪声干预可使入睡潜伏期 ${<}5\\ \\mathrm{min}$ 的人数增加$(O R{=}12\\,,95\\%C I\\ 2.7{\\sim}53.3)^{\\,[51]}$ ;另1项RCT研究( $\\scriptstyle{n=}$12)也发现,白噪声可缩短人睡潜伏期( $M D{=}$-13.2 min, $95\\%C I-21.4\\ –5.04\\ \\mathrm{min}\\ )^{[52]}$ 。3篇关于儿童夜醒问题的病例报告,其中1例15月龄儿童夜醒次数并未减少[53],而9例4月龄至4岁儿童夜醒次[ ]  

婴幼儿处于听觉与语言发育的关键期,因此对于听觉刺激装置是否会影响婴幼儿听力发育也是被关注的焦点问题。根据医院婴儿房和新生儿重症监护室的噪声暴露指南建议,噪声应限制在 $^{1\\mathrm{~h~}}$内平均不超过 $50\\;\\mathrm{dB}\\mathrm{\\left(A\\right)}$ 的水平[56-5]。有实验室研究选择了市场上较常用的14种婴儿睡眠装置,分别将其设置到最大输出音量,在距离装置30、100及 $200~\\mathrm{cm}$ 处测试其产生的噪声强度,发现所有装置在30和 $100\\;\\mathrm{cm}$ 的噪声均超过50dB(A),而在距离 $200~\\mathrm{cm}$ 处,也仅有1种装置产生的噪声低于50dB(A),提示使用婴儿睡眠装置时应尽量远离婴儿,尽量降低音量,并且缩短使用时间[58]  

临床问题6:分床睡能否降低儿童就寝问题和夜醒发生?  

推荐意见6:分床睡可能可以降低儿童就寝问题和夜醒发生,建议采用分床睡降低儿童就寝问题和夜醒发生(2D)。  

同床睡是儿童早期普遍存在的睡眠行为习惯,也是儿童睡眠领域颇具争议的内容之一。按我国育儿习俗,家长与儿童同床睡的比例远高于欧美国家,0\\~35月龄的比例为 $84.8\\%^{[59]}$ ,而学龄前期仍高达 $78.1\\%^{[60]}$ 。美国儿科学会从预防婴儿猝死综合征和安全睡眠环境考虑,建议12月龄前婴儿宜与父母同屋分床睡\"]。我国国家卫生行业标准“0岁\\~5岁儿童睡眠卫生指南”推荐婴儿宜与成人同屋分床睡;幼儿期可逐渐从婴儿床过渡到小床,有条件的家庭儿童可单独一个房间睡[13]  

5篇观察性研究考察睡床方式与儿童就寝问1 564 2 59 62‐632 4 10.1%1564名2月龄婴儿的队列研究跟踪随访至儿童2岁,将儿童划分为4组,即从不同床睡( $\\,10.1\\%$ 人仅早期同床睡( $18.4\\%$ )、后期开始同床睡 $(27.9\\%)$ )和一直分床睡 $(43.6\\%)$ ,结果显示相比一直分床睡儿童,后期开始同床睡和一直同床睡的儿童在2岁时虽然人睡潜伏期无明显增多,但人睡困难风险显著增加( $O R{=}2.06$ , 95%CI 1.37\\~3.0; $O R{=}2.07$ , $95\\%C I$$1.41{\\sim}3.06)^{[65]}$ 。3篇横断面研究考察儿童夜醒时间[59,64,66],其中2篇研究结果显示分床睡与儿童夜59  62‐70 12 463‐64 66‐68 706示分18床睡的儿童夜醒次数较少[ ,1,], 篇队列研究显示婴儿出生时、2月龄、4月龄和6月龄分床睡,18月龄时夜醒次数较少[69],而另1篇队列研究未发现分床睡能减少儿童2岁时的夜醒次数[65]  

临床问题7:辅食添加月龄提前是否可以减少婴幼儿就寝问题和夜醒的发生?  

推荐意见7:适当提前辅食添加的月龄可能可以减少婴幼儿夜醒,但可能增加就寝问题。不推荐把提前添加辅食作为改善婴幼儿就寝问题和夜醒的干预方法(1D)。  

世界卫生组织推荐婴儿纯母乳喂养至6月龄[7] ,不建议早于4月龄添加辅食[72] 。纳入1303名婴儿的RCT研究结果显示,平均4月龄添加固体食物的婴儿比6月龄添加的婴儿夜醒次数更少( $M D{=}9.1\\%\\,,95\\%C I\\,4\\%{\\sim}14\\%)^{[73]}$ 。1项8696名婴儿的队列研究,按照出生到10月龄的喂养行为对婴儿进行轨迹分组,探索早期喂养行为对1岁时睡眠结局的影响,结果显示,与期间未添加组相比,4月龄前和5、7月龄添加并持续组婴儿1岁时人睡困难均出现更多,4月龄前添加并持续组同时夜醒也更加频繁;与4\\~6月龄添加辅食组相比,早期( $<$4月龄)添加辅食组(不含米粉)1岁时人睡困难与夜醒差异均无统计学意义,但是6月龄以上添加辅食的则显示人睡困难更少,夜醒差异均无统计学意义;与未使用增稠配方组相比,早期( ${<}6$ 月龄)使用增稠配方1岁时人睡困难增加,而6月龄时开始使用增稠配方1岁时频繁夜醒减少[74]。另1项1028名儿童的队列研究探索8月龄以内儿童喂养习惯与2\\~6岁的睡眠关系,结果显示无论是添加米粉的年龄还是添加其他辅食的年龄均与2\\~6岁时的睡眠问题无显著关系,同时是否使用增稠配方也与日后的睡眠问题发生无显著关系[75]  

临床问题8:额外摄人营养补充剂可改善儿童就寝问题和夜醒吗?  

推荐意见8:铁剂补充可能可以改善部分铁缺乏导致的儿童就寝问题和夜醒。在未明确营养素缺乏的情况下,不建议额外摄人营养补充剂作为改善儿童就寝问题和夜醒的干预方法(2D)。  

针对铁剂补充治疗儿童就寝问题和夜醒的研究证据有限,仅检索到1篇观察性研究和1篇病例报告。Bruni等[76调查338例6\\~48月龄慢性失眠儿童的临床表现、病史和家族史,采用潜在分组模型将慢性失眠分为3种亚型,其中失眠伴肢体运动较多型主要表现为人睡困难伴躁动不安、夜间肢体运动较多以及频繁夜醒,这部分儿童常有不宁腿综合征、缺铁性贫血、生长痛等家族史和疾病史,提示可能与缺铁相关。另1篇针对1例2岁儿童的病例报告发现,该儿童表现为人睡困难、睡眠中肢体运动较多、就寝抵抗以及白天嗜睡的临床症状,铁蛋白水平低,经口服硫酸亚铁,静脉输注铁剂治疗后儿童能在 $15\\;\\mathrm{min}$ 内人睡,夜间睡眠中肢体运动较多的症状也明显改善[7]。  

2022年的系统综述考察了维生素D与儿童睡眠障碍的关系,纳人了4篇(2篇横断面调查、2篇队列研究)涉及6岁以下儿童的研究[7]:1篇针对39名2\\~17岁(平均年龄6.6岁)儿童的研究发现,维生素D缺乏( $<75\\;\\mathrm{nmol/L}_{\\mathrm{i}}$ )与人睡潜伏期无关[7;1篇 209名婴幼儿的队列研究发现,维生素D水平与2岁儿童的夜醒时间无关]。在6岁以下儿童中的研究多聚焦维生素D与睡眠时间的关系,1项209名2岁婴幼儿的队列研究和2项横断面研究(分别包含39名2\\~17岁和5289名0\\~5岁儿童)的结果均显示,维生素D缺乏( $<50\\ \\mathrm{nmol/L}$ 或 $<$$75\\ \\mathrm{nmol/L}$ )与睡眠时间短有关[7-8]。而脐血维生素  

D水平与儿童睡眠时间的关系结果不一致,1项队列研究发现脐血低维生素D水平与学龄前期持续短睡眠时间相关[\\*2],另1项队列研究则未发现脐血维生素D水平与儿童2岁时的睡眠时间有关系[80]目前尚无干预性研究探索额外摄人维生素D是否可以改善儿童就寝问题和夜醒。此外,也未检索到钙剂摄人与儿童就寝问题和夜醒关系的证据。  

1项RCT研究在600名6\\~11月龄且身长低于同月龄 $1\\,s$ 的婴儿中发现,补充维生素 $\\mathrm{B}_{12}(2\\upmu\\mathrm{g/d)}$不能减少夜醒时间 $\\langle M D{=}0.23~\\mathrm{min}\\$ , $95\\%C I-2.59\\sim$$-3.05\\;\\mathrm{min}\\;\\mathrm{,}$ ),反而会增加睡眠潜伏期( $?M D{=}1.75\\ \\mathrm{min}$ ,$95\\%C I\\ 0.13\\mathrm{\\sim}3.56\\mathrm{\\min})$ )。目前未检索到额外摄入维生素 $\\mathbf{B}_{12}$ 改善儿童就寝问题和夜醒的证据[3]  

临床问题9:增加日间身体活动水平是否能够改善儿童就寝问题和夜醒?  

推荐意见9:证据未显示增加日间身体活动水平能改善儿童的就寝问题和夜醒,不建议把增加日间身体活动水平作为改善儿童就寝问题和夜醒的干预方法(2D)。  

2篇相关性研究观察了日间身体活动水平与儿童就寝问题和夜醒的关系,但结果并不一致。针对141名12月龄婴儿的横断面研究显示,日间身体活动水平较高的婴儿夜醒次数与日间身体活动水平较低的婴儿比较,差异无统计学意义 $M D{=}$0.37次/晚, $95\\%C I-0.11{\\sim}0.86$ 次/晚)[84]。另1项队列研究按照加速度计采集的活动水平在 $P_{s}$ 和 $P_{95}$ 的值将216名儿童分为最活跃和最不活跃两组,结果显示白天最活跃的儿童3岁时夜醒时间比最不活跃的儿童长 $19.2(\\,95\\%C I\\,10.2{\\sim}28.2\\,)\\mathrm{min}\\,,$ 5岁时夜醒时间长 $16.2(95\\%C I\\,10.2{\\sim}16.2)\\mathrm{min}^{[85]}$  

此外,通过活动记录仪监测33\\~71月龄儿童的身体活动水平和睡眠质量的研究发现,日间中高强度身体活动时间较长的儿童夜间的睡眠效率(睡眠时间占在床时间的比例)较低( $\\beta\\!=\\!0.12$ , $95\\%C I$$-0.20{\\sim}{-}0.12\\big)^{[86]}$ ;而来自同一人群的横断面研究从不同强度身体活动时间占比的角度进行分析,发现在结构比中静息活动时间占比增加,而中高强度身体活动时间占比下降 $30\\;\\mathrm{min}$ ,睡眠效率增加 $\\scriptstyle\\left(\\beta={\\frac{1}{2}}$$0.42\\,,95\\%C I\\,0.05{\\sim}0.79)^{!}$ 87]  

目前尚无增加日间身体活动水平改善儿童就寝问题和夜醒的证据,不推荐把增加日间身体活动水平作为改善儿童就寝问题和夜醒的干预方法。但仍然建议按照世界卫生组织发布的“5岁以下儿童身体活动、久坐行为和睡眠指南”,合理安排 $24\\,\\mathrm{{h}}$  

活动,促进身心健康[\\$]  

临床问题10:药物治疗(褪黑素及其他药物)是否可以改善儿童就寝问题和夜醒?  

推荐意见10:褪黑素可减少婴幼儿夜醒,苯海拉明不能改善儿童就寝问题和夜醒。不推荐药物作为改善儿童就寝问题和夜醒的一线方案或单独方案,建议仅在行为治疗等效果不佳或睡眠问题持久、严重时,考虑使用褪黑素作为整体治疗方案的一部分(2C)。  

各国均未批准任何药物用于儿童就寝问题和夜醒的治疗,包括中国国家药品监督管理局、美国食品药品监督管理局、加拿大卫生局。根据现有指南和共识,药物治疗均不作为儿童失眠的一线治疗方案,仅在行为治疗无效或睡眠问题持续、严重时才考虑联合使用[11,89]。根据美国儿科处方的调查报告显示,儿科医生选用药物治疗睡眠问题时,最多选择的是褪黑素、抗组胺药(如苯海拉明)、 $\\upalpha$ 受体激动剂(如可乐定)水合氯醛等19-91]  

褪黑素是由大脑松果体分泌的一种胺类激素,新生儿产生褪黑素的量很少或几乎没有,直到3月1 RCT [ 6]0 褪黑素较多应用于伴有神经发育障碍患儿睡眠问题的治疗中,目前仅检索到1项RCT研究在60名1\\~3岁无发育障碍儿童中使用褪黑素治疗就寝问题和夜醒,结果显示在行为治疗的基础上加用 $0.1~\\mathrm{mg/kg}$ (最大 $1~\\mathrm{mg}$ )褪黑素能够减少夜醒次数 $'M D{=}{-}1.16$ 次/晚,95%CI $-1.93\\sim$$-0.39$ 次/晚)和夜醒时间 $\\mathit{\\check{M D}}{=}{-}10.73\\ \\mathrm{min}$ , $95\\%C I$$-29.04{\\sim}-7.58\\ \\mathrm{min}\\ )^{[94]}$ 30\\~60 min共识推荐,在婴儿期和幼儿期,褪黑素使用剂量一般为 $1{\\sim}3~\\mathrm{mg}$ ,在通常就寝时间前 $30{\\sim}60~\\mathrm{min}$[4]4  

苯海拉明是一种竞争性H1组胺受体阻滞剂。纳人44例6\\~15月龄婴幼儿的RCT研究显示,实验组在睡前 $30\\;\\mathrm{min}$ 给予剂量为每千克体重 $1~\\mathrm{mg}$ 的苯海拉明7d,与安慰剂组相比,未显著缩短人睡潜伏期 $\\langle M D{=}4.2\\ \\mathrm{min}$ , $95\\%C I-4.7{\\sim}13.0\\mathrm{\\min}\\,)$ ),也并未减少夜醒次数( ${M D}\\mathrm{=}0.2$ 次/晚, $95\\%C I$ $-0.65\\mathrm{\\sim}$1.00次/晚)[95]  

可乐定是一种传统的降血压药物,为 $\\upalpha2$ 受体激动剂,可同时对中枢神经系统产生抑制作用。美国1项关于222名儿科医生的调查研究发现,可乐定在0\\~2岁和3\\~5岁睡眠问题儿童中使用的比例分别为 $2.3\\%$ 和 $13.6\\%^{[90]}$ 。但目前尚无研究验证可乐定对儿童就寝问题和夜醒的治疗作用。  

此外,美国对222名儿科医生的调查研究还发现,水合氯醛等镇静催眠药物在0\\~2岁和3\\~5岁睡眠问题儿童中使用的比例分别为 $8.0\\%$ 和 $11.4\\%^{[90]}$同样,目前尚无研究验证水合氯醛对儿童就寝问题和夜醒的治疗证据。  

总体而言,药物对6岁以下儿童就寝问题和夜醒的治疗效果、安全性及不良反应等尚缺乏高质量RCT研究,在使用药物改善儿童就寝问题和夜醒时,应当在临床药师指导下,按最低有效剂量、最短时间原则谨慎使用,并密切监测不良反应[!1,9%] O

"""
response = """
// 节点更新
MERGE (n:Disease {name: '就寝问题'})
SET 
    n.description = coalesce(n.description, '6岁以下儿童失眠的主要表现，可对儿童生长发育和家长身心健康造成不良影响。');

MERGE (n:Disease {name: '夜醒'})
SET 
    n.description = coalesce(n.description, '6岁以下儿童失眠的主要表现，常见主诉之一。');

MERGE (n:Symptom {name: '人睡潜伏期'})
SET 
    n.description = coalesce(n.description, '从家长准备安顿儿童睡觉到儿童真正人睡的时间，一般认为大于20分钟具有临床意义。');

MERGE (n:Symptom {name: '夜间醒来'})
SET 
    n.description = coalesce(n.description, '儿童频繁夜醒的问题，通常表现为每晚2次以上的夜醒，且每次醒来大于5分钟。');

MERGE (n:Treatment {name: '行为治疗'})
SET 
    n.description = coalesce(n.description, '通过标准消退法、渐进消退法等方式改善儿童就寝问题和夜醒。');

MERGE (n:Treatment {name: '早期睡眠卫生习惯指导'})
SET 
    n.description = coalesce(n.description, '对儿童就寝问题和夜醒的改善效果显著，建议作为干预方法。');

MERGE (n:Treatment {name: '药物治疗'})
SET 
    n.description = coalesce(n.description, '包括褪黑素，短期内可减少婴幼儿夜醒，但不推荐作为一线方案。');

MERGE (n:Complication {name: '慢性失眠障碍'})
SET 
    n.description = coalesce(n.description, '如果相关睡眠问题每周出现3次并持续3个月，为慢性失眠障碍。');

// 关系更新
MATCH (from) WHERE from.name = '就寝问题'
MATCH (to) WHERE to.name = '行为治疗'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.85),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '一线治疗');

MATCH (from) WHERE from.name = '就寝问题'
MATCH (to) WHERE to.name = '早期睡眠卫生习惯指导'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.75),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '辅助手段');

MATCH (from) WHERE from.name = '就寝问题'
MATCH (to) WHERE to.name = '慢性失眠障碍'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 0.6),
    r.timeframe = coalesce(r.timeframe, '长期');

MATCH (from) WHERE from.name = '就寝问题'
MATCH (to) WHERE to.name = '人睡潜伏期'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '夜醒'
MATCH (to) WHERE to.name = '夜间醒来'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '夜醒'
MATCH (to) WHERE to.name = '行为治疗'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.8),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '一线治疗');

MATCH (from) WHERE from.name = '夜醒'
MATCH (to) WHERE to.name = '早期睡眠卫生习惯指导'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.7),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '辅助手段');

MATCH (from) WHERE from.name = '夜醒'
MATCH (to) WHERE to.name = '药物治疗'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.6),
    r.priority = coalesce(r.priority, '低'),
    r.stage = coalesce(r.stage, '非首选');

MATCH (from) WHERE from.name = '就寝问题'
MATCH (to) WHERE to.name = '夜醒'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '必需'),
    r.mandatory = coalesce(r.mandatory, 'true');

"""
