[metadata]
file_name = "儿童中枢性睡眠呼吸暂停56例临床分析.md"
processed_at = "2024-12-19 00:12:18"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-19 00:08:59"
message = """

[隶属文件名]
儿童中枢性睡眠呼吸暂停56例临床分析.md
[隶属文件分块名]
儿童中枢性睡眠呼吸暂停56例临床分析/001-完整文档.md
[文本块]
# 儿童中枢性睡眠呼吸暂停56例临床分析

# 郑莉1 吴云肖2 许志飞3
1国家儿童医学中心,首都医科大学附属北京儿童医院耳鼻咽喉头颈外科,北京100045;2国家儿童医学中心,首都医科大学附属北京儿童医院儿童耳鼻咽喉头颈外科疾病北京市重点实验室,北京100045;3国家儿童医学中心,首都医科大学附属北京儿童医院呼吸科,北京100045  

通信作者:许志飞,Email:zhifeix $@$ aliyun.com  

【摘要】 目的 探讨儿童中枢型呼吸暂停(CA)(按呼吸事件类型分类)的临床特点及疾病构成,以提高临床对儿童睡眠呼吸疾病的认识。方法 横断面研究。统计2019年3月至2022年3月在首都医科大学附属儿童医院睡眠监测中心完成整夜多导睡眠监测(PSG)的患儿共计5708例,按照中枢型呼吸暂停指数(CAI) $\\geqslant$5次/h且CA和/或中枢型低通气数量 $>$ 呼吸暂停低通气数量 $50\\%$ 的标准,共有56例患儿 $(1.0\\%$ )符合此标准,回顾性分析56例以CA为主要表现的PSG及临床资料,总结分析疾病构成和呼吸特点。采用多元线性回归分析中枢型呼吸事件的相关因素。结果 中枢性睡眠呼吸暂停(CSA)同时符合阻塞性睡眠呼吸暂停(OSA)有37例患儿,其中男16例、女21例。CAI与阻塞型呼吸暂停低通气指数呈正相关 $r=0.\\,673$ , $P<0.\\,001$ ),与体重指数、年龄无相关性。在56例CSA患儿中, $\\mathrm{CAI}>20$ 次/h有4例患儿,其中Chiari畸形1例,脑干肿瘤2例,遗传代谢病1例。结论 CA相对于阻塞型呼吸暂停发生率更低。CSA患儿多合并OSA,阻塞的严重程度是影响CAI的主要因素。若 $\\mathrm{CAI}>20$ 次/h,应高度重视,需全面评估病史,完善相关影像学等检查,排除内外科基础疾病导致的CSA。  

【关键词】 儿童;中枢性睡眠呼吸暂停;阻塞性睡眠呼吸暂停;多导睡眠监测  

睡眠呼吸障碍(sleepbreathingdisorders,SBD)是指睡眠期间出现呼吸异常的一类疾病,主要分为阻塞性睡眠呼吸暂停(obstructivesleepapnea,OSA)、中枢性睡眠呼吸暂停(centralsleepapnea,CSA)、睡眠相关肺泡低通气障碍和睡眠相关低氧血症[1]。在儿科人群中,以OSA最为常见,是指睡眠过程中频繁发生部分或全部上气道阻塞,表现为睡眠时张口呼吸、打鼾、呼吸暂停,腺样体扁桃体肥大是OSA的最常见病因[2]。相比OSA而言,CSA在睡眠中心并不常见,只占所有SBD的 $10\\%$ 以下[3],是以呼吸驱动缺乏或异常导致的通气功能障碍为特征[4]。由于CSA的发病率远低于OSA,且临床症状不显著,容易被忽略,但其实际临床危险度更高。本研究探讨以中枢型呼吸暂停(centralapnea,CA)(按呼吸事件类型分类)为主要表现患儿的临床特点及疾病构成,分析CSA的病因,以提高临床医师对儿童睡眠呼吸疾病的认识。
# 1 资料与方法
1.1 研究对象 横断面研究。以2019年3月至2022年3月在首都医科大学附属儿童医院睡眠监测中心就诊的患儿为研究对象。纳入标准:(1)年龄 $1\\sim16$ 岁;(2)多导睡眠监测(polysomnography,PSG)结果符合CSA诊断标准[1]。排除标准:(1)睡眠监测时间 $<7~\\mathrm{h}$ ,睡眠有效率 $<\\!60\\%$ ;(2)近2周有上呼吸道感染史。本研究通过医院医学伦理委员会批准(批准文号:2020K93),患儿监护人及患儿均签署知情同意书。 MEDI
# 1.2 方法
1.2.1 PSG 采用澳大利亚CompumedicsESeries、Grael系列、美国飞利浦Alice5、Alice6系列、德国SOMNOscreenplus系列睡眠监测仪对研究对象进行整夜PSG。所有研究对象在自然状态下入睡,入睡前禁止服用咖啡、茶、可乐及镇静催眠药物等,有效监测时间均超过 $7\\textrm{h}$ 。脑电电极安装按照国际1020标准。PSG监测的导联:脑电(F3/M2,F4/M1,C3/M2,C4/M1,O1M2,O2/M1)、眼电、下颌肌电、心电、胸部和腹部呼吸运动、血氧饱和度、呼吸鼻气流、鼾声、体位等。睡眠技师依据美国睡眠医学会制定的标准[5],对PSG进行人工分析及校对。  

1.2.2 诊断标准 依据儿童OSA诊断标准[2],阻塞型呼吸暂停低通气指数(obstructiveapneahypopneaindex,OAHI) $>1$ 次/h可以诊断 $\\mathrm{OSA}$ 。依据CSA诊断标准[1],中枢型呼吸暂停指数(centralapneaindex, $\\mathrm{CAI})\\geqslant$5次/h且CA和/或中枢型低通气数量 $>$ 呼吸暂停低通气数量 $50\\%$ 诊断为 $\\mathrm{CSA}$ 。  

1.3 统计学处理 采用JMP11.0软件进行分析,人口学信息均符合偏态分布,采用 $M(\\,Q_{1}\\,,Q_{3}\\,)$ )描述。CAI严重程度相关因素分析采用多元线性回归分析。 $P<0.\\,05$ 为差  

异有统计学意义。
# 2 结果
2.1 一般情况 回顾性分析5708例患儿PSG指标,有56例患儿符合CSA诊断 $(1.\\,0\\%\\,)$ ),其中合并OSA37例 $(66.1\\%$ ),男16例、女21例,年龄5.1(4.4,9.5)岁;体重指数(bodymassindex,BMI)17.6(14.8,22.1) $\\mathrm{kg}/\\mathrm{m}^{2}$ 。按照 $\\mathrm{CAI}>20\\$ 次/h为标准时,有4例患儿符合,其中Chiari畸形1例,脑干肿瘤2例,遗传代谢病1例。  

2.2 相关性分析 将37例CSA合并OSA患儿的CAI与相关风险因素进行多元线性回归分析,结果发现,CA与BMI、年龄无相关性,与OAHI呈正相关 $r=0.\\,673$ ,$P<\\!0.001$ ),CAI与OAHI的散点图见图1。  

注:CSA:中枢性睡眠呼吸暂停;OSA:阻塞性睡眠呼吸暂停;CAI:中枢 型呼吸暂停指数;OAHI:阻塞型呼吸暂停低通气指数 CSA:centralsleep apnea;OSA:obstructivesleepapnea;CAI:centralapneaindex;OAHI:obstruc tiveapneahypopneaindex  

图 $^{1}$ CSA合并OSA患儿CAI与OAHI相关性分析 Figure1 CorrelationanalysisofCAIandOAHIinCSAchildrenwithOSA  

2.3 典型病例 病例1,女,2岁7个月,因“长出气2周”于2021年3月11日就诊于呼吸科。患儿表现为白天运动后长出气,夜间刚入睡及晨起时叹气样呼吸,熟睡后呼吸规律,但有时出气粗,不打鼾,时轻时重。查体未见明显异常。心脏彩超、脑血管超声、肺CT、头颅CT均未见异常。PSG相关数据(图2、3):(1)睡眠结构:总睡眠时间 $446\\,\\mathrm{\\min}$ ,N1期睡眠 $37\\%$ ,N2期睡眠 $28.\\,8\\%$ ,N3期睡眠 $13.8\\%$ ,R期睡眠 $20.4\\%$ ,睡眠潜伏期 $8\\,\\mathrm{\\min}$ ,R睡眠潜伏期 $98.\\,5\\,\\mathrm{\\min}$ ,睡眠效率 $75.9\\%$ ,入睡后清醒时间 $134\\ \\mathrm{min}$ 。入睡后无鼾声,无张口呼吸,提示睡眠结构紊乱;(2)呼吸事件:OAHI0次/h,CAI111次/h,CA最长时间15s,平均时间10s,符合CSA;(3)血氧情况: ${\\geqslant}3\\%$ 氧减指数106.5次/h,平均血氧 $97\\%$ ,最低血氧 $84\\%$ , $<\\!90\\%$ 血氧时间占睡眠时间百分比 $0.\\,2\\%$ ;(4)觉醒指数:呼吸事件相关6.1次/h,肢体运动相关0次/h,自发觉醒3.6次/h;儿童OSA疾病特异性生活质量问卷(OSA18):55分,轻度。实验室检查:血气分析(静脉血)$\\mathrm{pH}\\,7.35$ ,二氧化碳(carbondioxide, $\\mathrm{CO}_{2}$ )分压 $39\\,\\mathrm{\\mmHg}$( $\\mathrm{1\\mmHg=0.\\,133\\kPa}_{,}$ ),氧分压 $40\\ \\mathrm{mmHg}$ ,实际碳酸氢盐$21.\\,5\\;\\mathrm{\\mmol/L}$ ,标准碳酸氢盐 $21.~3~\\mathrm{\\mmol/L}$ ,剩余碱$-3.8\\ \\mathrm{mmol/L}$ ,血氧饱和度 $72\\%$ 。颅脑磁共振成像(magneticresonanceimaging,MRI)(图4):小脑扁桃体超过枕骨大孔水平约 $1.\\,6\\,\\,\\mathrm{cm}$ ,延髓及上段颈髓略受压,脑实质内未见异常信号。诊断为Chiari畸形I型,患儿采取保守治疗,定期复查,随访。  

图2 例1中枢性睡眠呼吸暂停综合征患儿多导睡眠监测趋势图图3 例1中枢性睡眠呼吸暂停综合征患儿多导睡眠监测显示的中枢型呼吸暂停  

Figure3 Centralsleepapneaofpolysomnographyofcase1withcentralsleep apnea  

图4 例1中枢性睡眠呼吸暂停综合征患儿颅脑磁共振成像(箭头所指为小脑扁桃体下疝)  

Figure4 Cranialmagneticresonanceimagingofcase1withcentralsleepap nea(thearrowindicatesinferiortonsillarhernia)  

病例2,男,5岁10个月,因“睡眠呼吸暂停2年”于2021年2月25日收入院。入院前2年开始出现睡眠中呼吸暂停,轻度打鼾,于当地医院行腺样体切除术;但术后仍有夜间呼吸暂停,近2个月症状进行性加重,入睡后有明显的口唇发绀,无明显鼾声。近0.5年来有脾气暴躁,无呕吐、头疼、头晕、晕厥等症状。既往史:患儿3岁前生长发育正常,3岁后食欲旺盛,体重及身高增长均快于同龄儿。查体:体型肥胖,身高 $131~\\mathrm{cm}$ ,体重 $55~\\mathrm{kg}$ ,BM $32\\ \\mathrm{kg/m}^{2}$ ,神志清楚,精神反应好,清醒时呼吸规律,呼吸频率 $15\\sim25$ 次/min,入睡后呼吸5~10次 $\\overrightarrow{\\mathrm{min}}$ ,口唇及甲床发绀,但无明显鼾声,心脏及肺部查体未见明显异常,指鼻试验欠稳准,轮替试验欠灵活,闭目难立征阳性,余神经系统查体未见明显异常。心脏彩超:肺动脉高压(轻中度)右侧房室饱满。实验室检查:血常规及生化均大致正常。血气分析(静脉血) $\\mathrm{pH}~7.35\\$ , $\\mathrm{CO}_{2}$ 分压$60~\\mathrm{mmHg}$ ,氧分压 $54~\\mathrm{mmHg}$ ,血氧饱和度 $86\\%$ 。PSG相关数据(图5、6):入睡后无鼾声,OAHI0.5次/h,CA197.4次/h,最低血氧 $65\\%$ ,平均经皮二氧化碳分压(transcutaneouspartialpressureofcarbondioxide, $\\mathrm{TCPCO}_{2}$ )$82.\\,5~\\mathrm{mmHg}$ ,快眼球运动期(rapideyemovement,REM)$\\mathrm{TCPCO}_{2}$ 升高明显,平均 $94.\\,4\\ \\mathrm{mmHg}$ 。头颅MRI(图7)示延髓脑干及颈髓背侧占位性病变,病变向后突出推挤四脑室及小脑结构,幕上脑室增宽。诊断为延髓肿瘤、CSA、肥胖症。患儿于外院行肿瘤部分切除术,术后病理为多形性黄色星形细胞瘤。术后患儿偶有夜间呼吸暂停,症状有所改善,仍在长期随访中。  

图5 例2中枢性睡眠呼吸暂停综合征患儿多导睡眠监测趋势图图6 例2中枢性睡眠呼吸暂停综合征患儿多导睡眠监测显示的中枢型呼吸暂停  

Figure6 Centralsleepapneaofpolysomnographyofcase2withcentralsleep apnea
# 3 讨论
与成人不同,在儿童中CSA的患病率低,但睡眠中CA事件时常可见。根据美国睡眠医学会2.6版要求[5],满足下列所有标准时判读为CA:(1)口鼻温度传感器或替代呼吸暂停传感器监测信号较事件前基线下降 ${\\tt{290\\%}}$ 。(2)整个事件期间没有相关的呼吸努力,并且存在下列之一: $\\textcircled{\\scriptsize{1}}$ 事件持续 ${\\geqslant}20$ s; $\\circledcirc$ 事件持续时间至少为基线呼吸的2个呼吸周期,同时伴相关觉醒或 $\\geqslant$$3\\%$ 氧饱和度下降; $\\textcircled{3}$ 事件持续时间至少为2个呼吸周期,且呼吸事件相关心率减低至 $<50$ 次/min持续至少$5\\,\\mathrm{\\textrm{s}}$ 或心率减低至 $<60$ 次/min持续至少 $15\\,\\mathrm{~s~}$ (仅用于1岁以内婴儿)。OSA发生时主要表现为因气道阻塞而出现持续的呼吸努力,而CA不同,事件持续期间不存在呼吸努力,因此呼吸努力的监测对评估CA事件是必不可少的。食道压测量是反映呼吸中枢驱动、区分呼吸暂停类型的金标准[6],由于为侵入性操作,儿童配合度差,目前临床多采用呼吸感应体积描记技术(respiratorinductanceplethysmography,RIP)测量。  

健康儿童在思睡期、哭泣后及REM睡眠易出现CA事件,但通常被认为是生理性的。许志飞等[7]研究发现,在健康儿童中学龄前儿童CAI为 $0.\\,6(0.\\,1,1.2)$ )次/h,学龄期儿童CAI为0.1(0.1,0.4)次/h,CAI与年龄呈负相关。随着年龄增长,呼吸中枢发育逐渐成熟,中枢型呼吸事件随之减少。这一研究结果与MontgomeryDowns等[8]研究结果相似,对健康儿童进行年龄段划分,其中3~5岁儿童 $\\mathrm{CAI}(0.\\,8\\pm0.\\,7\\,)$ )次 $/\\mathrm{h}\\,,6\\sim7$ 岁儿童$\\left(0.5\\pm0.5\\right)$ )次/h。因此,在对PSG结果进行分析时,判断CAI是否异常应根据年龄采用不同界限值。参考第97.5百分位值,建议学龄前儿童正常CAI高限约为4.0次/h,学龄期儿童正常CAI高限约为1.5次/h[7]。  

CSA可与其他睡眠障碍共存,尤其是OSA。本研究结果显示,56例CSA患儿中合并OSA有37例患儿$(66.1\\%$ ),将CAI与BMI、年龄、OAHI进行相关性分析,结果发现,CAI与OAHI呈正相关,CA事件随着阻塞程度的加重而增加。DelRíoCamacho等[9]回顾性分析了1279例 $1\\sim14$ 岁无神经系统疾病的儿童夜间PSG数据,发现OSA组的平均CAI(2.1次/h)高于非OSA(1.2次/h),且OSA患儿行腺样体扁桃体切除术后CAI有所改善。尹国平等[10]对62例OSA患儿手术前后PSG数据分析发现,术前有18例 $(29.0\\%$ )患儿以CA为主,术后1~3个月复查,以CA为主的OSA患儿,术后CAI较术前降低,术前CAI中位数 $2.68\\;\\%/\\mathrm{h}$ ,术后CAI中位数1.6次/h,有显著改善 $P<0.\\,001$ ),说明腺样体扁桃体切除术对于改善CA有着积极作用。由此推测,儿童CA的发生尽管与儿童期年龄相关的呼吸中枢发育不完善存在相关性,但腺样体扁桃体肥大所引起的气道阻塞,增加了呼吸中枢的不稳定性,加重了CSA的严重程度。  

本研究结果发现,56例CSA儿童中,52例$(92.9\\%$ )CAI在20次/h以下,与气道阻塞存在重叠的病理生理机制。 $\\mathrm{CAI}>20\\$ 次/h有4例,均是出现了中枢神经系统病变,包括Chiari畸形1例,脑干肿瘤2例及遗传代谢病疾病1例。本研究报道的2例病例,均是在完善睡眠监测时,发现呼吸节律异常、间歇低氧、 $\\mathrm{CO}_{2}$ 潴留等表现,建议临床完善中枢神经系统查体及影像检查,查找引起CA的原因,最终明确诊断。  

呼吸中枢位于延髓,正常情况下延髓呼吸中枢接受化学感受器、大脑皮质的随意控制信号和网状激活系统的行为输入信号,控制呼吸节律。当病变累及延髓时,脑干通气控制中枢功能受损,无法发起呼吸努力,出现CA事件。日间由于皮质信号和行为信号的调控,可以没有明显的呼吸节律问题,在夜间入睡以后呼吸中枢对各种不同刺激的反应性减低,出现低氧,尤其是 $\\mathrm{CO}_{2}$ 水平改变引起的呼吸反馈调控不稳定,加重了睡眠呼吸紊乱程度[11]。覃丽霞等[12]对441例1岁以上儿童PSG进行回顾性研究发现,18例 $(4.1\\%)$ )儿童的 $\\mathrm{CAI}>5$ 次/h,神经外科疾病,特别是Chiari畸形是最常见的CSA原因。检索国内外2000年至2020年报道的延髓脑干肿瘤合并SBD的文献,共8篇,均为个案报道。CSA是延髓脑干肿瘤引起SBD的主要类型[1320]。CSA相比于OSA,临床症状不显著,患儿多是在夜间入睡后出现异常,容易被忽略,但其实际临床危险度更高[21]。在睡眠监测时发现以CA事件为主时,要密切关注生命体征和$\\mathrm{CO}_{2}$ 变化,病情严重的,随时做好抢救准备。如覃丽霞等[12]报道患者出现睡眠昏迷和呼吸心跳骤停表现,如果不及时发现诊治容易出现猝死。  

综上所述,PSG可以明确SBD的类型,对于SBD疾病的诊治至关重要。CSA多合并OSA,CA随阻塞程度的加重而增加。若 $\\mathrm{CAI}>20\\$ 次/h,应高度重视,密切关注睡眠时呼吸、心率、 $\\mathrm{CO}_{2}$ 等指标变化,需全面评估病史,完善头颅MRI、心脏彩超、血气分析等相关检查,排除颅内肿瘤、畸形等内外科疾病导致的 $\\mathrm{CSA}$ 。  

利益冲突 所有作者均声明不存在利益冲突作者贡献声明 郑莉:文章撰写、统计分析;吴云肖:提供研究思路、写作指导、分析解释数据;许志飞:设计方案、对文章的知识性内容作批评性审阅

"""
response = """
// 节点更新
MERGE (n:Disease {name: '中枢性睡眠呼吸暂停(CSA)'})
SET 
    n.description = coalesce(n.description, '以呼吸驱动缺乏或异常导致的通气功能障碍为特征，相对于阻塞性睡眠呼吸暂停(OSA)发生率更低'),
    n.category = coalesce(n.category, '睡眠呼吸障碍'),
    n.severity = coalesce(n.severity, '高');

MERGE (n:Disease {name: '阻塞性睡眠呼吸暂停(OSA)'})
SET 
    n.description = coalesce(n.description, '在睡眠过程中频繁发生部分或全部上气道阻塞'),
    n.category = coalesce(n.category, '睡眠呼吸障碍'),
    n.severity = coalesce(n.severity, '中');

// 关系更新
MATCH (from) WHERE from.name = '中枢性睡眠呼吸暂停(CSA)'
MATCH (to) WHERE to.name = '阻塞性睡眠呼吸暂停(OSA)'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

"""
