[metadata]
file_name = "基层医疗机构失眠症诊断和治疗中国专家共识.md"
processed_at = "2024-12-19 00:12:18"
total_pairs = 2

[[message_pairs]]
timestamp = "2024-12-19 00:08:14"
message = """

[隶属文件名]
基层医疗机构失眠症诊断和治疗中国专家共识.md
[隶属文件分块名]
基层医疗机构失眠症诊断和治疗中国专家共识/002-三物理治疗.md
[文本块]
# (三)物理治疗
物理治疗具有使用方便,不易成瘾、不良反应小等优点。失眠的常用物理治疗包括光照疗法、重复经颅磁刺激、经颅电刺激、生物反馈疗法等;此外,迷走神经刺激术、虚拟现实(VR)、听觉刺激等新兴技术也日益得到关注。  

1.光照治疗:光线是调节昼夜节律的重要因素。光照疗法可改善失眠患者的日间思睡,减少睡眠片段化[],光照治疗对于各种睡眠紊乱普遍有效,适用人群广泛(2A)。推荐晨间光照,单位$2\\ 500{\\sim}10\\ 000\\ \\mathrm{lux}$ ,每天光照时间 $30{\\sim}45\\ \\mathrm{min}$  

2.重复经颅磁刺激(repetitive transcranialmagnetic stimulation,rTMS):低频 $\\mathrm{rTMS}\\left(\\,\\leqslant\\!1~\\mathrm{Hz}\\,\\right)$ 通过降低失眠患者的皮质异常兴奋性、诱导慢波睡眠、增加睡眠深度,同时影响松果体褪黑素的合成和分泌,以维持正常睡眠觉醒周期和改善睡眠质量。rTMS对失眠的疗效确切,并且可以缓解焦虑和抑郁症状7},疗效持续时间与疗程有关(2B)。  

3.经颅电刺激(transcranialelectricalstimulation,TES):TES通过向头皮施加低强度电流来调节大脑活动,包括经颅交流电刺激(tACS)和经颅直流电刺激(tDCS)。tACS对慢性失眠患者有显著改善作用[3,tDCS在失眠患者中应用较少,暂不推荐。  

4.生物反馈疗法:生物反馈旨在减少条件唤醒,尤其是躯体、认知或皮质的过度唤醒,可以减少失眠者的入睡时间和觉醒次数[74],可以作为CBTI的替代疗法或辅助治疗75。  

5.其他:迷走神经刺激、VR、听觉刺激等治疗方法尚缺乏高质量的临床证据支持,暂不推荐。  

推荐意见9:光照疗法对于各种睡眠紊乱普遍有效(2A),rTMS可以缓解失眠相关的焦虑和抑郁症状(2B),tACS对慢性失眠患者有改善作用(2B),生物反馈疗法可减少失眠者的入睡时间和觉醒次数(2B)。  

(四)药物治疗  

药物治疗主要是指镇静催眠药物,治疗中需要明确失眠症的病因以针对性治疗,还应避免或减少相关的负面效应。基层医疗机构需要遵循以下原则:  

1.治疗时机:无法开展CBTI或不愿意接受CBTI,以及CBTI疗效不满意时,可以与患者共同决策,选择药物治疗[3,30];对于失眠症状严重且紧急的患者,则宜尽早应用。  

2.个体化:考虑患者的症状学特点,如人睡困难、睡眠维持困难或早醒,关注共病的躯体疾病、精神障碍、睡眠障碍、药物和(或)成瘾性物质使用史、药物相互作用,以及患者的自我选择和药物可获取性等[3,66]  

3.按需和间歇给药:以最低剂量开始治疗,逐步向上滴定以达到治疗效果[3]。“按需\"的具体决策标准:预期人睡困难时,上床前 $5{\\sim}10\\ \\mathrm{min}$ 服用;上床 $30\\;\\mathrm{min}$ 后仍不能人睡时,立即服用;比通常起床时间提前 $^{\\geqslant5}\\mathrm{~h~}$ 醒来,且无法再次入睡时,可以服用短半衰期的药物;根据次日的日间活动需求(如重要事务),睡前服用。“间歇”是指非连续性每晚用药,具体频次尚无定论,推荐频率为3\\~5晚/周[3.66]。  

4.药物选择:催眠作用的药物种类繁多。苯二氮草类受体激动剂(benzodiazepinereceptoragonists,BZRA)的临床应用最为广泛,包括非苯二氮草类药物(如唑吡坦、右佐匹克隆、佐匹克隆、扎来普隆)苯二氮草类药物(如劳拉西泮、阿普唑仑、艾司唑仑) $\\upgamma\\cdot$ -氨基丁酸A型(GABAA)受体的部分正向别构调节剂(地达西尼)等。双重食欲素受体拮抗剂[dual orexin receptor antagonists(DORA),如莱博雷生、达利雷生、苏沃雷生]是新型镇静催眠DORA2A 2 BZRA选短、中效的BZRA或褪黑素受体激动剂(2A),或者DORA(2A);(2)其他的BZRA或褪黑素受体激动剂(2A);(3)具有镇静催眠作用的抗抑郁药物(2B),尤其适用于伴随焦虑和抑郁症状的失眠患者;(4)联合BZRA和具有镇静作用的抗抑郁剂(2B);(5)具有镇静作用的抗精神病药(2C)不作为首选药物使用,仅适用于某些特殊情况和人群;(6)非处方药抗组胺药物、普通褪黑素以及草提取物等非处方药(2D)。  

5.疗程:疗程根据失眠障碍病程、严重程度及对药物的治疗反应决定,一般不超过4周;如果连续治疗超过4周时需重新全面评估。药物疗效与安全性欠佳者,建议更换治疗药物,睡眠明显改善者,建议适时采取降低剂量或间歇给药3。  

6.终止治疗:患者的失眠改善并感觉可以控制睡眠后,可考虑逐渐减量、停药[76,CBTI有助于此过程。大剂量、多药联用或长期连续药物治疗的患者应避免突然停药,以避免失眠反跳、癫痫发作和其他的严重精神症状[66.,79]  

7.特殊人群:儿童、孕妇、哺乳期妇女、肝肾功能损害、重度睡眠呼吸暂停综合征、重症肌无力患者慎用镇静催眠药物治疗(2D)[3。  

推荐意见10:镇静催眠药物治疗应遵循个体化、按需、间歇和最低有效剂量给药的原则,建议首选短、中效的BZRA或褪黑素受体激动剂或者DORA(2A),尽可能在CBTI基础上使用镇静催眠药物(2A)。  

推荐意见11:镇静催眠药物使用一般不超过4周,失眠改善并感觉可以控制睡眠后,可考虑逐渐减量、停药;连续治疗超过4周时,需重新全面评估。(专家共识)  

(五)中医药治疗  

中医称失眠症为“不寐病”,在辨证论治的基础上,进行证治分类[80-8],采用中医药治疗,以及针刺、穴位按摩、艾灸治疗、耳穴疗法、功法治疗、中医心理疗法等非药物疗法。  

1.失眠症的辨证论治:(1)实证: $\\textcircled{1}$ 肝气郁结 证:治法:疏肝解郁,行气止痛。推荐方药:柴胡疏 肝散或逍遥散加减;推荐中成药:舒肝解郁胶囊[82] 舒眠胶囊[83]; $\\textcircled{2}$ 肝郁化火证:治法:疏肝解郁,清热 化火。推荐方药:龙胆泻肝汤加减; $\\textcircled{3}$ 胃气失和证: 治法:行气导滞,和胃降逆。推荐方药:保和丸或半 夏林米汤加减; $\\textcircled{4}$ 痰热内扰证:治法:化痰清热,和 中安神。推荐方药:黄连温胆汤加减; $\\circled{5}$ 瘀血内阻 证:治法:活血化瘀,通经活络。推荐方药:血府逐 瘀汤加减; $\\circled{6}$ 心火炽盛证:治法:清心泻火,养血安 神。推荐方药:导赤汤合交泰丸或朱砂安神丸加 减。(2)虚证: $\\textcircled{\\scriptsize{1}}$ 心脾两虚证:治法:益气健脾,养心 安神。推荐方药:归脾汤加减。推荐中成药:枣仁 安神胶囊[84-85]; $\\textcircled{2}$ 心胆气虚证:治法:益气养心,镇 静安神。推荐方药:安神定志丸合酸枣仁汤加 减; $\\textcircled{3}$ 心肾不交证:治法:滋阴降火,交通心肾。推 荐方药:六味地黄丸合交泰丸或天王补心丹加减; 推荐中成药:乌灵胶囊[86-87]、百乐眠胶囊[88]  

2.中药单味药治疗:(1)药目:酸枣仁[8990]远志[1]、五味子[92]、茯神[9]、草[94]、落花生枝叶[5]、柏子仁%等。(2)服用方法:单味药可泡水作代茶饮。  

3.失眠症的非药物手段治疗:(1)采用相应穴位可进行传统针刺、电针、温针、穴位按摩、艾灸治[ ] 101关、神庭、安眠、太溪[\"]。操作要领参考《针灸技术操作规范》。(2)耳穴治疗:取穴:神门、心、肝、皮质下、交感[8]。每日自行按压3\\~5次,每次每穴 $1\\sim$$2~\\mathrm{min}$ 。每晚睡前按1次,约 $5~\\mathrm{min}$ ,双耳交替。按压以耳廓微红、微热为度,不宜过度重按,切记揉搓。每周换耳穴贴2次,每次双耳各2贴,持续4周。(3)功法治疗: $\\textcircled{\\scriptsize{1}}$ 八段锦:操作要领参考国家体育总局推广的《健身气功·八段锦》10]; $\\textcircled{2}$ 太极拳:操作要领参考“六式太极拳\"[13]。建议治疗时间:每周3\\~4次,每次半小时,至少持续12周; $\\textcircled{3}$ 中医心理疗法:结合当代人的心理特征,重视精神调摄,倡导天人相应,五志有节,起居有常。  

推荐意见12:中医治疗在辨证论治的基础上,对失眠症进行分类诊治,应用中药(2C)、中成药(2C)、针灸配合电针、温针、艾灸(2A)、中医心理疗法(2D)等非药物疗法,具有一定的应用场景。  

推荐意见13:单味药代茶饮(2C)、穴位按摩(2D)、耳穴疗法(2C),八段锦(2D)、太极拳(2C)等功法锻炼的方法简便,便于患者居家保健。  

推荐意见14:中医治疗可以单独应用,也可应用于镇静催眠药物的减量、停药过程。(专家共识)
# 第八部分失眠症的基层管理
建立基层失眠症体系管理,需要患者及其家庭成员/照料者、基层医疗机构人员、专科医师的共同参与。基层医疗机构具有特定的社区基础,在开展失眠防治、分级诊疗和建立健康网络方面具有重要作用(图1)。  

一立足筛查,数据建档(一)失眠症筛查模式  

ISI可作为基层人群定期筛查量表,并在筛查基础上应用睡眠日记、PSQI、ESS、MEQ、STOP-BANG、RLSQ等量表,以及家用睡眠监测设备、活动记录仪、非侵人式远程监控、额贴脑电、手环等设备进行筛查和评估[104]  

(二)建立电子健康档案  

基层医疗机构通过建立电子健康档案,充分运用互联网等信息网络技术,开展失眠症的定期评估和健康管理。通过信息化的个案管理平台,提高疾病的防治效率,降低复发风险,有效促进医疗服务的可及性。  

二、分级诊疗、双向转诊(一)分级诊疗  

分级诊疗可以优化医疗服务、构建多层次化体系,通过专科和全科、二三级医院(二级甲、乙等医院,三级甲、乙等医院)等上级医疗机构和基层医疗机构的协同合作,给患者提供全疾病周期的医疗服务,使患者在失眠症的早期获得及时的干预,减少就医的不便和盲目性,以及减少镇静催眠类药物的滥用,有助于医师进行有针对性地随访和制定个体化的诊疗方案,有利于全面改善医疗服务质量与提高医疗服务效率[105] MEDI(二)各级医疗机构失眠症的诊治范围  

注:PSG为多导睡眠监测;rTMS为重复经颅磁刺激;tACS为经颅交流电刺激图1基层医疗机构失眠症诊疗流程图  

1.基层医疗机构:具备失眠症的识别能力,具有开展失眠症的诊疗、预防、康复能力。  

2.上级医疗机构:具有开展失眠症、药物依赖性失眠、异相睡眠障碍、不宁腿综合征、失眠症共病精神障碍和躯体疾病等疑难、急危重症的诊断、治疗能力。
# (三)上转指征
当基层医疗机构在处理失眠症患者时遇到以下情况,应考虑及时将患者转至上级医疗机构进行进一步的诊断和治疗。(1)失眠症经规范化治疗4周以上,未得到缓解或患者对治疗效果不满意。(2)需要上级医疗机构进行PSG、核磁共振等检查,以明确诊断和协助治疗。(3)基层不具备rTMS、tACS、生物反馈疗法等物理治疗设备,需上级医疗机构配合进行。(4)合并不稳定的躯体疾病、精神障碍、其他睡眠障碍。  

(四)下转指征  

失眠症经上级医疗机构规范治疗后,症状缓解的患者可下转至基层医疗机构进一步巩固治疗、康  

复、随访。  

三、规范治疗、定期随访(一)规范治疗  

治疗方式包括良好生活习惯、心理治疗、物理治疗、药物治疗、中医药治疗等。在基层医疗机构,良好生活习惯是防治基础,心理治疗和物理治疗是优选治疗策略,药物治疗是以上措施效果不佳的治疗方法。其中,CBTI可以提高基层失眠症的临床疗效[10],在减少复发率、降低发病率上有一定作用[10],值得在基层诊疗中进一步推广。  

(二)定期随访基层医疗机构可以通过面对面  

访谈、电话、手机App、微信随访等形式做好失眠患者定期随访。定期随访有利于提高患者的睡眠认知水平,定期更新健康档案,动态观察睡眠情况,及时就患者出现的睡眠问题进行治疗、干预和转诊,降低失眠症进一步严重、恶化的风险。  

推荐意见15:基层医疗机构在失眠症管理中承担重要任务,立足于筛查,建立电子健康档案,并根据诊疗范围与上级医疗机构开展规范化分级诊疗,并定期随访。(专家共识)  

总之,本共识的制订充分吸纳了国内外失眠症诊断与治疗领域的最新研究成果,经过数十位专家的深人讨论和反复推敲,经过多轮修订后形成最终文本。尽管失眠症的诊断和治疗在基层医疗机构中已有一定的实践基础,但仍面临着诸多挑战和需要进一步探索的问题,如患者接受度、医疗资源配置,以及长期治疗效果的评估等。本共识仅代表参与撰写的专家组的集体意见,不具有法律上的强制执行力。随着未来失眠症诊断和治疗技术的不断进步,以及相关临床研究的深人,本共识将根据新的科学证据进行适时更新和完善,以期为基层医疗机构提供更加精准和有效的指导。

"""
response = """
// 节点更新
MERGE (n:Disease {name: '失眠'});

MERGE (n:NonDrugTreatment {name: '光照疗法'})
SET 
    n.description = coalesce(n.description, '光线调节昼夜节律'),
    n.duration = coalesce(n.duration, '短期'),
    n.frequency = coalesce(n.frequency, '每天'),
    n.contraindication = coalesce(n.contraindication, '无'),
    n.equipment = coalesce(n.equipment, '无');

MERGE (n:NonDrugTreatment {name: '重复经颅磁刺激'})
SET 
    n.description = coalesce(n.description, '低频磁刺激改善睡眠质量'),
    n.duration = coalesce(n.duration, '短期'),
    n.frequency = coalesce(n.frequency, '根据需要'),
    n.contraindication = coalesce(n.contraindication, '无'),
    n.equipment = coalesce(n.equipment, '设备需要');

MERGE (n:NonDrugTreatment {name: '经颅电刺激'})
SET 
    n.description = coalesce(n.description, '向头皮施加低强度电流调节大脑活动'),
    n.duration = coalesce(n.duration, '短期'),
    n.frequency = coalesce(n.frequency, '根据需要'),
    n.contraindication = coalesce(n.contraindication, '无'),
    n.equipment = coalesce(n.equipment, '设备需要');

MERGE (n:NonDrugTreatment {name: '生物反馈疗法'})
SET 
    n.description = coalesce(n.description, '减少条件唤醒，改善入睡时间'),
    n.duration = coalesce(n.duration, '短期'),
    n.frequency = coalesce(n.frequency, '根据需要'),
    n.contraindication = coalesce(n.contraindication, '无'),
    n.equipment = coalesce(n.equipment, '无');

MERGE (n:DrugTreatment {name: '苯二氮草类药物'})
SET 
    n.description = coalesce(n.description, '用于治疗失眠的镇静催眠药物'),
    n.dosage = coalesce(n.dosage, '根据医生建议'),
    n.frequency = coalesce(n.frequency, '根据需要'),
    n.duration = coalesce(n.duration, '不超过4周'),
    n.route = coalesce(n.route, '口服'),
    n.contraindication = coalesce(n.contraindication, '重度呼吸衰竭');

MERGE (n:Complication {name: '焦虑症'})
SET 
    n.description = coalesce(n.description, '失眠可能导致焦虑症状加重'),
    n.severity = coalesce(n.severity, '严重');

MERGE (n:Complication {name: '抑郁症'})
SET 
    n.description = coalesce(n.description, '失眠与抑郁症状相关联'),
    n.severity = coalesce(n.severity, '严重');

// 关系更新
MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '光照疗法'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.85),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '初始治疗');

MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '重复经颅磁刺激'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.8),
    r.priority = coalesce(r.priority, '中'),
    r.stage = coalesce(r.stage, '联合治疗');

MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '经颅电刺激'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.75),
    r.priority = coalesce(r.priority, '中'),
    r.stage = coalesce(r.stage, '辅助治疗');

MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '生物反馈疗法'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.7),
    r.priority = coalesce(r.priority, '中'),
    r.stage = coalesce(r.stage, '辅助治疗');

MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '苯二氮草类药物'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.9),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '药物治疗');

MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '焦虑症'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 0.6),
    r.timeframe = coalesce(r.timeframe, '长期');

MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '抑郁症'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 0.5),
    r.timeframe = coalesce(r.timeframe, '长期');

"""

[[message_pairs]]
timestamp = "2024-12-19 00:08:25"
message = """

[隶属文件名]
基层医疗机构失眠症诊断和治疗中国专家共识.md
[隶属文件分块名]
基层医疗机构失眠症诊断和治疗中国专家共识/001-基层医疗机构失眠症诊断和治疗中国专家共识.md
[文本块]
# 基层医疗机构失眠症诊断和治疗中国专家共识
中国睡眠研究会  

通信作者:张斌,南方医科大学南方医院精神心理科(睡眠医学中心),广州510515,Email : zhang73bin@hotmail.com  

【摘要】失眠症是最常见的睡眠障碍,不仅增加多种躯体疾病和精神障碍的风险,而且带来沉重的社会卫生经济学负担。然而目前国内外均缺乏针对基层医疗机构失眠症的诊疗规范。为此,中国睡眠研究会组织国内睡眠医学专家,以国内外最新的研究进展为依据,制订本专家共识,针对失眠症的病理生理学机制、流行病学、诊断思路、筛查评估、防治措施和基层管理进行逐一阐述,共制订了2021YFC2501500 2023  

【关键词】睡眠障碍;失眠症;基层医疗机构;专家共识;诊断;治疗  

失眠症是最常见的睡眠障碍\",不仅增加多种 卫生经济学负担[2-3}。基层医疗机构指社区卫生服躯体疾病和精神障碍的风险,而且带来沉重的社会 务中心和站点、乡镇卫生院和村卫生室,是我国三  

级医疗制度的基础,主要提供常见病、多发病的预防、治疗和康复等基本公共卫生和医疗服务。目前,基层医疗机构对失眠症的诊疗手段相对有限,而且国内缺乏针对基层医疗机构失眠症的诊疗规范。因此,中国睡眠研究会组织国内睡眠医学领域的专家,以国内外的最新研究进展为依据,结合国内现状,经过反复讨论,制订本专家共识,为基层医疗机构的失眠症诊疗提供规范化参考和依据。
# 第一部分专家共识的制订方法
本共识制订采用共识会议制订法。2023年6月至2024年3月,中国睡眠研究会组织国内睡眠医学领域的专家,成立基层医疗机构失眠症诊断和治疗中国专家共识编写委员会(以下简称“编委会”),其中16名成员执笔撰写。系统检索了PubMed、EMBASE、Cochrane Library、中国知网、万方数据库和中国生物医学文献数据库等从建库到2023年12月发表的文献,检索词为“insomnia(disorder) \"“disorder of initiating and/or maintainingsleep\"“primary/community care/healthcare\"\"primary/community health/medical care/services/center (s)“失眠(症/障碍)”“睡眠起始/维持困难”“初级/社区卫生保健/服务”“基层医疗机构”等,涵盖的文献类型包括临床指南、专家共识、综述、荟萃分析以及原始临床研究。尽管国外医疗体系与我国存在差异,但仍可借鉴其初级/社区卫生保健/服务的相关内容。编委会成员对纳人的文献进行证据等级分级,在此基础上进行推荐强度分级。部分的共识内容可能无法在文献中找到理想证据,需编委会成员根据临床经验进行判断、推荐为“专家共识”。  

本共识的证据等级和推荐强度基于中华医学会发布的《中国制订/修订临床诊疗指南的指导原则(2022版)》4,采用证据等级和推荐强度的评估、制定与评价(grading of recommendations,assessment,developmentandevaluations,GRADE)分级系统对证据质量和推荐意见的强度进行分级「5}。其中,证据等级分为“高(A)、中(B)低(C)极低(D)\"四级,推荐强度分为“强(1)、弱(2)\"二级(表1)。
# 第二部分失眠的病理生理学机制
失眠机制尚不清楚,主要假说简述如下:一、三因素假说  

该假说从易感因素(predisposingfactors)促发因素(precipitating factors)和维持因素(perpetuatingfactors)三方面因素探讨失眠的心理学机制?,也称3P假说。易感因素包括年龄、性别、遗传及性格特征等,可影响个体的失眠易感性;促发因素包括生活事件及应激等,可诱发短期失眠;维持因素是失眠得以持续的行为和信念,包括应对短期失眠的不良行为(如延长在床时间)及对失眠本身的焦虑和恐惧等,进而发展为慢性失眠。  

表1GRADE证据等级和推荐强度分级标准  

注:GRADE为证据等级和推荐强度的评估、制定与评价
# 二、过度觉醒假说
该假说认为失眠是一种过度觉醒。这种过度觉醒呈持续性,横跨 $24~\\mathrm{h}$ 日周期,既包括担心、紧张、反刍等认知觉醒水平升高,也包括躯体、皮质等生理水平升高。失眠患者表现为睡眠期觉醒增多、日间小睡潜伏期延长 $.24\\,\\mathrm{h}$ 代谢率增加,以及清醒期更多β波活动”睡眠期的频繁 $\\upalpha$ 波和 $\\upbeta$ 波、自主神经功能活性增加、下丘脑-垂体-肾上腺轴过度活跃及炎症因子释放增加等[8]。
# 三、情绪应对假说
该假说提出,在快速眼动睡眠(rapid eyesmovement,REM)期间,健康人的大脑蓝斑停止释放去甲肾上腺素[4]。去甲肾上腺素的减少会阻断记忆与情绪反应之间的联系,使个体在睡眠中达到“情绪喘息\"的效果。失眠人群的REM睡眠则出现片段化,引发睡眠对不良情绪的适应不足,导致持续性情绪问题。该模型也解释了失眠作为精神障碍风险因素的原因。  

四、其他假说  

还包括认知假说[6、REM睡眠不稳定假说[9]刺激控制假说等。  

以上假说并不是相互排斥的,失眠的发生和发展可能是多种因素共同作用的结果,不同的假说衍生出不同的临床治疗方法。失眠认知行为治疗(cognitive behavioral therapy for insomnia, CBTI)建立在3P假说的基础上,通过改变失眠者的认知和行为模式来改善失眠症状。基于过度觉醒假说,临床可采取降低觉醒程度的治疗措施,例如通过放松训练缓解日间的烦躁情绪。情绪应对假说则提供了新的治疗思路,通过阻断去甲肾上腺素受体(如$\\upbeta$ -受体阻滞剂)或抑制蓝斑的活动(如胍法辛),调控REM睡眠而达到调节情绪反应和改善睡眠质量的效果。  

推荐意见1:失眠的病理生理学机制尚不清楚,主要包括三因素、过度觉醒和情绪应对等多种假说;各种假说并不相互排斥,失眠是多种因素共同作用的结果。(专家共识)
# 第三部分 失眠症的流行病学和高危因素
失眠症的现患率与定义、评估程序样本特征等因素有关。人群数据表明, $36.3\\%$ 成年人报告了当前存在至少一种失眠症状[1,将日间功能受损添加到失眠定义时,现患率降至 $9\\%{\\sim}15\\%^{[11]}$ ,使用《精神障碍诊断与统计手册(第五版)》(Diagnostic andStatistical  Manual of Mental Disorders  5th Ed,DSM-5)或《国际睡眠障碍分类第3版文字修订版》(The  International   Classification of  SleepDisorders-Third Edition, Text Revision, ICSD-3-TR)的失眠症诊断标准时,现患率则为 $6\\%{\\sim}10\\%^{\\left[12\\right]}$  

女性的失眠现患率约为男性的1.5倍[。随着年龄增长而睡眠能力逐渐下降,老年人的失眠现患率最高[41]。一项美国全国性睡眠调查发现失眠人群中,白人为 $10\\%$ 、亚洲人为 $4\\%$ ,这可能与不同种族文化人群的睡眠态度和信念差异有关16]。失眠的自然病程具有波动性,可能自发缓解。一项研究对388例失眠患者进行了为期3年随访,结果显示 $54\\%$ 的患者在某个时间点进人缓解期,但其中约半数又最终复发[]。不同严重程度的失眠患者存在不同的病程轨迹,基线的严重失眠患者往往表现出更持久的病程。综上所述,失眠发生发展的影响因素众多,包括性别、年龄、失眠既往史、严重程度、家族史、心理脆弱性、生物易感性等。  

失眠症会带来一系列不良后果。短期包括醒来时身体不适、疲劳、易怒、对噪音和光线敏感,以及日间动力下降等[8。长期失眠是多种精神疾病发展的风险因素,增加抑郁症、焦虑症、物质滥用障碍等精神障碍的发病风险[19-0]。失眠还常伴随躯体疾病,因为慢性失眠引发的过度觉醒导致植物神经活动过于活跃从而诱发心脑血管系统疾病[2],失眠患者由于睡眠剥夺导致血糖调节能力受损,也容易诱发糖尿病等代谢性疾病[。此外,失眠带来沉重的社会卫生经济学负担,导致患者及其家庭的生活质量下降[23-24]  

推荐意见2:大多数的失眠流行病学研究采用了自评问卷而非诊断工具或客观监测数据,所以失眠的流行病学特征尚需更多高质量研究。(专家共识)
# 第四部分失眠症的基层医疗机构防治情况
20世纪80年代我国第一家睡眠呼吸障碍诊疗中心成立,至今已有3000余家医疗机构具备睡眠监测的条件[25],从业人数大幅增长,诊治范围也由单一类型睡眠障碍向综合类型睡眠障碍转变。多部专著与指南也为睡眠障碍的规范化诊治提供了依据。然而,我国的睡眠医学专业仍存在发展不均衡[26] 、技术门槛高、人才培养不系统等问题。2022年的《全国医院睡眠医学业务开展情况调查》覆盖了31个省市自治区的各级综合与专科医院,调查显示仅 $2\\%$ 基层医疗机构开展了睡眠业务,前三位阻碍因素为专业人才缺乏( $76\\%$ )、设备成本高昂( $70\\%$ )、缺乏睡眠障碍患者 $(33\\%)^{[27]}$ 。需要关注的是,睡眠医学在我国尚未成为独立的二级学科,没有独立学位培养点,缺乏睡眠技师、住院医师及专科医师规范化培训体系和认证机构[7],因此限制了专业人才培养。  

目前,基层医疗机构的失眠症主要采用传统镇静催眠药及中医药治疗。由于医疗水平和设备条件的影响,很多失眠治疗方式在基层医疗机构没有开展28],失眠症的分级诊疗制度也需要确立和完善。  

推荐意见3:基层医疗机构的失眠症防治水平受到了睡眠医学发展现状的制约,失眠症的分级诊疗制度也需要确定和完善。(1B)
# 第五部分失眠症在基层的诊断和鉴别诊断
一、临床诊断失眠既可以是一种症状,也可以是独立的疾病。通常来说,失眠症状是短期与压力、焦虑等因素相关的失眠问题,通常是短期的、可自行缓解的。失眠症是持续数月的、对个体的社会功能产生较大负面影响的睡眠障碍。
# (一)失眠症状
失眠症状包括存在人睡困难、睡眠不深、易醒、早醒等,并导致了明显的日间功能受损。
# (二)失眠症
根据ICSD-3-TR,失眠症可分为慢性失眠症(chronic insomnia disorder)短期失眠症(short-terminsomnia disorder)和其他失眠症(other insomniadisorder)。诊断标准如下:  

1.慢性失眠症(ICD-11编码:7A00):标准 $(\\,1\\,)\\,\\sim$(6)都必须满足:(1)患者报告,或患者父母或照顾者观察到患者存在下列1条或以上: $\\textcircled{\\scriptsize{1}}$ 人睡困难;$\\textcircled{2}$ 睡眠维持困难; $\\textcircled{3}$ 比期望的起床时间醒来早;$\\textcircled{4}$ 在适当的时间点不肯上床睡觉; $\\textcircled{5}$ 没有父母或照顾者干预难以人睡。(2)患者报告,或患者父母或照顾者观察到患者存在下列与夜间睡眠困难相关的1条或以上: $\\textcircled{\\scriptsize{1}}$ 疲劳或萎靡不振; $\\textcircled{2}$ 注意力、专注力或记忆力下降; $\\textcircled{3}$ 社交、家庭、职业或学业等功能损害: $\\textcircled{4}$ 情绪不稳或易激惹; $\\circled{5}$ 日间困倦: $\\circled{6}$ 行为问题(如活动过度、冲动或攻击性): $\\textcircled{7}$ 动力、精力或工作主动性下降; $\\circled{8}$ 易犯错或易出事故; $\\circledcirc$ 对自己的睡眠质量非常关切或不满意。(3)这些睡眠/觉醒主诉不能完全由不合适的睡眠机会(如充足的睡眠时间)或环境(如黑暗、安静、安全、舒适的环境)解释。(4)这些睡眠困难和相关的日间症状至少每周出现3次。(5)这些睡眠困难和相关的日间症状持续至少3个月。(6)这些睡眠紊乱和相关的日间症状不仅仅是由于当前的另一种睡眠障碍、躯体疾病、精神障碍或药物/物质使用所致。  

2.短期失眠症(ICD-11编码:7A01):短期失眠症诊断标准为符合慢性失眠症第(1)\\~(3)、(6)条标准,主要区别在于病程 $<\\!3$ 个月,且没有频率的要求。  

3.其他失眠症(ICD-11编码:7A0Z):指存在失眠症状但不符合另外两类诊断标准的情况。
# 二、鉴别诊断
失眠症可共病某种躯体疾病或精神障碍,需要区别单纯性失眠症、共病性失眠症,以及没有达到诊断标准的失眠症状。  

1.精神障碍:如抑郁障碍、双相情感障碍、焦虑障碍等引起的失眠症状。  

2.躯体疾病:如内分泌系统疾病、神经系统疾病、心血管系统疾病、呼吸系统疾病、消化系统疾病等继发的失眠症状。  

3.精神活性物质或药物:如抗抑郁药物、中枢兴奋性药物、心血管药物、麻醉性镇痛药和平喘药等药物及酒精和烟草等物质诱发的失眠症状。  

4.其他睡眠障碍:如睡眠呼吸障碍、不宁腿综合征、发作性睡病、异态睡眠等伴发的失眠症状。  

5.昼夜节律相关睡眠障碍:由于个体的生物钟与外部环境的日夜节律不一致引起,如倒班或飞行时差。  

6.环境性睡眠障碍:存在干扰睡眠的环境因素时,不应诊断为失眠症。  

7.睡眠不足综合征:过度或有意延长工作或娱乐的时间而缺乏充足的时间睡眠,应与失眠症鉴别。  

推荐意见4:失眠既可以是一种症状,也可以是独立的疾病。需要鉴别单纯性失眠症、共病性失眠症,以及未达诊断标准的失眠症状。(专家共识)
# 第六部分失眠症的基层筛查和评估方法及工具
一、失眠症的基层筛查  

定期筛查有助于及早发现睡眠问题,降低失眠症的患病率,减少社会卫生经济学的影响,促进社会的睡眠健康认知[29]  

二、失眠症的评估方法及工具  

1.病史采集:(1)现病史: $\\textcircled{\\scriptsize{1}}$ 核心症状及伴随症状: $\\textcircled{2}$ 睡前状况:评估傍晚到睡前的行为模式、心理活动及睡眠环境: $\\textcircled{3}$ 睡眠-觉醒节律:了解日常作息习惯; $\\circledast$ 日间功能损害:日间的工作和学习情况,以及思睡和疲劳状况。(2)其他:既往史、个人史、月经史、婚育史、家族史等。  

2.体格检查:全面体格检查(包括神经系统检查)以评估患者的躯体状况。  

3.精神检查:评估患者的精神状态,建议使用抑郁筛查量表(the patient health questionnaire,PHQ-9)、医院焦虑抑郁量表(hospital anxiety anddepression scale,HADS)等量表辅助评估常见抑郁和焦虑情绪。  

4.辅助检查:病史提示潜在疾病影响睡眠时, 需进行相关辅助检查(如动态血压监测、磁共振、甲 状腺功能等检查)以明确诊断,必要时转诊至上级 医院[30-31]  

5.睡眠检查:(1)主观评估工具: $\\textcircled{\\scriptsize{1}}$ 睡眠日记:患者应连续2周(至少1周)记录每天的活动和睡眠情况,从而评估睡眠节律,计算睡眠效率等指标[3]$\\textcircled{2}$ 量表评估:常用量表包括失眠严重程度指数(insomnia severity index,ISI)、匹兹堡睡眠质量指数(Pittsburgh sleep quality index, PSQI) ,Epworth 嗜睡量表(Epworth sleepiness scale,ESS)、清晨型-夜晚型量表(Morning and evening questionnaire,MEQ)睡眠呼吸暂停初筛量表(Snoring,tiredness,observed apnea, high blood pressure-body massindex, age, neck circumference and genderquestionnaire,STOP-BANG)、不宁腿综合征问卷(restless legs syndrome questionnaire, RLSQ)等。(2)客观评估工具:多导睡眠监测(polysomnography,PSG)需要睡眠实验室和专业技术人员,在基层医院不易开展,基层可以使用家用睡眠监测设备[3-3]、活动记录仪(actigraphy)、非侵人式远程监控、额贴脑电和手环等创新设备[34]。  

推荐意见5:失眠症的基层定期筛查非常必要,睡眠日志、量表及活动记录仪在失眠筛查和评估中具有实际操作的便捷性和准确性。(1B)  

三、中医的评估方法及工具  

中医的失眠评估包括病史采集和望、闻、问、切,用于证候的鉴别诊断和确立诊断。目前,已经发展了较多的中医评估量表:失眠症系列状态量表[35-38]、老年失眠中医 PRO量表[39]、失眠症中医生存质量量表[4]、中医失眠量表[41]、主观性失眠评定问卷[42-43]、成人不寐中医证候流行病学调查问卷[44] 、失眠症中医辨证诊断和治疗前瞻性评定表[45]。这些量表除了评估夜间睡眠,均涵盖了日间精神状态、情绪状态、脏腑功能表现,以症状程度和频率评分,反映整体证候表现。  

推荐意见6:中医失眠评估量表用于证候的诊断,对失眠的中医分型治疗具有临床意义。(2B)
# 第七部分 防治措施

# 一、目标
针对基层医疗机构的医疗条件,以及服务人群的特点,利用现有医疗资源,结合现代技术,制定合理的中西医结合防治方案。实现以下目标:(1)增加有效睡眠时间和(或)改善睡眠质量;(2)改善失眠相关日间损害;(3)降低失眠慢性化的概率;(4)减少失眠引发躯体疾病或与精神障碍的风险。
# 二、防治措施
包括良好生活习惯、心理治疗、物理治疗、药物治疗、中医治疗等。在基层医疗机构,良好生活习惯是防治基础,心理治疗和物理治疗是优选治疗策略,药物治疗是以上措施效果不佳的治疗方法。  

(一)良好生活习惯[46-47]  

1.科学膳食:《中国居民膳食指南(2022)》建议[4],注意饮食的搭配和营养的摄人,增加膳食纤维和水分的摄人量,避免过量摄人高糖、高脂、高盐的食物,适当控制总能量摄入,以维持身体的健康。失眠者还应该避免午后摄人咖啡、茶、奶茶、酒精饮品等刺激性食物,以及睡前过度进食等。(1B)  

2.充足日照:光照是维持生物节律的最重要授时因子[4-5],失眠患者应减少夜间人工光源,特别是电子产品的使用;增加日间自然光照,上午的光照比下午更能促进睡眠[52]。(1B)  

3.合理运动:运动可以改善睡眠质量[53],并有助于建立稳定的休息-运动规律[54],推荐瑜伽、太极拳、八段锦等传统运动。(2C)  

4.心理调适:可以自我进行以下心理调适:(1)放松训练:降低紧张与过度警觉,提高睡眠质量3,包括渐进式肌肉放松训练、腹式呼吸、冥想等[\\$5]。(2)音乐疗法:轻柔舒缓的音乐可以降低神经系统兴奋性,减轻焦虑情绪从而改善睡眠[56]。(3)调整认知:不灾难化和过分关注失眠,不因偶尔失眠而产生挫败感,培养失眠的耐受性[7。(2A)  

推荐意见7:科学膳食(1B),充足日照(1B)、合理运动(2C)、心理调适(2A)等良好生活习惯,可以保持健康的身心状况,促进健康睡眠。
# (二)心理治疗
失眠的心理治疗以CBTI为代表,CBTI是针对行为和认知因素导致失眠症的多成分非药物治疗,包括睡眠卫生教育、睡眠限制治疗、刺激控制治疗、认知治疗、放松训练等5个部分,被国内外指南推荐为失眠症的一线治疗[58-66]。  

传统的面对面模式CBTI效果良好,但是对治疗师要求较高,且受时间和空间限制,随着信息技术的发展,失眠数字疗法(digital therapies forinsomnia,DTI)应运而生,可以通过应用程序、微信、网络、电话等形式开展[65,67] ,大幅度降低了治疗成本,不受时间和空间限制,且与传统模式CBTI的效果相当[]。基层医疗机构可通过“阶梯式保健”模式,在社区环境中以自助式CBTI作为失眠的阶梯式保健的首选6\"。并根据失眠的严重程度将患者分配到不同级别的保健机构中,增加患者的治疗机会,节省有限的专家资源[7]  

推荐意见8:阶梯式保健和DTI等创新模式有助于CBTI在基层医疗机构实施。(1A)

"""
response = """
// 节点更新
MERGE (n:Disease {name: '失眠症'})
SET 
    n.description = coalesce(n.description, '最常见的睡眠障碍'),
    n.category = coalesce(n.category, '睡眠障碍');

"""
