[metadata]
file_name = "多发性硬化合并睡眠障碍研究进展.md"
processed_at = "2024-12-18 16:48:29"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-18 09:56:09"
message = """

[隶属文件名]
多发性硬化合并睡眠障碍研究进展.md
[隶属文件分块名]
多发性硬化合并睡眠障碍研究进展/001-完整文档.md
[文本块]
·综述·
# 多发性硬化合并睡眠障碍研究进展
陈健华 刘秀琴 黄颜 孙鹤阳 孟琼  

多发性硬化(MS)是一种慢性中枢神经系统自身免疫性脱髓鞘疾病,主要累及 $20\\sim50$ 岁人群,世界范围内约250万人患病[!,是青年及中年人最常见的非外伤性神经系统疾病。MS睡眠障碍发生率高,常见的睡眠障碍包括:失眠、睡眠运动障碍、睡眠相关呼吸异常、发作性睡病、快速眼动期(REM)睡眠行为障碍、异常睡眠-觉醒节律、白天睡眠过多。导致MS患者睡眠障碍的原因,包括与疾病相关性(原发性)和继发于疼痛、运动受限、痉挛状态、夜尿增多、呼吸肌或呼吸中枢受累导致的睡眠呼吸障碍、抑郁和药物治疗的不良反应等(继发性)[2”。本文将综述MS所伴有的各种睡眠障碍的发病情况、临床表现、影响因素及治疗。
# 一、失眠
失眠分为人睡困难(初期失眠),睡眠维持困难(中期失眠),或者早醒(终期失眠)。初期失眠最常见的原因是焦虑和疼痛/不适,中期失眠最常见的原因是夜尿增多,中期失眠是导致日间疲劳的主要因素,终期失眠常与抑郁有关3}。普通人群失眠率为 $10\\%\\sim15\\%$ ,而MS患者则达 $54\\%$ ,明显高于普通人群[4]。其中, $42\\%$ 是初期失眠, $53\\%$ 中期失眠, $58\\%$为终期失眠[3。普通人群抑郁症、焦虑症患病率分别为$2.\\,1\\%\\sim3.\\,4\\%$ 和 $2.\\,3\\%\\sim6.\\,3\\%^{\\,[5+}$ 。MS 患者终身情感障碍如抑郁症的患病率达 $50\\%$ ,这些患者经常主诉失眠或睡眠过度[7]。
# 二、不安腿综合征(RLS)
RLS是一种累及感觉运动的疾病。国际 RLS 研究组RLS诊断标准:(1)肢体运动的欲望,常与肢体不适感有关;(2)通过活动肢体可缓解症状;(3)休息时症状加重;(4)夜间症状加重。症状严重时,RLS可以影响睡眠,导致白天嗜睡、抑郁、失眠和疲劳[8]。RLS 病理机制包括:遗传因素、铁缺乏、多巴胺储存/转运机制缺陷、周围神经病和糖尿病。  

MS 患者 RLS 患病率为 $31.9\\%$ []。意大利针对 MS 患者的RLS研究组通过多中心研究发现,MS患者RLS患病率是 $19\\%$ ,而普通人群 RLS 患病率只有 $4.2\\%$ [10]。MS 易患RLS的危险因素包括:高龄;较长的MS病程;原发性进行性MS;较重的锥体束征和感觉功能障碍以及人睡前腿部痉挛[10]。RLS 可加重 MS 的功能障碍,加重睡眠障碍。当 MS的RLS症状为中度或重度时,可以导致睡眠片段化,引发疲劳、情绪改变、认知功能障碍。  

$80\\%\\sim90\\%$ RLS合并周期性肢体运动(PLMS)。PLMS是刻板性、周期性肢体活动,常见于下肢,表现为大拇脚趾伸展,踝关节、膝关节和髋关节持续性屈曲。PLMS和RLS均可导致人睡困难、睡眠维持障碍、白天嗜睡,这些均与MS 疲劳的发生和睡眠质量下降有关。
# 三、睡眠呼吸障碍
阻塞性睡眠呼吸暂停(OSA)是最常见的呼吸障碍,累及$2\\%\\sim4\\%$ 的成人。中枢性睡眠呼吸暂停(CSA)少见,普通人群患病率不详。 $8\\%$ 的MS存在 $0\\mathbf{S}\\mathbf{A}^{[4]}$ ,高于普通人群。具有 OSA的 MS患者与无 OSA 的 MS 患者在磁共振成像(MRI)上病灶分布无显著差异。MS易患OSA可能原因包括:针对MS疼痛、痉挛的药物可能降低咽喉肌的肌张力;神经功能障碍所致的活动减少导致的肥胖;脑干病灶累及疑核。  

中枢性肺泡通气不足综合征是CSA的一种表现形式,患者清醒时呼吸正常,但在非REM期睡眠出现长程或持续通气不足,伴有血氧饱和度降低和高碳酸血症。中枢性肺泡通气不足源于自主通气障碍,大部分是先天性的,少部分为获得性,主要累及延髓和(或)高位颈髓,病因包括缺血性、炎性病变或肿瘤。Auer 等[1报道2例可以行走的MS 患者,人睡后出现高碳酸和低氧血症,户检发现延髓有硬化斑块。延髓孤束核病灶致使膈肌瘫痪导致CSA,这类患者夜间可发生致死性睡眠呼吸暂停,需给予重视。
# 四、发作性睡病
发作性睡病是一种以过度日间嗜睡为特征的慢性睡眠障碍,表现为白天发作性人睡、REM期睡眠异常(如入睡前/睡梦中幻觉)、猝倒、睡眠麻痹、夜眠不实。多次小睡检查显示睡眠潜伏期缩短 ${\\leqslant}8\\,\\mathrm{\\min}$ ,出现2次或2次以上以REM为起始的睡眠。患病率日本人 $(159\\sim160)/100\\;000$ ,以色列人0. 23/100 000,欧洲人(3 \\~ 5)/10 000[1,12]  

发作性睡病与人白细胞抗原DR2、DR6和DQw1高度相关,属于原发性睡眠障碍。MS与发作性睡病在遗传易感性方面有-定关联。MS易感基因位于人白细胞抗原DR-DQ亚区之内或与之邻近[,13]。 $95\\%$ 的发作性睡病, $50\\%\\sim60\\%$的MS 为DR单体型DR2阳性。人白细胞抗原 $\\mathrm{DQB1}*0602$是发作性睡病的遗传高危因素,其与MS亦有关系,并且与MS严重程度相关。  

发作性睡病与下丘脑分泌的一种具有维持清醒和能量消耗作用的神经肽类一orexin缺乏有关,orexin可刺激食物摄人,orexin的减少可能是自身免疫介导的。炎性脱髓鞘疾病可引起继发性发作性睡病。水通道蛋白4主要在下丘脑室旁区域表达,针对水通道蛋白4的免疫攻击与下丘脑损害和orexin缺乏有关,导致发作性睡病或白天睡眠过多[4]。发作性睡病可以是抗水通道4抗体阳性的视神经脊髓炎患者的首发症状[15]。MS 的下丘脑炎性病灶可导致可逆性orexin系统功能障碍,引起脑脊液中orexin水平降低,出现发作性睡病样临床表现[16]
# 五、REM 期睡眠行为障碍
REM期睡眠行为障碍(RBD)是以REM睡眠期肌肉弛缓现象消失并出现与梦境相关的异常运动行为为特征的发作性疾病。异常运动可由简单的言语、唱歌、喊叫到复杂的运动现象如奔跑、拳打脚踢、坠床等。常有暴力色彩,可自伤或伤及同床者。  

RBD病因可以是特发性,或者继发于神经系统疾病,最常见的是帕金森病、多系统萎缩、路易体痴呆和进行性核上性眼肌麻痹,其次是脑干血管病、MS及脑干肿瘤。普通人群RBD患病率为 $0.\\,38\\%\\,\\sim0.\\,50\\%$ ,常见于中老年男性。RBD可以是 MS 的首发症状。 $1,4\\%$ 的MS合并 $\\mathbf{RBD}^{[17]}$ 。正在接受抗抑郁治疗的 MS 患者需警惕RBD风险[1]。  

RBD与脚桥核病灶有关,脚桥核与蓝斑和网状结构联系,导致REM期睡眠肌张力持续存在。当MS患者中脑脑桥背盖部或延髓腹内侧部存在炎性破坏性病灶时,可导致RBD。  

六、昼夜节律失调性睡眠障碍(CRD)  

当个体睡眠与觉醒节律和外部环境不协调时即可发生CRD。CRD 常导致失眠、白天睡眠过多或两者兼有,影响工作、学习或社交。患者表现为睡眠时相提前、睡眠时相延迟、睡眠-觉醒节律紊乱或者自由式睡眠-觉醒节律。  

Attarian等2]对15例有疲劳感的MS患者、15例无疲劳感的MS患者和15名正常对照进行研究,发现2例有疲劳感的患者存在睡眠时相延迟,无疲劳感的患者中仅1例出现,正常对照不存在该问题。  

动物模型显示,CRD的发生与位于视交叉上部的掌管生物节律的视交叉上核损伤有关。MS脱髓鞘病变累及该路径,使生物节律功能受损。
# 七、疲劳与白天睡眠过多
疲劳是MS最常见的症状, $75\\%\\sim85\\%$ 的患者存在疲劳: $:50\\%\\sim60\\%$ 的患者认为疲劳是他们致残的主要原因[\"]。持续性的疲劳被MS 患者认为是使其致残的严重症状之一,并严重影响其生活质量。 ${28\\%}$ 的患者对疲劳感到烦恼至极[20]。  

下述因素可能与疲劳发病机制有关:中枢传导通路上神经脱髓鞘改变导致传导速度延迟、单胺类神经递质系统紊乱、脑内局灶性损害(右侧顶颞部及左侧额部白质病变以及额叶、顶叶皮质萎缩)、免疫功能障碍(疾病相关性和免疫调节治疗的不良反应)、由于痉挛肌肉能量需求增高、疼痛、自主神经功能不稳、睡眠障碍、心理因素(抑郁、焦虑、无助感、症状治疗效果缺失感)、人格特质[21]  

MS的疲劳在早晨即可显现,可因潮湿、炎热加重,白天随时间推移症状加重,午后症状明显。其与性别、年龄、教育程度、神经心理行为、MRI上病灶部位及病灶数量或者神经解部发现无关,而与病程长短、病情轻重、残疾程度、进展类型相关[2]。正电子发射计算机断层显像(PET)显示 MS 的疲劳与脑内特殊区域包括额叶和皮质下通路的低代谢有关[22]。脑脊液中orexin水平与疲劳程度呈正相关[23]  

觉醒的维持主要与下丘脑结节乳头体核的组胺能神经元有关,白天睡眠过多或者发作性睡病的MS患者脑脊液中组胺水平下降。 $6.8\\%$ MS 患者存在白天睡眠过多[24]。白天睡眠过多可能与睡眠不足或者具体的睡眠障碍如睡眠呼吸暂停、继发性发作性睡病有关。Kaynak等[5]对27例有疲劳主诉的MS患者睡眠结构研究发现,Pittsburgh睡眠质量指数评分、睡眠效率指数、睡眠持续指数、人睡后醒觉时间、总觉醒指数和PLMS觉醒指数异常,由此得出结论,MS存在睡眠片段。  

睡眠质量下降可加重MS的疲劳症状,疲劳本身又引起或加重睡眠障碍。 $\\upbeta$ 干扰素或格拉默治疗可导致全身效应,使患者产生不适,诱发疲劳26]
# 八、MS 睡眠障碍治疗
MS易受失眠困扰, $19.5\\%$ 的患者需每天服用处方类安眠药物, $10.\\,6\\%$ 间断使用安眠药, $,7.8\\%$ 每天使用非处方类助眠药, $14.\\,2\\%$ 间断使用助眠药。与普通人群失眠治疗一样,MS失眠治疗包括正确的睡眠生理卫生、认知行为疗法,必要时药物干预。  

MS患者常因括约肌功能障碍、痉挛状态和疼痛导致睡眠障碍,针对MS本身的药物治疗如干扰素、格拉默、米托葱醒和那他珠单抗等亦很重要,虽然用干扰素-β治疗也可能产生失眠的不良反应。  

多巴胺能药物是治疗RLS一线药物。罗匹尼罗和普拉克索都是美国食品药品管理局(FDA)批准的用药。其他未经FDA批准的药物包括类罂粟碱、加巴喷丁和苯二氮■类。上述药物亦可缓解MS 的RLS和疲劳症状[  

MS合并发作性睡病目前尚无治疗指南,但如果是急性MS 斑块造成的症状,可用大剂量甲强龙缓解症状[27]。莫达非尼用于日间过度嗜睡。  

RBD存在下述情况需要考虑药物治疗:(1)与梦境相关的剧烈动作,防止造成伤害;(2)减少令患者不快及不适的梦境密度;(3)避免破坏同床者睡眠质量。氯硝西泮是特发性RBD的一线用药,小剂量即有效,常用范围0.5~$2.\\ 0\\ \\mathrm{mg/d}$ .氯硝西泮降低位相性REM肌电活动,对紧张性REM肌电活动无影响。褪黑激素有助于提高REM期睡眠比例,减少REM睡眠肌肉失弛缓现象,缩短REM期异常行为的时间,是RBD二线用药,常用范围 $3\\sim12~\\mathrm{mg/d}$ 。与氯硝西泮不同,褪黑素仅降低紧张性REM肌电活动,不改变位相性REM肌电活动。选择性5羟色胺再摄取抑制剂和其他抗抑郁药物能加重RBD症状,应注意避免使用。  

MS疲劳的非药物治疗包括物理治疗、避免受热及适当体育锻炼[23]。可尝试使用金刚烷胺、莫达非尼、利他林或氨基吡啶对症治疗白天睡眠过多和慢性疲劳。  

OSA的治疗包括减肥、牙齿矫正器、体位治疗、正压通气及手术治疗。继发于延髓急性炎性病灶的中枢性肺泡换气不足患者,应首先应用类固醇激素治疗以缓解病情。CSA治疗包括双相正压通气或者膈肌起搏。  

睡眠障碍是评估 MS 生活质量的独立因子[28]。慢性持续性睡眠障碍导致患者生活质量下降。尽管MS与各种睡眠障碍有关,但患病率和相关程度还不清楚,目前都局限于小样本研究,且缺乏客观报告或PSG资料。未来应进行大样本、多中心、前瞻性研究,采用主观报告和客观方法相结合,评价MS与睡眠障碍的关系以及睡眠障碍与疲劳、痉挛、疼痛、焦虑抑郁、运动障碍等之间的相互作用,并行随机对照治疗研究。总之,MS睡眠障碍研究任重而道远。

"""
response = """
// 节点更新
MERGE (n:Disease {name: '多发性硬化'})
SET 
    n.code = coalesce(n.code, 'MS'),
    n.description = coalesce(n.description, '一种慢性中枢神经系统自身免疫性脱髓鞘疾病'),
    n.category = coalesce(n.category, '神经系统疾病'),
    n.severity = coalesce(n.severity, '中等');

MERGE (n:Symptom {name: '失眠'})
SET 
    n.description = coalesce(n.description, '人睡困难、睡眠维持困难或早醒'),
    n.severity = coalesce(n.severity, '轻至重'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '不安腿综合征'})
SET 
    n.description = coalesce(n.description, '累及感觉运动的疾病，表现为肢体运动的欲望'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '睡眠呼吸障碍'})
SET 
    n.description = coalesce(n.description, '包括阻塞性睡眠呼吸暂停和中枢性睡眠呼吸暂停'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '发作性睡病'})
SET 
    n.description = coalesce(n.description, '以过度日间嗜睡为特征的慢性睡眠障碍'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '少见');

MERGE (n:Symptom {name: 'REM期睡眠行为障碍'})
SET 
    n.description = coalesce(n.description, 'REM睡眠期肌肉弛缓现象消失，并出现异常运动行为'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '少见');

MERGE (n:Symptom {name: '昼夜节律失调性睡眠障碍'})
SET 
    n.description = coalesce(n.description, '睡眠与觉醒节律和外部环境不协调'),
    n.severity = coalesce(n.severity, '轻'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '疲劳'})
SET 
    n.description = coalesce(n.description, '持久的疲惫感，影响生活质量'),
    n.severity = coalesce(n.severity, '重'),
    n.frequency = coalesce(n.frequency, '常见');

// 关系更新
MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '多发性硬化'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.54),
    r.frequency = coalesce(r.frequency, '高'),
    r.severity = coalesce(r.severity, '重');

MATCH (from) WHERE from.name = '不安腿综合征'
MATCH (to) WHERE to.name = '多发性硬化'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.319),
    r.frequency = coalesce(r.frequency, '高'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '睡眠呼吸障碍'
MATCH (to) WHERE to.name = '多发性硬化'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.08),
    r.frequency = coalesce(r.frequency, '中等'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '发作性睡病'
MATCH (to) WHERE to.name = '多发性硬化'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.1),
    r.frequency = coalesce(r.frequency, '低'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = 'REM期睡眠行为障碍'
MATCH (to) WHERE to.name = '多发性硬化'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.014),
    r.frequency = coalesce(r.frequency, '低'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '昼夜节律失调性睡眠障碍'
MATCH (to) WHERE to.name = '多发性硬化'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.2),
    r.frequency = coalesce(r.frequency, '中等'),
    r.severity = coalesce(r.severity, '轻');

MATCH (from) WHERE from.name = '疲劳'
MATCH (to) WHERE to.name = '多发性硬化'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.75),
    r.frequency = coalesce(r.frequency, '高'),
    r.severity = coalesce(r.severity, '重');

"""
