[metadata]
file_name = "成人阻塞性睡眠呼吸暂停高危人群筛查与管理专家共识.md"
processed_at = "2024-12-27 20:09:32"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-27 20:08:11"
message = """

[隶属文件名]
成人阻塞性睡眠呼吸暂停高危人群筛查与管理专家共识.md
[隶属文件分块名]
成人阻塞性睡眠呼吸暂停高危人群筛查与管理专家共识/001-完整文档.md
[文本块]
# 成人阻塞性睡眠呼吸暂停高危人群筛查与管理专家共识
中华医学会呼吸分会睡眠呼吸障碍学组中国医学装备协会呼吸病学装备技术专业委员会睡眠呼吸设备学组  

通信作者:欧琼,广东省人民医院呼吸与危重症医学科睡眠中心,广州510080,Email:ouqiong2776@hotmail.com;肖毅,中国医学科学院北京协和医院呼吸与危重症医学科,obstructive s  

【摘要】阻塞性睡眠呼吸暂停(obstructive sleep apnea,OSA)是一种常见的睡眠呼吸疾病,其可能的高危因素包括男性、年龄的增加、上气道及颌面结构异常、肥胖、不良生活方式、遗传因素和使用镇静安眠类药物等。OSA与高血压、冠心病、卒中、糖尿病等全身多个系统疾病的发生发展密切相关,导致医疗费用及社会负担增加。由于公众缺乏对该病所致严重后果的认知,仅依靠患者主动就医的模式,远不能解决OSA高患病率、低诊治率的现状。因此,针对OSA高危人群开展筛查和规范管理,对降低OSA疾病负担具有十分重要的意义。为了使OSA这一疾病在不同场景和人群中得到充分认识和筛查,中华医学会呼吸分会睡眠呼吸障碍学组、中国医学装备协会呼吸病学装备技术专业委员会睡眠呼吸设备学组组织有关专家,制定了本共识。共识强调了OSA高危人群筛查的对象包括具有OSA患病危险因素、相关合并疾病、相关职业风险等人群。推荐基层医疗机构、体检中心和医院相关科室对OSA高危人群进行筛查。阐明了不同场景和人群中筛查OSA的工具、方法和流程。强调筛查出的OSA高危人群需由医疗机构采用医用级睡眠监测设备包括家庭睡眠呼吸暂停监测或多导睡眠图完成诊断。对OSA高危人群和确诊患者均强调全面生活方式干预的重要性。对明确诊断的OSA患者应进行规范化管理,包括采取个体化的治疗方案,气道正压通气可作为优先选择,可选择的治疗还包括口腔矫治器、体位治疗,外科手术等。推荐建立规范的患者随访制度,及时发现OSA疾病进展,定期评估临床干预效果。  

【关键词】睡眠呼吸暂停,阻塞性;高危人群;筛查;管理;专家共识基金项目:国家自然科学基金(82170098)  

阻塞性睡眠呼吸暂停(obstructive sleep apnea, OSA)是一种常见的睡眠呼吸疾病,以呼吸暂停低通气指数(apnea-hypopnea index,AHI) ${\\geqslant}5$ 次/h为诊断标准,我国约有1.76亿患者\",患病人数居全球首位。鉴于该病带来的巨大医疗负担,依据OSA的患病危险因素对高危人群进行筛查、早期诊断和管理,具有十分重要的意义。目前OSA的防治仍以已经开展睡眠呼吸诊疗工作的三级甲等综合性医院为主。由于受开展睡眠呼吸疾病诊疗工作的医院数量、技术人员力量等的限制,实际获得诊疗的OSA患者人数十分有限,而且人群对OSA的认知度低,不能进行预防或主动诊治,多数OSA高危患者未能被识别出,病程进展到出现合并症后,其管理难度明显加大。单纯依靠患者到医院就诊的单一途径来实施OSA的诊疗远远不能满足实际需求,需要早期筛查,将OSA防治关口前移。为了进一步提高OSA的知晓率、诊治覆盖率,由中华医学会呼吸分会睡眠呼吸障碍学组、中国医学装备协会呼吸病学装备技术专业委员会睡眠呼吸设备学组组织相关专家,通过对国内外成人OSA筛查和管理的相关研究进行全面回顾,充分讨论,共同制定了本共识,针对OSA高危人群的筛查对象、筛查方法、管理方式作出规范化建议,旨在为我国OSA高危人群的筛查和管理提供切实可行的循证指导,以期达到减缓OSA疾病进展、降低合并症,提高生活质量和生存质量,降低OSA相关的交通事故、靶器官损害及医疗成本,为实现2030全民健康行动计划奠定基础。
# 第一部分 OSA概述

# 一、OSA的流行病学
当以 $\\mathrm{AHI}{\\geqslant}5\\,$ 次/h诊断OSA时,普通人群中OSA患病率为 $9\\%{\\sim}38\\%^{\\,[2]}$ 。然而,由于OSA的知晓率较低,其在人群中的真实患病率可能远高于此[3]。  

OSA与多种心血管疾病、代谢性疾病的发生发展密切相关。高血压、冠心病、心力衰竭和心房颤动等心血管疾病的患者中,OSA的患病率在 $40\\%\\mathrm{\\sim}$$80\\%^{\\left[4\\right]}$ 。约 $60\\%$ 的2型糖尿病住院患者合并$\\mathrm{OSA}^{[5-6]}$ 。肥胖是OSA的高危因素, $60\\%{\\sim}90\\%$ 的OSA患者伴肥胖,OSA在肥胖人群中的患病率约为$40\\%^{\\left[7\\right]}$ 。在接受减肥手术的人群中OSA患病率高达 $80.5\\%^{[8]}$  

国外数据显示,商用卡车司机中OSA的患病率为 $28\\%{\\sim}78\\%$ ,显著高于普通人群\"。基于多导睡眠图(polysomnography,PSG)诊断 $35\\%$ 的铁路工人患有 $\\mathrm{OSA^{[10]}}$ 。国内的一项调查研究显示,广州市货运司机鼾症患病率为 $37.3\\%$ ,OSA患病率为 $12.5\\%^{[11]}$  

OSA在不同人群中的高患病率提示应针对OSA高风险人群开展筛查及早期干预。
# 二、OSA 的疾病负担
由于对OSA及时诊治的缺失,大大增加了OSA相关性疾病的医疗和经济负担。2015年美国医疗系统OSA经济负担报道,由于对OSA严重程度的认识不足,可导致数百亿美元的经济损失!,其中直接经济损失包括高血压、糖尿病等合并症的长期治疗及OSA的嗜睡、疲劳等症状导致工作或交通事故等,间接经济损失包括由OSA症状导致的工作效率降低、缺勤、生活质量下降等。我国目前尚缺乏OSA相关医疗负担的数据,但OSA这一疾病带来的健康危害和经济损失不可忽视,必须引起足够的重视,亟待形成OSA早期管理的共识,尽早对OSA高危人群进行筛查和积极干预。  

三、OSA的筛查对象  

1.OSA高危人群:具有下列任何一项及以上的危险因素者,即为OSA高危人群:(1)性别[12}:中老年男性和绝经后女性;(2)具有典型OSA症状;(3)具有明显的OSA体征;(4)存在OSA相关合并12 15‐16 [ ]人群的特征见表 1[12,15-16]  

表1阻塞性睡眠呼吸暂停高危人群的特征  

注:如果存在日间嗜睡和以下3项标准中的2项:习惯性大声打鼾、呼吸暂停或喘息/室息、高血压,则为中重度OSA高危人群  

2.无症状OSA高危人群:即有以上OSA高危因素之一,但无典型的OSA相关的症状表现,或未意识到自己的症状而未主动就医的人群[17]。这类人群往往由于缺乏OSA典型症状,容易被忽视或漏诊,从而延误OSA诊治时机。然而,即使无症状,但其具有潜在的健康风险,因此不应被忽视[18-19]。尽管当前暂未有高质量的证据支持无症状OSA的全面筛查[\",但鉴于我国OSA患病群体庞大\",且人口老龄化加剧带来的OSA患病率进一步升高,预防和确诊严重不足的状况,筛查我国高危人群中无症状OSA将对疾病的防控起到积极作用。  

3.OSA危害大的人群:对某些职业人群,OSA除了个体健康影响,还会带来公共安全问题,如职业司机、飞行员、消防员、从事危险工作(如高空作业、伐木等)职业[20-21],这些人群均属于OSA筛查对象。此外,围手术期人群也是OSA筛查对象[22]  

【推荐意见1】建议对具有OSA典型症状、体征、相关合并疾病以及围手术期的OSA高危人群进行筛查。对不具备典型症状的和(或)自己未意识到OSA症状的高危人群也应进行筛查。对于一些OSA可能危及公共安全的职业人群,如职业司机、飞行员、消防员、从事危险工作(如高空作业、伐木等)均应进行OSA筛查。
# 第二部分 OSA的筛查工具和方法
一、筛查工具  

目前OSA筛查工具以量表和客观睡眠监测设备为主,各筛查工具的优缺点见表2。
# (一)睡眠量表
1.柏林问卷:该问卷包括3个类别。类别1包含夜间打鼾和呼吸暂停共5个问题;类别II有4个关于日间过度嗜睡的问题,其中1个是驾驶时嗜睡情况;类别III有2个问题,包括是否患有高血压或体质指数(body mass index,BMI) $>\\!30\\;\\mathrm{kg/m}^{2}$ 。如果有2个以上类别为阳性,则认为该个体为OSA高风险[23]。当使用 $\\mathrm{AHI}{\\geqslant}5\\,$ 次/h作为OSA诊断标准的截点时,柏林问卷灵敏度为 $76\\%$ ,特异度为 $45\\%$ ,诊断准确度为 $56\\%{\\sim}70\\%$ ,容易产生假阴性结果[24] 。此外,该筛查问卷条目较多,相对复杂。  

2.STOP-Bang问卷:该问卷是一种能有效预测中重度OSA的筛查工具,简单快捷、使用方便,具有较高的灵敏度,在外科术前筛查中广泛应用。该问卷共包括8个问题:响亮的鼾声、疲倦、可观察到的呼吸暂停、高血压、 $\\mathrm{BMI}{>}35\\;\\mathrm{kg}/\\mathrm{m}^{2}$ ,年龄 ${>}50$ 岁、颈围 ${>}40~\\mathrm{cm}$ 、男性。STOP-Bang问卷评分 $\\geqslant3$ 分则提示OSA 高危[12]。STOP-Bang 问卷作为 OSA 的筛查工具在不同地域、不同人种中得到广泛应用,包括普通人群[25]、睡眠门诊[26] 、术前筛查等多种场景。一项来自睡眠门诊的数据显示[2],STOP-Bang 问卷对AHI≥5次/h,15次/h和30次/h灵敏度分别为 $94.9\\%$ 、  

$96.5\\%$ 和 $97.7\\%$ ,且 STOP-Bang问卷评分越高,患重度OSA的可能性越大。对不同严重程度OSA诊断的灵敏度和诊断效能 STOP-Bang问卷优于柏林问卷[28]。但应注意的是,对于如心房颤动等合并OSA但嗜睡症状少见为特点的患者,STOP-Bang问卷诊断准确度较差,应谨慎使用[29]  

3.Epworth嗜睡 量表(Epworthsleepinessscales,ESS):ESS用于量化成人日间嗜睡的程度[30]。该量表内容简短,共8个问题,以0\\~3分的等级表示8项白天不同场景中打瞌睡的程度( $0{=}$ 从不, $1\\mathrm{=}$ 有时, ${2=}$ 经常, $3{=}$ 极易),计算8个问题的总得分,得分越高,表示日间嗜睡越严重。 $\\mathrm{ESS}{\\geqslant}9$ 分提示存在日间嗜睡。当使用 $\\mathrm{AHI}{\\geqslant}5\\,$ 次/h作为OSA诊断截点时,ESS诊断OSA灵敏度为 $27\\%{\\sim}72\\%$ ,特异度为 $50\\%{\\sim}76\\%$ ,准确度为 $51\\%{\\sim}59\\%^{[24]}$ 。值得注意的是,如果单独使用ESS量表来预测OSA的风险容易产生假阴性结果,因为相当多的OSA患者并没有日间嗜睡的主诉,而且OSA严重程度并不总与日间嗜睡程度呈正相关。ESS嗜睡量表单独筛查OSA的作用受限。  

【推荐意见2】建议将STOP-Bang问卷作为OSA常用筛查量表,不单独使用ESS量表。STOP-Bang问卷可用于体检机构、外科手术前、基层医疗机构、社区人群的高危OSA筛查。
# (二)睡眠监测工具
1.PSG:PSG是诊断OSA的金标准,但存在耗时费力、价格昂贵、专业技术要求高、等待检查时间长等问题。OSA高危人群的筛查更适宜采用简单易行、方便快捷、低成本的筛查手段。PSG多用于OSA筛查后确诊。对于筛查出的OSA高风险人群,若临床怀疑有其他睡眠障碍、神经肌肉疾病、充血性心力衰竭、呼吸系统疾病、阿片类药物使用、肥胖低通气综合征等严重伴发疾病时,首选PSG进行确诊。  

2.家庭睡眠呼吸暂停监测(home sleep apneatest,HSAT):HSAT包括II、III型的便携式睡眠监测,临床上用于高度怀疑中重度OSA的诊断[4]HSAT操作简便,费用较低,不受床位限制,较PSG对患者睡眠影响更小,无需技术人员值守,且具有较高灵敏度及特异度,也能在远程医疗中发挥重要作用[3]。III型设备是目前临床上在OSA诊断中应用最为广泛的HSAT设备。对于中重度OSA高危人群,可使用HSAT作为确诊手段。由于HSAT可能低估OSA的严重程度,若HSAT测试结果为阴性,高度怀疑OSA时,需PSG确诊。出于卫生经济学考虑,目前不推荐在无症状、无合并症大规模人群调查中使用HSAT进行OSA筛查,但在院内存在OSA高危因素的情况下可考虑使用HSAT进行OSA筛查和诊断[28]  

3.IV型睡眠监测:IV型睡眠监测采取持续单/双信号通道记录,可连续记录1或2个生理参数,最常采集的信号是脉搏血氧饱和度。IIV型睡眠监测是一种简单、客观的OSA筛查工具,更接近自然睡眠状态,故患者接受程度高,可及性强。国内一项将可疑OSA患者用IV型可穿戴式设备与PSG对比研究结果显示,这种单通道血氧饱和度IV型睡眠监测对OSA的诊断具有较好的灵敏度和特异度。以$\\mathrm{AHI}{\\geqslant}5\\,$ 次/h作为诊断标准,其对OSA诊断的灵敏度、特异度分别为 $93\\%\\,.77\\%$ ;当使用 $A H I\\!\\geq\\!15$ 次/h作为中重度OSA的诊断标准,灵敏度、特异度分别为 $92\\%\\,.89\\%^{[32]}$ 。有研究表明单独使用IV型睡眠监测设备监测的氧减指数,或联合STOP-Bang问卷在筛查 OSA中明显优于单独的STOP-Bang问卷,尤其AHI $\\mathrm{OSA}^{[33]}$ 。美国预防工作小组回顾了既往研究发现,虽然IV型睡眠监测设备在估计实际的AHI上存在不一致性,但总体上在诊断OSA方面通常是准确的[17]。IIV型睡眠监测设备小巧,便携,几乎不影响睡眠,可及性及可接受性较高,诊断能力低于III型设备,筛查价值大于诊断价值,因此在大规模人群的OSA筛查中具有巨大的潜力。  

【推荐意见3】推荐IIVV型睡眠监测设备单独或联合STOP-Bang问卷可用于体检机构、外科手术前、基层医疗机构、社区等高危OSA的筛查。不建议II、III型HSAT用于大样本人群的筛查。但可应用于存在OSA相关合并疾病的医院内OSA高危人群的筛查,包括但不局限于以下:难治性高血压、肺动脉高压、复发性心房颤动;存在纽约心脏病分级II\\~IIV级的心力衰竭、快慢综合征、病态窦房结综合征、室性心动过速、既往发生心源性猝死和卒中、2型糖尿病及胰岛素抵抗等患者[28]。推荐PSG作为OSA筛查后确诊工具。  

(三)消费者级别的睡眠监测设备  

近年来,一些消费者级别的睡眠监测设备,如移动应用程序、可穿戴设备、植人式平台、桌面或网站平台等被应用于睡眠结构以及OSA的自我评估。一些小样本研究验证了消费者级别的睡眠监测设备在OSA筛查中的作用。Behar等[34]报告了一个智能手机应用程序,该应用程序集成了体动、音频、光电容积描记,人口统计数据以及STOP-Bang问卷,通过机器学习算法,该应用程序正确区分中重度OSA患者的准确度为 $92.2\\%$ 。基于光电容积脉搏波的一款智能手表,与PSG对比,预测OSA(AHI>5次/h)的准确度为 $81.1\\%$ ,与HSAT对比预测中重度OSA( $\\mathrm{AHI}{\\geqslant}15$ 次/h)的准确度达 $87.9\\%^{[35]}$ 。与临床诊断级别睡眠监测设备不同,消费者级别的睡眠监测设备不需要医生处方,给消费者提供了便携的个体筛查机会,更受消费者的青睐。虽然上述消费者级别的睡眠监测设备在预测OSA方面与PSG有一定的一致性[3,但在不同应用场景下信号采集的准确度以及呼吸事件判读的准确度方面还需进一步临床验证[28。此外,需要进一步完善对其算法的研究以及设备的开发。  

【推荐意见4】一些经过充分临床验证的消费者级别的睡眠监测设备可用于OSA高风险人群的自我筛查,促进其就医。但其属于非医用个体筛查工具,不可替代医疗级睡眠监测诊断工具。  

二、筛查场景  

1.社区筛查:应提倡逐步推广社区OSA高危人群筛查,培训社区全科医生或睡眠专科医师,建立社区OSA筛查点及筛查路径。由受过培训的基层医师或护士使用筛查问卷,如STOP-Bang问卷或IIV型睡眠监测设备发现可疑OSA患者。筛查出的OSA高危患者,在有条件的基层医院即可进行确诊和治疗,无条件者需转诊至睡眠专科或睡眠医学中心进一步诊治。  

表2OSA各筛查工具的优缺点  

注:OSA为阻塞性睡眠呼吸暂停;ESS为Epworth嗜睡量表;PSG为多导睡眠图;HSAT为家庭睡眠呼吸暂停监测  

2.医院内筛查:医院内所有符合OSA高危因素的潜在OSA患者,均应进行OSA筛查,包括但不限于以下情况:(1)心脑血管疾病:难治性高血压、心房颤动、卒中、纽约心脏病分级II\\~IIVV级的心力衰竭、快慢综合征、病态窦房结综合征、室性心动过速、既往发生心源性猝死和卒中;(2)代谢性疾病:肥胖、2型糖尿病、多囊卵巢综合征、肢端肥大症、甲状腺功能减退;(3)术前:如减重手术、关节置换术、高危妊娠的产妇等;(4)静脉麻醉手术前,以及静脉麻醉进行胃肠镜等内镜检查前。建议以上相关科室建立OSA高危患者筛查管理流程。有条件的医院可使用HSAT或PSG睡眠监测工具对院内以上高危OSA患者进行筛查。无条件可先用STOP-Bang问卷或IV型睡眠监测工具进行初筛,筛出OSA高危患者应由睡眠呼吸诊疗专科进行确诊、规范治疗和随访。 S  

3.常规体检筛查:目前我国尚未将OSA筛查纳人常规体检项目。但由于OSA高患病率、低认知率及延误诊治带来的疾病负担,建议逐步推广在常规体检项目中纳人OSA高危人群筛查,并在体检报告中给予OSA高危提示,作为进一步专科诊治或转诊的依据。筛查工具可选量表或IIV型睡眠监测工具。  

4.特殊职业人群的筛查:研究显示,未治疗的OSA驾驶员发生交通事故是非OSA驾驶员的3.43倍。制定全面的OSA筛查、诊治方案,可将交通事故减少 $73\\%^{\\mathrm{[9]}}$ 。特殊职业人群OSA筛查的对象主要包括职业司机、飞行员、消防员、从事危险工作(如高空作业、伐木等)的人群。在特殊职业人群中,出于特殊职业安全性考虑,不建议将主观的症状报告作为筛查OSA高风险依据。可通过III~IV型睡眠监测工具进行OSA筛查,对筛查阴性而高度怀疑OSA或怀疑合并其他睡眠障碍的职业人群可使用PSG进行确诊。  

5.非特殊职业人群的筛查:对于非特殊职业人群,未及时诊治的OSA也可能导致工作效率低下、缺勤以及生产力下降等。可将OSA筛查纳人单位职工常规年度体检项目。国内一项研究对1036例公务员职业人群先进行柏林问卷筛查(其中 $22.0\\%$阳性),之后通过III型睡眠监测进行OSA确诊,103例得到明确诊断,这些患者绝大多数之前未诊断过OSA[37]。对于一次性大样本职业体检人群,可以先用睡眠问卷筛查再使用睡眠监测工具确诊。实践证明,这种有组织地对职业人群如公务员人群进行OSA高危人群筛查可以主动发现从未诊治过的OSA以及OSA相关性高血压,对积极干预者的观察发现有一定的获益[38]  

6.妊娠期OSA的筛查:妊娠期的体重增加和伴随的生理变化,如上气道黏膜充血、口咽部直径变窄、功能残气量下降和耗氧量增加等,可导致或加重 $\\mathrm{OSA}^{[39]}$ OSA OSA$56.1\\%^{[40]}$ ,在合并妊娠高血压、先兆子痫、糖尿病孕妇人群中OSA更为常见[39]。患有OSA的孕妇发病率和死亡率增加,且对胎儿造成诸多不良影响,增加早产、低出生体重儿等的风险[39,4]。对妊娠期OSA的筛查尤为重要。处于妊娠期且伴有OSA高危人群特征提示需要进行OSA筛查。建议在孕12\\~18周之间进行0SA筛查,以便在妊娠早期有足够的时间进行评估和早期治疗[39]。由于受多种因素的影响,目前常用的OSA筛查问卷,如STOP-Bang问卷、柏林问卷多针对一般人群,在孕妇中的应用相对受限。HSAT正成为一种可靠、方便且具有成本效益的筛查高危孕妇OSA患者的方法[39]。  

【推荐意见5】推荐在社区、医院内非睡眠专科、体检中心、各种职业人群、妊娠期等多场景下,采用推荐的合适的工具进行OSA高危人群的筛查。
# 第三部分OSA筛查机构与流程

# 一、筛查人员与机构
在目前睡眠专科缺少、医技人员缺乏的情况下,逐步培训具备OSA筛查能力的人员,完善具备筛查能力的机构。并鼓励采用各种宣传方式和途径,向公众传播OSA的疾病防治知识,提高公众对OSA的识别意识和就诊积极性。  

1.基层医疗机构:基层医疗机构是OSA防治的首道防线。应初步完善包括村卫生室、乡镇卫生院、社区卫生服务中心、县级及县级以下医院的OSA识别和筛查能力。在常规健康管理和公共卫生工作中应主动开展OSA风险筛查,及时发现OSA高危人群。包括初步完善人员培训制度,建立OSA筛查点及筛查路径,完善OSA慢病管理体系。  

2.医院:OSA高危人群往往分布于医院的呼吸科、心内科、内分泌科、肾内科、老年医学科、神经精神科、耳鼻喉科及外科等各个科室。需要提高相关科室医务人员的OSA风险筛查意识,对OSA高危人群开展初步的评估,必要时建议专科就诊。  

3.体检中心:建议有条件的体检中心在常规体检中开展OSA高危人群筛查和在体检结果中报告OSA高危,对明确的OSA高危人群建议专科就诊。  

4.自我筛查:积极推广各种形式的科普和义诊提高公众对OSA疾病的认知度和自我识别能力,包括不限于讲座、网络媒体、画册、社区宣传栏等各种形式的宣传活动,以促使患者自我筛查及主动就医。  

【推荐意见6】建议逐步完善基层医疗机构、医院内相关科室、体检中心等机构人员对OSA的筛查意识和筛查能力。建议通过各种科普宣传活动提高公众对OSA的认知度和自我筛查意识。  

二、OSA高危人群筛查与管理流程(图1)  

在社区、医院内非睡眠专科、体检中心、各种职业人群、妊娠期等多场景下的OSA高危人群,可因地制宜地通过 STOP-Bang 问卷、IV型睡眠监测、  

HSAT或PSG进行初筛或诊断。对于STOP-Bang问卷评分 $\\geqslant3$ 分或IV型睡眠监测测试异常的高危人群,若疑为单纯中重度OSA,且不合并以下情况:(1)严重的心肺疾病;(2)神经肌肉疾病导致的呼吸肌无力;(3)清醒低通气或睡眠相关低通气风险;(4)慢性阿片类药物的使用;(5)卒中史;(6)严重失眠;(7)怀疑其他睡眠障碍,则推荐使用HSAT进行确诊,否则需至专业睡眠中心行整夜PSG监测明确诊断。对于确诊的OSA患者采取个体化的管理模式。
# 第四部分OSA高危人群的管理
由于OSA的高患病率以及与导致发病率和死亡显著增高的多种疾病关联,对OSA的确诊和管理是OSA高危人群筛查后的重要任务。OSA高危人群筛查后管理包括诊断后OSA患者管理和具OSA高危因素的人群管理。睡眠呼吸专科或睡眠中心的医技人员必须具备对OSA全面的管理能力,包括患者的评估、治疗方案的制定。熟练掌握包括生活方式指导、睡眠卫生教育、气道正压通气(positiveairwaypressure,PAP)治疗与随访等方法。  

一、生活方式改变  

与大多数慢性病一样,生活方式干预是OSA管理的重要措施。  

1.减重:超重/肥胖是OSA常见且可逆的风险因素。以媒体、宣传册等形式让患者了解肥胖的危害。建议对超重/肥胖的OSA患者进行全面的生活方式干预,包括低热量饮食、运动或增加体力活动以及行为干预。低热量饮食可根据患者的喜好定制饮食谱,以提高依从性,减少热量的摄入。运动可以独立于体重减轻而改善OSA[\"5]以及相关健康结局,建议每周至少进行 $150\\;\\mathrm{min}$ 的中等强度的有氧运动。  

注:OSA为阻塞性睡眠呼吸暂停;HSAT为家庭睡眠呼吸暂停监测;PSG为多导睡眠图;CBTI为失眠认知行为治疗;BBTI为失眠简明行为治疗;PAP为气道正压通气  

2.睡眠卫生:改善睡眠卫生可能缓解OSA相关的症状。良好的睡眠卫生包括建立规律的睡眠、保持充足的睡眠;睡前限制饮酒和含咖啡因的饮料,适当运动、合理膳食、避免睡前情绪激动以及保持卧室舒适的睡眠环境等[42]。  

3.危险因素控制:戒烟戒酒及慎用镇静安眠类药物。  

4.共病失眠的治疗:共病失眠的OSA患者,有条件的情况下推荐失眠认知行为治疗(cognitivebehavioral therapy for insomnia,CBTI)。CBTI 内容包括刺激控制、睡眠限制、放松训练、认知疗法、睡眠卫生教育,能缓解人睡困难,增加总睡眠时间,改善睡眠质量,并可长期维持疗效。若无法完成CBTI,可使用失眠简明行为治疗(brief behavioraltreatment forinsomnia,BBTI),特别是在门诊和社区场景下。BBTI选取了CBTI最核心、最有效的行为干预组分睡眠限制和刺激控制[4],在改善失眠的同时可缩短治疗时长。
# 二、OSA确诊患者的治疗
1.PAP:PAP是OSA的一线治疗手段。PAP治疗应基于客观睡眠监测明确诊断的OSA患者。依从性是影响治疗效果的主要因素,PAP治疗使用时间越长,患者获益越大。配合减重、改变不良生活习惯等,治疗效果更明显。  

2.口腔矫治器:对于不能耐受PAP,或不愿使用PAP的轻中度OSA患者,可选择口腔矫治器治疗。  

3.体位治疗:体位疗法包括佩戴绑在背部的网球,背包或泡沫装置等,以最大程度地减少仰卧位的睡眠时间,可减轻部分患者OSA严重程度,适合体位性OSA。  

4.外科手术:部分患者可能适合手术,包括扁桃体肥大等或需要下颌前移的明显下颌后缩的患者44,需严格掌握手术适应证。对于 $\\mathrm{BMI}{\\geqslant}35\\;\\mathrm{kg}/\\mathrm{m}^{2}$ 的病态肥胖的OSA患者,尽管采取了全面的生活方式干预减重,效果不明显,可转诊进行外科减重手术评估[45] 。  

5.药物:目前尚缺乏对治疗OSA具有明确疗效的药物[15]
# 三、随访管理
对明确诊断并接受PAP治疗的OSA患者,建议在睡眠医学专科或已开展睡眠诊疗的基层医疗机构进行定期随访。分别在PAP使用的1\\~2周,1、3、6个月及以后每年1次进行随访。在0SA患者PAP初始治疗阶段进行门诊或远程监测和随访,包括监测症状改善、治疗依从性、残余AHI、漏气量、呼吸事件及调整治疗参数等[46]  

非PAP治疗的OSA患者,如口腔矫治器,外科手术等,在相应科室进行随访同时,需定期在睡眠医学专科诊疗中心随访监测治疗效果。  

对于明确诊断但不接受治疗的OSA患者或拒绝明确诊断的OSA高危患者,可由相应的筛查机构给予生活方式教育及危险因素控制指导。给予可能的疾病进展迹象提示,如OSA相关症状加重、出现合并症等情况时及时就诊。  

【推荐意见7】对筛查出来的OSA高危人群,推荐到正规医疗机构的睡眠中心进行HSAT或PSG以确诊和进行规范管理。OSA高危人群和确诊患者均需强调全面生活方式干预的重要性,包括减重、睡眠卫生教育、戒烟戒酒及慎用镇静安眠类药物等。共病失眠的OSA患者,有条件的情况下推荐CBTI治疗失眠,若无法完成CBTI,特别是在门诊和社区场景下,可使用BBTI作为失眠治疗手段。基于患者意愿,推荐明确诊断的OSA患者PAP作为优先选择,可替代治疗方案包括口腔矫治器、体位治疗、外科手术等。对于来源于不同筛查机构,采取不同的治疗方式的OSA患者,制定适宜的、规范的随访制度,及时发现疾病进展,定期评估干预效果。
# 第五部分 OS小A结与展望
随着肥胖的流行、OSA患病率的升高,中国OSA疾病负担日益沉重,给公共卫生带来重大挑战。进行OSA的早期筛查及管理,对于减少医疗支出,提高全民健康水平具有重要的战略意义。  

STOP-Bang问卷简单、可操作性强,仍是人群筛查的优选方式。在诊断设备及经济条件允许的情况下,可采用III\\~IV型睡眠监测工具进行OSA高危人群筛查。随着科技的发展,各种消费级的睡眠监测工具受到消费者的青睐,一些经过充分临床验证的消费级睡眠监测工具可用于OSA高危人群自我筛查,但筛查后的OSA确诊必须由医疗机构采用医用级睡眠监测设备完成。对来源于不同筛查机构的OSA高危患者应进行专科规范化综合管理,包括明确诊断和评估、个体化治疗、长期随访。随着我国OSA筛查工作的开展和推广,未来,来自我国OSA的临床实践和研究结果将进一步推动该共识的更新,更好地指导我国OSA的防治和规范化管理。

"""
response = """
// 节点更新
MERGE (n:Disease {name: '阻塞性睡眠呼吸暂停'})
SET 
    n.description = coalesce(n.description, '一种常见的睡眠呼吸疾病'),
    n.severity = coalesce(n.severity, '中等');

MERGE (n:Symptom {name: '呼吸暂停'})
SET 
    n.description = coalesce(n.description, '睡眠期间发生的呼吸停止现象'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '频繁');

MERGE (n:Symptom {name: '日间嗜睡'})
SET 
    n.description = coalesce(n.description, '白天感到过度困倦'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '打鼾'})
SET 
    n.description = coalesce(n.description, '夜间睡眠时发出声响'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '疲劳'})
SET 
    n.description = coalesce(n.description, '白天感到疲乏无力'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Examination {name: '多导睡眠图'})
SET 
    n.description = coalesce(n.description, '用于诊断OSA的金标准'),
    n.method = coalesce(n.method, '多导睡眠监测'),
    n.requirement = coalesce(n.requirement, '在医院进行');

MERGE (n:Examination {name: '家庭睡眠呼吸暂停监测'})
SET 
    n.description = coalesce(n.description, '用于中重度OSA的便携式监测'),
    n.method = coalesce(n.method, '便携式睡眠监测'),
    n.requirement = coalesce(n.requirement, '在家中进行');

// 关系更新
MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停'
MATCH (to) WHERE to.name = '呼吸暂停'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.95),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停'
MATCH (to) WHERE to.name = '日间嗜睡'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停'
MATCH (to) WHERE to.name = '打鼾'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.85),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停'
MATCH (to) WHERE to.name = '疲劳'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.8),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停'
MATCH (to) WHERE to.name = '多导睡眠图'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '高'),
    r.mandatory = coalesce(r.mandatory, 'true');

MATCH (from) WHERE from.name = '阻塞性睡眠呼吸暂停'
MATCH (to) WHERE to.name = '家庭睡眠呼吸暂停监测'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '中'),
    r.mandatory = coalesce(r.mandatory, 'false');

"""
