[metadata]
file_name = "特发性过度睡眠：一类不容忽视的睡眠障碍.md"
processed_at = "2024-12-19 00:12:18"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-19 00:09:02"
message = """

[隶属文件名]
特发性过度睡眠：一类不容忽视的睡眠障碍.md
[隶属文件分块名]
特发性过度睡眠：一类不容忽视的睡眠障碍/001-完整文档.md
[文本块]
# 特发性过度睡眠:一类不容忽视的 睡眠障碍
宿长军'赵忠新2  
1空军军医大学第二附属医院神经内科,西安710038;2海军军医大学第二附属医院  
神经内科,上海200003  
通信作者:赵忠新,Email:neuzhaozx@163.com  

【摘要】特发性过度睡眠(IH)是一种慢性中枢性嗜睡疾病,主要表现为尽管睡眠时间正常或延长,但白天仍会出现过度嗜睡。由于疾病个体异质性、临床症状重叠性高、多导睡眠监测结果重复性差及缺乏明确生物标志物,造成诊断与鉴别诊断困难。本文总结IH的诊断标准更新、临床表现、诊断及治疗策略更新,以期能够得到重视,增加临床诊断识别率、减少误诊率及漏诊率。  

【关键词】睡眠障碍;特发性过度睡眠;长时程多导睡眠监测;低钠羟丁酸  

特发性过度睡眠(idiopathic hypersomnia,IH)是一种慢性中枢性过度睡眠疾病。早在20世纪50年代末,BedrichRoth首先描述了一种以日间过度思睡、睡眠时间延长和醉酒样睡眠为特征的综合征,且不伴睡眠发作、猝倒发作、睡眠瘫痪和睡眠幻觉,病情程度可呈波动性,多达1/3的患者可出现自发缓解[]。  患病率为 $0.02\\%o{\\sim}0.05\\%o$ ,发病年龄通常在10\\~30岁之间,平均发病年龄为17岁,男女患病率近似。由于缺乏系统的研究,IH的确切流行率和发病率仍未知。IH可导致生活质量下降、多认知域功能受损及工作/学习效率下降等不良结局。目前由于IH的神经生物学机制尚不清楚,缺乏明确生物标志物和有效的辅助诊断工具,其疾病诊断、鉴别诊断及治疗仍需要重新认识与提高。  

一、诊断标准的更新  

IH最早在19世纪70年代首次被报道,并于1990年纳入第一版的睡眠障碍国际分类(ICSD-1)。2005年,《睡眠障碍国际分类》第二版(ICSD-2)明确将IH分为伴夜间长睡眠 $(>\\!10\\,\\mathrm{h})$ 和不伴夜间长睡眠( $6~\\mathrm{h}<$ 夜间睡眠 $<\\!10\\,\\mathrm{h}$ )[4]。但在2014年的《睡眠障碍国际分类》第三版(ICSD-3)中并未强调这一区别[5]。在2023年的最新《睡眠障碍国际分类》第三版-修订版(ICSD-3-TR)中新增加一条诊断标准,即多导睡眠监测(polysomnography,PSG)和多次睡眠潜伏期测试(multiple sleep latency test,MSLT)结果不符合发作性睡病型或2型0[2]3。  

IH的诊断需要进行详细的临床问诊及客观的睡眠监测进行综合评估。2023年ICSD-3-TR 的诊断标准6要求必须满足:(1)病程持续至少3个月每日出现难以控制的困倦欲睡或非预期性入睡;(2)无猝倒发作;PSG和MSLT结果不符合发作性睡病1型或2型;(3)MSLT提示睡眠始发快速眼动期次数(SOREMP)少于2次,或前夜PSG中如果快速眼动(rapid eye movement,REM)睡眠潜伏期 $\\leqslant$$15~\\mathrm{min}$ 时,则MSLT中无SOREMP;(4)至少出现以下一项: $\\textcircled{\\scriptsize{1}}$ MSLT中平均睡眠潜伏期 $\\leqslant8\\ \\mathrm{min}$ $\\textcircled{2}24\\,\\mathrm{h}$PSG或腕式体动记录仪结合睡眠日志证实总睡眠时间 ${\\geq}660~\\mathrm{min}$ (典型IH为 $12{\\sim}14\\mathrm{\\;h}\\,.$ );(5)排除睡眠不足综合征(必要时可通过延长夜间睡眠时长观察思睡改善情况,最好通过至少1周的腕式体动记录仪证实);(6)日间思睡和(或)MSLT结果不能被睡眠不足、阻塞性睡眠呼吸暂停(obstructive sleepapnea,OSA)、睡眠觉醒时相延迟障碍、药物/物质使用/撤药等其他原因解释。
# 二、临床表现
IH主要表现为夜间睡眠时间延长(成人患者典型睡眠时间为 $10\\;\\mathrm{{h}}$ 以上,儿童患者为多于其正常年龄段睡眠 $2\\;\\mathrm{{h}}$ 以上),日间小睡时间长(通常1h以上)且醒后无恢复感,睡眠惯性/醉酒样睡眠(表现为难以从整夜睡眠或日间小睡后快速醒来)[3]。其中 $78\\%$ 的IH患者呈现为轻度睡眠惯性[7-9], $36\\%$ 的IH患者睡眠惯性较为严重[7且与睡眠时长[10]无关(难以醒来,随时很可能再次入睡)。IH患者在晨起睡眠惰性消失后通常能够全天保持清醒,但昏昏欲睡感和脑雾症状会持续存在(如记忆力减退、注意力不集中、常忘记事情、头脑“空白感”)[7-8],且小睡后可再次出现睡眠惰性。客观长睡眠( $24\\,\\mathrm{{h}}$ 监测内 $11\\;\\mathrm{{h}}$ 或 $32\\;\\mathrm{h}$ 监测内 $^{19\\mathrm{~h~}}$ 以上睡眠)较为常见[6,11],既往研究中 $30\\%{\\sim}50\\%$ 的 IH患者睡眠时长≥$10\\;\\mathrm{{h}}$ ,但客观长睡眠的流行病学可能被低估,因为大7多数睡眠中心无3 法h完成长时程 []。等”发现,IH患者在周末和节假日较工作日的夜间睡眠时间平均延长 $3\\textrm{h}$ 以上,在排除了睡眠不足综合征等原因之后,提示这些特定情况下的长睡眠支持IH的诊断[13]。IH患者在睡眠发作时常有自动行为/不恰当行为,而睡眠幻觉和睡眠瘫痪很少见,这些与发作性睡病不同,但有些患者的症状可能与发作性睡病重叠,比如表现出难以抑制的短暂的睡眠发作、醒后精力充沛的现象。此外,抑郁症状、头痛(偏头痛和紧张型头痛)也有报道,甚至伴有自主神经功能紊乱相关症状(如心悸、直立性低血压、四肢末端发冷等)。
# IH

# (一)鉴别诊断
IH的诊断实际上属于排除诊断,诊断难处不仅在于与其他中枢性思睡类疾病难鉴别,更是由于疾病临床症状的交叉重叠性高、监测结果重复性差,难以排除继发于神经疾病、精神疾病或其他系统疾病等复杂因素[]。日间过度思睡也可non见‐r于api其d他睡眠障碍,如OSA、发作性睡病、睡眠不足综合征、睡眠觉醒时相延迟障碍、非快速眼动(non-rapideye movement,NREM)异态睡眠等。尤其是2型发作性睡病与IH最难鉴别,从思睡严重程度常难以区分开(既往报道IH的平均Epworth嗜睡量表评分为14.1\\~17.9分,2型发作性睡病为14.5\\~16.7分,型发作性睡病为 $16.6{\\sim}18.5$ 分)[, ]。  患者更为突出的表现是整日感觉困倦/思睡、长时间小睡后无恢复感但尚可保持清醒,但是发作性睡病患者短暂小睡后即可有恢复感,且经常表现为突然出现的不可克制的不分场合的瞌睡发作。此外也要注意肥胖患者,即使不共病OSA,肥胖也可能导致内分泌代谢性疾病和(或)昼夜节律异常,从而出现日间过度思睡和夜间长睡眠。  

(二)客观睡眠监测  

常规PSG通常显示患者的NREM睡眠和REM睡眠比例基本正常,REM睡眠潜伏期正常,总睡眠时间常延长。当前的ICSD-3-TR的诊断标准中依然强调 $24\\mathrm{~h~PSG}$ 或腕式体动记录仪结合睡眠日志证实总睡眠时间 ${\\geq}660~\\mathrm{min}$ ,但并未有详细标准化的流程,也并未考虑可能影响总睡眠时间的因素(如年龄)。目前有研究报道可进行长时程的客观睡眠监测,包括 $48\\;\\mathrm{h}$ 监测(整夜PSG,次日MSLT及包含一整夜4的8 $18{\\sim}20\\;\\mathrm{h}$ 第 次 )[,M]S、 $32\\;\\mathrm{h}$ 8监测(整夜PSG,次日 MSLT及第 2次整夜 PSG)[11,18]和 $^\\mathrm{60\\h}$ 监测(前 $48\\;\\mathrm{h}$ 为  监测,之后为 )[ ]。上述方案均可在任何国家或地区开展,但由于多为欧盟国家创立,因此监测结果解释可能不一致,存在一定的局限性,如并未强调卧床时间、体力活动情况、光照情况及缺少与健康对照组对比后的诊断灵敏度和特异度等。  

尽管2014年ICSD-3及2023年ICSD-3-TR仍以$24\\,\\mathrm{{h}}$ 监测时长为诊断标准的主要参考,但是在2020年欧洲学者Lammers等[20]对诊断标准提出修改,建议分类为:(1)明确的IH:客观检查满足2周的睡眠日记结合体动记录仪显示每晚 $^{9\\textrm{h}}$ 以上睡眠和 $24~\\mathrm{h}$ PSG显示 $^\\mathrm{10}\\,\\mathrm{h}$ 以上睡眠,或 $32~\\mathrm{h}$ PSG显示$19\\,\\mathrm{h}$ 以上的睡眠[\"];(2)可能的IH:客观检查满足2周的睡眠日记结合体动记录仪显示每晚 $^{9\\textrm{h}}$ 以上睡眠,但是不满足明确的IH的 PSG标准。同时建议无论是明确的还是可能的IH,夜间睡眠效率均达到 $85\\%$ 以上作为参考;如果测定脑脊液下丘脑食欲素-1,其值应在正常范围内。临床上需要注意的是,在行常规的诊断监测前建议延长夜间睡眠时间,便于排除正常变异型的长睡眠者,因为长睡眠者在满足夜间睡眠后日间过度思睡会明显改善,且醒后有恢复感。由于在长夜间睡眠时长的IH患者中,MSLT多为正常且MSLT重测结果的一致性较差,因此长夜间睡眠时长可能是更为可靠的诊断特征。  

IH患者的MSLT中平均睡眠潜伏期通常缩短,但长于大部分发作性睡病患者。此外,MSLT在中枢性过度睡眠疾病中,尤其是在IH患者中,其结果的重复性较低。2017年的一项97例中枢性过度睡眠疾病人群的回顾性研究中,首次MSLT后仅有$25\\%$ 的IH患者在第2次MSLT时仍满足IH的诊断标准[21];另外一项回顾性研究中,发现已满足MSLT诊断标准的 $30\\%$ 的IH患者经再次MSLT后达到2 型发作性睡病的诊断标准[22]。上述 MSLT检测结果较低的重复性可以用MSLT的内在特征或IH和2型发作性睡病的本身症状波动来解释,这也提示两种中枢性过度睡眠疾病之间可能存在表型重叠。上述结果也表明,以MSLT的平均睡眠潜伏期>$8~\\mathrm{min}$ 或总睡眠时间 $\\geqslant\\!11\\;\\mathrm{h}$ 为界值可能不足以确诊IH,因此在临床上疑诊IH但是不满足诊断标准的患者需要重新监测。此外,MSLT中可用于中枢性过度睡眠疾病鉴别的指标除了平均睡眠潜伏期和SOREMP之外,REM睡眠潜伏期、REM睡眠时长和睡眠分期转换等参数也可作为参考指标[23-25]
# (三)主观测评工具
目前对于IH与其他睡眠障碍的相关症状的评估/鉴别仍然缺少有效的主观评估工具。目前使用的测评工具主要是仅针对日间过度思睡或是其他思睡相关疾病的评估(发作性睡病或OSA),如Epworth嗜睡量表和清醒维持试验。其他IH相关症状(如睡眠惰性、夜间睡眠时间过长及认知障碍等)在临床研究中很少进行评估,主要是由于在IH人群中缺乏有效的评估工具。其中睡眠惰性问卷(SleepInertia Questionnaire,SIQ)仅在抑郁症中得到验证,主要用于自我评估睡眠-觉醒状态的生理、认知、情绪和行为,也用于过度思睡的评估[26-27] 。临床研究中使用了两种未经验证的量表来评估睡眠惯性,其中一个是针对睡眠惯性的治疗疗效的评估,由患者和医师共同评估,范围从0分(完全没有改善)到3分(明显改善)。另一个是使用视觉模拟评分量表进行评估,受试者晨起自评每天早上清醒维持困难,范围从0分(非常容易)到100分(非常困难)。过度思睡严重程度指数(HSI)属于患者自评工具,用于评估过度思睡症状和相关的功能受损情况,在中枢性思睡障碍患者的混合人群中得到验证,包括发作性睡病、 和与精神疾病相Id关iop的a[thic]过度睡眠。  

特发性过度睡眠严重程度量表(IdiopathicHypersomnia Severity Scale, IHSS)[30-31] 是-种 自评疾病临床严重程度的工具,涵盖14个问题,主要为疾病主要症状:夜间睡眠症状和相关睡眠惰性(5项)、日间思睡和相关睡眠惰性(4项),以及日间功能受损情况(5项)。每个项目的得分从0分到3或4分,综合得分从0分到50分(得分越高,程度越重)。健康对照组的平均IHSS总分为10分,IHSS总分界值22分是区分IH和健康对照的最佳临界值[3]。疾病严重程度类别根据 IHSS总评分定义如下:0\\~12分为轻度;13\\~25分为中度;26\\~38分为严重;39\\~50分为非常严重。IHSS有几个优点:它在IH 中得到验证,在经过治疗[30-3]和未经治疗的大样本人群中经过验证,具有较好的特异度和可靠性,也常用于IH的临床随机双盲对照试验中。  

此外,精神运动警觉性测试(PsychomotorVigilanceTask,PVT)是一种较为简单的5或 $10\\;\\mathrm{min}$的评估,多用于测定健康人群睡眠剥夺和睡眠限制后的反应性/警觉性。既往几项研究证实PVT可作为1型发作性睡病、2型发作性睡病和主观日间过度思睡的鉴别诊断和治疗效果评估的重要辅助手段[ ]。近期一项关于通过  评估中枢性过度睡眠中的警觉性和睡眠惯性来作为中枢性过度睡眠的辅助诊断的研究结果显示,无论基线还是小睡试验后应用PVT都具备较好的鉴别诊断价值,同时提出PVT和MSLT分别是思睡和警觉性两个不同方面的评估,是相互补充而非重复测试[3]。  

四、治疗  

治疗目标主要是维持正常日间功能,包括降低伴或不伴夜间长睡眠IH患者日间思睡程度,减少夜间睡眠时长,提高正常起床后维持清醒能力及驾驶安全,改善注意力和认知等。IH的治疗包括药物和非药物治疗。  

(一)非药物治疗  

非药物治疗包括健康教育如对疾病症状、严重程度、病程和转归的认识,规律小睡(如果醒后有恢复感),良好睡眠卫生;认知行为治疗,避免过度黑暗环境(如可以使用光照疗法改善季节性光照不足),晨起独特唤醒策略(如特殊闹铃等),晨起后增加警觉性方案(如自然醒来后 $30\\;\\mathrm{min}$ 快速光暴露疗法、咖啡因、淋雨或体育锻炼等)。对于伴夜间长睡眠时长的IH患者,应避免睡眠剥夺。尽管上述非药物治疗对疾病的疗效尚无充足证据,但未见不良反应。
# (二)药物治疗
近期法国指南[36]和美国睡眠医学会指南[3]中均推荐莫达非尼作为一线治疗药物或强推荐药物。其他药物包括哌甲酯和安非他明、克拉霉素、氟马西尼、马吲哚、替洛利生和羟丁酸钠均属于弱推荐用药。临床上莫达非尼治疗IH的日间过度思睡疗效尚可且安全性较好,但相比于伴长夜间睡眠患者,莫达非尼和安非他明可能对不伴长夜间睡眠患者更有效。  

低钠羟丁酸具有独特的阳离子构成(钙、镁、钾、钠),其钠含量比羟丁酸钠少 $92\\%$ (如羟丁酸钠每晚推荐剂量为 $6{\\sim}9\\ \\mathrm{g}$ 的范围内,钠含量则减少$1\\ 013{\\sim}1\\ 509\\ \\mathrm{mg}$ )。2020年由美国食品药品监督管理局(FDA)批准用于治疗7岁及以上发作性睡病患者的猝倒或日间过度思睡[ ]。 3 8‐4年0,低钠羟丁酸被美国FDA批准用于治疗成人 $\\mathrm{IH}^{[38-40]}$ IH关于低钠羟丁酸的标准化剂量和治疗方案尚未确定,如目前无法明确对于伴夜间长睡眠者的IH是每晚1次还是每晚2次的用药方案更好,且其滴定疗效可能需要数周/数月观察才得知。而对于不伴夜间长睡眠的患者,用药方案与发作性睡病治疗类似,即 $3.0{\\sim}4.5~\\mathrm{g/}$ 晚小剂量起始逐渐滴定到所需剂量。由于低钠羟丁酸的钠含量明显较低,因此羟丁酸钠通常比低钠羟丁酸更适用于共病低血压、自主神经紊乱或其他建议增加盐摄入量的情况。  

此外,IH药物治疗时需要注意的是共病和药物不良反应,如莫达非尼、替洛利生、低钠羟丁酸、羟丁酸钠、哌甲酯和安非他明可能加重抑郁症状,罕见可诱发抑郁症状。尤其是低钠羟丁酸可能导致中枢神经系统相关的不良反应,如癫痫、呼吸抑制、意识水平下降、昏迷和死亡,因此,对于有药物滥用史、抑郁症或自杀企图的患者,低钠羟丁酸可能并不适合。_对于无OSA的肥胖型IH患者可选择低钠羟丁酸,不仅可改善思睡,也可有助于减重[4]。对于有心血管疾病病史的患者,兴奋类药物应谨慎使用。羟丁酸钠对心力衰竭、高血压、肾功能损害或其他对钠敏感的疾病的高钠患者慎用。但是低钠羟丁酸未提到上述情况下慎用,使用时应酌情应用于心血管疾病患者。  

综上,IH属于一种异质性疾病,个体症状严重程度不同,治疗上需要根据临床表现(尤其是夜间的长睡眠和日间严重的睡眠惰性)共病及生活方式等进行综合治疗。
# 五、展望
目前对IH的认识仍有不足,无论是临床症状与其他过度睡眠疾病的交叉重叠性高、客观监测结果的重复性差,还是缺少明确的生物学标志物,都导致疾病在诊断和鉴别诊断方面存在一定困难。疾病评估时应使用经过严格验证的量表,如特发性过度睡眠严重程度量表。此外,未来智能可穿戴设备可能会用于疾病长期随访观察,尤其是药物治疗滴定方案的进一步明确。药物治疗上,应该开展严格的临床研究,尤其是关于低羟丁酸钠等药物治疗启动时间和具体剂量的方案。同时,疾病的不同表型需要进一步探索,如根据疾病的严重程度(如白天过度睡眠、长睡眠时间及睡眠惰性等)、年龄和共病情况(如抑郁、心血管疾病史)等进行分型,将有

"""
response = """
// 节点更新
MERGE (n:Disease {name: '特发性过度睡眠'})
SET 
    n.code = coalesce(n.code, 'IH'),
    n.description = coalesce(n.description, '一种慢性中枢性嗜睡疾病，主要表现为正常或延长的睡眠时间但白天过度嗜睡。'),
    n.category = coalesce(n.category, '睡眠障碍'),
    n.severity = coalesce(n.severity, '中度');

MERGE (n:Symptom {name: '过度嗜睡'})
SET 
    n.description = coalesce(n.description, '尽管睡眠时间正常或延长，白天仍会出现过度嗜睡。'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '睡眠惰性'})
SET 
    n.description = coalesce(n.description, '醒后难以快速清醒，类似醉酒样的感觉。'),
    n.severity = coalesce(n.severity, '中度'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '认知功能障碍'})
SET 
    n.description = coalesce(n.description, '包括记忆力减退、注意力不集中和常忘记事情。'),
    n.severity = coalesce(n.severity, '轻度'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:NonDrugTreatment {name: '认知行为治疗'})
SET 
    n.description = coalesce(n.description, '通过心理干预改善患者对疾病的认识和应对能力。'),
    n.duration = coalesce(n.duration, '长期'),
    n.frequency = coalesce(n.frequency, '根据需要'),
    n.contraindication = coalesce(n.contraindication, '无'),
    n.equipment = coalesce(n.equipment, '光照疗法设备');

MERGE (n:NonDrugTreatment {name: '健康教育'})
SET 
    n.description = coalesce(n.description, '对患者进行疾病知识和健康指导。'),
    n.duration = coalesce(n.duration, '长期'),
    n.frequency = coalesce(n.frequency, '定期'),
    n.contraindication = coalesce(n.contraindication, '无'),
    n.equipment = coalesce(n.equipment, '无');

MERGE (n:Complication {name: '抑郁症状'})
SET 
    n.description = coalesce(n.description, '患者可能出现抑郁相关的情绪变化。'),
    n.severity = coalesce(n.severity, '严重');

MERGE (n:Complication {name: '头痛'})
SET 
    n.description = coalesce(n.description, '常见的伴随症状，可能是偏头痛或紧张型头痛。'),
    n.severity = coalesce(n.severity, '中度');

// 关系更新
MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = '过度嗜睡'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.8),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = '睡眠惰性'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.7),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中度');

MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = '认知功能障碍'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.6),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '轻度');

MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = 'e1'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '高'),
    r.mandatory = coalesce(r.mandatory, 'true');

MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = 'e2'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '高'),
    r.mandatory = coalesce(r.mandatory, 'true');

MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = '认知行为治疗'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.75),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '初始治疗');

MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = '健康教育'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.7),
    r.priority = coalesce(r.priority, '中'),
    r.stage = coalesce(r.stage, '常规治疗');

MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = '抑郁症状'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 0.5),
    r.timeframe = coalesce(r.timeframe, '长期');

MATCH (from) WHERE from.name = '特发性过度睡眠'
MATCH (to) WHERE to.name = '头痛'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 0.4),
    r.timeframe = coalesce(r.timeframe, '长期');

"""
