[metadata]
file_name = "睡眠相关的节律性运动障碍的临床特点.md"
processed_at = "2024-12-27 20:09:32"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-27 20:08:21"
message = """

[隶属文件名]
睡眠相关的节律性运动障碍的临床特点.md
[隶属文件分块名]
睡眠相关的节律性运动障碍的临床特点/001-完整文档.md
[文本块]
# 睡眠相关的节律性运动障碍的临床特点
白洁  马铁  张文娟 陈蓓蓓 袁娜  吴中亮 刘永红  

【摘要】目的探讨睡眠相关的节律性运动障碍(SRMD)的临床及电生理特点。方法对本院脑电监测中心收治的3例SRMD患者的临床和电生理特点进行研究。3例患者均符合第三版国际睡眠障碍分类中推荐的SRMD的诊断标准,并且随访时间均在1年以上。结果3例患者均为男性,年龄6~27岁。1例13岁起病,持续至今;另2例均1岁起病,1例7岁后自行缓解,另一例2岁好转,21岁复发。3例患者的视频脑电图发作期均未见痫样放电,发作时同步肌电变化曾被误认为是脑电的慢波活动。视频多导睡眠图显示:全夜觉醒次数和微觉醒指数较高。2例使用氯硝西泮治疗,1例效果显著,1例效果不佳,加用盐酸曲唑酮后疗效显著。结论SRMD不仅发生于婴幼儿时期,亦可见于青少年和成年。对于影响睡眠质量的患者有必要给予治疗,氯硝西泮可明显减轻症状及改善睡眠质量,对于服用氯硝西泮效果不佳者,可以尝试加用盐酸曲唑酮。正确地监测和解读视频脑电图对发作性疾病的诊断非常重要。  

【关键词】夜间性肌阵挛综合征;脑电描记术;多道睡眠描记术;肌电描记术;氯硝西泮;曲唑酮  

睡眠相关的节律性运动障碍(SRMD)是一种与睡眠相关的,以身体多部位反复的节律性刻板样动作为表现的综合征。这种现象临床上并不少见,尤其是随着长程视频脑电图(V-EEG)的开展,越来越多的夜间发作性疾病被发现。但是,由于国内相关研究与报道罕见,临床医师对该病认识不够,多数患者被误诊为癫痫甚至长期接受抗癫痫药物治疗,给患者在心理和经济上均造成了很大的负担。现报道3例睡眠相关的节律性运动障碍的临床和电生理特点,以提高医生对该病的认识。
# 临床资料
例1患者男性,27岁,因“人睡后不自主摇头(头部左右摆动)14年余”于2014年5月12日就诊于我院门诊。患者13岁时无明显诱因于睡眠时(入睡后 $2\\,\\mathrm{~h~}$ 内)出现不自主摇头,呼之不应,持续$0.\\,5\\sim2.\\,0\\mathrm{~h~}$ 后自行停止,每晚均有发作,次日醒后不能回忆,发作时偶伴喉咙发声。脑电图提示:大致正常。当时医生拟诊“癫痫”并先后使用苯巴比妥、丙戊酸、卡马西平等药物治疗2年,疗效不佳,自行停药。15岁时患者睡眠中出现双手紧握,头部前后撞击或左右摇摆,家人诉“发作时呼之不应”,持续约1h,上述症状频繁出现。再次就诊,拟诊“癫痫”,给予拉莫三嗪 $150\\,.175~\\mathrm{mg}$ ,左乙拉西坦 $500~\\mathrm{mg},2$ 次/d(均缓慢加量),上述症状仍有出现。起病以来(14年),患者在国内多家医院就诊,在4个癫痫中心共行5次长程脑电图监测,结果均提示:发作期及发作间期脑电图均未见癫痫样放电。头颅MRI检查未见异常。患者曾被诊断为难治性癫痫,建议癫痫外科治疗。遂再次来我院脑电监测中心就诊。患者智力发育稍迟滞并伴有抑郁状态,出生史、家族史无特殊。  

本次检查中监测到了多次患者的“发作”:均出现于刚入睡阶段,发作形式如前。发作时同步脑电图未见癫痫样放电。结合以上,考虑“非癫痫性发作,睡眠障碍性疾病”。为患者行视频多导睡眠图(V-PSG)监测,结果见表1。结合临床特点,确诊为SRMD。给予氯硝西泮 $0.\\,5~\\mathrm{mg}$ ,睡前口服,用药后发作减少 $50\\%$ 以上,药量加至 $1.\\:0\\:\\mathrm{\\mg}$ 后发作消失,随访1年,未见不良反应。  

例2患者男性,6岁,以“入睡后不自主摇头5年余”于2012年6月3日就诊于我院门诊。患者1岁时于刚入睡后出现不自主摇头,持续约数分钟,每天发作近10次,白天、晚上均有发作,均出现于睡眠初期。在外院共行4次动态脑电图监测,3次监测结果提示:发作期异常脑电图,全导慢波改变,外院诊断为“癫痫”,给予丙戊酸钠口服液(以每日2次、每次 $5.\\:0\\mathrm{~ml}$ 为起始,1周后增量为 $5.\\:5\\:\\mathrm{\\ml}$ ),治疗1年余,疗效不佳,自行停药,遂来我院就诊。本次监测到了多次患儿的“发作”:患儿头部左右剧烈摆动,均出现于浅睡眠中,阅图后发现所谓“发作期同步脑电图全导慢波”实为摇头动作所致的肌电伪差改变(图1),发作后继续睡眠。头颅CT检查未见异常,患儿智力发育正常,出生史,家族史均无特殊。  

结合以上,因考虑睡眠障碍性疾病,行V-PSG 监测,结果见表1。结合临床,最终考虑为SRMD。鉴于发作动作幅度较大,告知家属予以适当保护措施。7岁后患者的“摇头发作”自行消失。随访至今,患儿一切同健康同龄儿童。  

图1例2“发作期”脑电图,显示非快速动眼睡眠II期背景下摇头肌电活动(箭头所指为摇头肌电活动开始)  

表13例睡眠相关的节律性运动障碍患者的视频多导睡眠图结果  

注:REM:快速动眼睡眠;NREM:非快速动眼睡眠;RMD:节律性运动障碍  

例3患者男性,23岁,以“睡眠中头部不自主摇摆2年,再发2年”于2013年12月6日就诊于我院门诊。患者1岁时无明显诱因于平卧位刚入睡时出现头部不自主摆动,侧位即消失,每次持续约3min,后自行停止,每晚均有发作,家属未予重视,2岁后自行消失。21岁再次出现上述发作,,形式同前,持续约 $30\\,\\mathrm{\\min}$ ,唤醒后停止。之后每晚都有发作,多出现于凌晨5点左右,唤醒后不能回忆发作经过,未予重视。随后出现睡眠中将自己反复摇醒,导致白天困倦疲乏,遂来就诊。头颅 MRI未见异常。  

患者智力发育正常,其母亲分娩后患精神分裂症,余出生史、家族史无特殊。本次检查中监测到多次患者的“发作”,均出现于凌晨5点左右,形式同上。发作时同步脑电图仅见基线漂移,未见癫痫样放电。结合以上,考虑非癫痫性发作,睡眠障碍性疾病。结合临床及V-PSG监测结果(表1),确诊为SRMD。鉴于患者的“发作”严重影响其睡眠质量,给予氯硝西泮 $0.\\,5~\\mathrm{mg}$ ,睡前口服,发作程度减轻,但仍有摇头发作导致患者转醒,白天仍感疲乏,将氯硝西泮加量至 $1.\\:0\\:\\mathrm{\\,mg}$ 后,患者出现上午嗜睡,遂减为氯硝西泮$0.\\:5\\:\\mathrm{\\,\\,mg}$ ,尝试添加盐酸帕罗西汀 $20~\\mathrm{mg}$ (每日1次),无效后换为添加盐酸曲唑酮 $50~\\mathrm{{mg}}$ (每日1次),患者发作消失,夜间睡眠好,白天精神状态明显改善。现随访1年半,未见明显不良反应。
# 讨    论
SRMD由Webfer于1727年首先报道,1905年Zappert 和Cruchet对其做了进一步较为详细的阐述\"。2014 年最新发布的国际睡眠障碍分类(ICSD-3)中,SRMD被归类于睡眠运动障碍性疾病[2”。关于 SRMD 的发病率,不同年龄段差别较大。ICSD-3及其他研究显示, $59\\%$ 的婴幼儿在9个月时会出现一些节律性运动,18个月时降至 $33\\%$症状通常在2~3岁以后逐渐好转或消失;到5岁时患病率仅为 $5\\%$ [1-];也有青春期起病或者复发的,有学者称之为迟发型或晚发型 SRMD[6。我们报道的SRMD 的发病特点与上述研究大致相同,如例1于13岁起病,持续至今;例3于1岁起病,2岁自行缓解,21岁再次出现睡眠摇头症状,二者均属于迟发型 SRMD。关于发病率的性别优势,ICSD-3中提到儿童总体发病率无性别差异,在成年患者中存在男性优势。本组3例患者均为男性,与ICSD-3报道相一致。青春期和成年患者多合并精神异常和认知缺陷,本文中例1合并抑郁和智力低下,这与部分研究报道一致[23,]。关于 SRMD 持续至成年并伴有认知缺陷和精神异常的机制尚需进一步研究。  

SRMD的发作形式多样,主要有以下几个类型:$\\textcircled{\\scriptsize{1}}$ 撞头型; ${\\textcircled{2}}.$ 摇头型; $\\textcircled{3}$ 身体摇摆型; $\\circledast$ 其他类型:身体滚动型,腿摇摆型及腿撞击型; $\\circled{5}$ 混合型。其中最常见的症状为撞头,或用手和膝盖协同做翻滚动作,把头顶或额部撞向床头或墙壁。发作时患者可发出响亮的嗡嗡声或吟唱声。这些发作形式可单一重复出现,也可以多种形式转换或者同时出现[8-10]。本文中3例患者发作形式相似,均表现为仰卧位头部节律性的左右摇摆或前后撞击,虽然发作时间有所不同,但均出现在睡眠觉醒转换期。  

随着V-EEG的普及,对于发作性疾病患者,临床医师通常会为其首选该项检查,因此,结合视频仔细读图,对于诊断非常重要。有文献报道,SRMD患者的视频脑电图偶有非特异性改变或者棘、尖波出现3}。如本组中例1和例2,脑电图上出现类似阵发性慢波活动的改变,加之家属对患者发作形式描述不清,一度被误诊为癫痫。但是仔细观看视频脑电图,所谓的慢波改变其实是与患者摇头发作同步的肌电改变,“发作期”背景脑电图为非快速动眼睡眠(NREM)II期的脑电特征(图1)。因此,正确解读视频脑电图对于疾病的诊断至关重要。  

V-PSG对于确诊SRMD有重要意义,但是检查结果却不尽相同,目前没有统一的标准,绝大多数SRMD 发生在 NREM I、IIII期[2.11 ,本组3 例发作均在该期。从表1可以看出,3例患者睡眠效率降低:例2人睡潜伏期明显延长,例1于晚间23:16后未再人睡,分析其原因,可能与睡眠环境改变及个人心理因素相关;例2、例3快速动眼睡眠(REM)潜伏期延长;3例患者均NREMI、II期睡眠减少,慢波睡眠增加;例1、例3 REM 期缩短。Yeh 和 Schenck[ii]的报道中1例NREMII期增加、慢波睡眠减少,3例REM 潜伏期均延长,REM 期均缩短。宿长军等[5]的个案报道数据显示NREMI期睡眠增加,II期减少,未见慢波睡眠,REM期睡眠明显增加,REM潜伏期明显缩短。Su 等[的研究显示 NREMI、II期增加,慢波睡眠和REM期明显减少,REM潜伏期明显缩短。Dyken 等l12}报道的 7 例患者V-PSG 数据显示睡眠结构均正常,认为SRMD的发生与 NREMII期和K复合波有重要关系。多数报道可见睡眠效率降低、全夜觉醒次数增加及微觉醒指数增高。分析各报道结果不一致的原因如下:以往研究多是个案报道,且不同年龄组睡眠各期比例差异很大;其次,各种药物、种族差异等对睡眠结构也有一定的影响。因此,有关SRMD的睡眠特征尚需大样本的临床研究。  

以往认为SRMD属于年龄依赖性疾病,无需治疗[13]。但在 ICSD-3 中明确提到,没有造成任何临床后果的应称之节律性运动,并非节律性运动障碍,因此确诊为SRMD的患者或在剧烈运动时造成自身伤害,或影响睡眠导致白天效率降低。如本文报道的例2,患儿发病年龄小,并不能够清晰地表达自己的睡眠情况,家人也无法观察其睡眠质量,但PSG结果显示患儿睡眠效率较同龄健康儿童差;其次,其运动幅度过大,易造成身体创伤。因此,PSG监测对于鉴别节律性运动与 SRMD 至关重要。本组3例患者均符合SRMD 的诊断。目前关于 SRMD 的治疗主要有三环类抗抑郁药(TCASs)、催眠、睡眠限定等方法[1,2,14-5]。本文中3 例患者均影响到睡眠质量,例3尤为严重,每次摇头都会使自己觉醒,严重影响睡眠,白天感到困乏无力。多数报道认为小剂量氯硝西洋治疗效果颇佳11,10-1,1],但也有个别报道患者服用本药后疗效并不理想[17,对于效果不佳者,有研究报道TCASs有效,但该类药物不良反应较多,而5-羟色胺再摄取抑制剂既保留了TCASs相似的疗效,也克服了TCASs 的诸多不良反应。如例3,服用氯硝西泮疗效不佳,尝试添加盐酸帕罗西汀,无效后换为添加盐酸曲唑酮,疗效显著。根据笔者检索的资料,本文是第1例将盐酸曲唑酮用于治疗SRMD的报道,分析其机制,考虑可能与盐酸曲唑酮具有提高睡眠效率、减少觉醒次数和觉醒时间的作用相关[1\",另外,盐酸曲唑酮还具有中枢镇静作用以及轻微的肌松弛作用。当然,本文仅是有关盐酸曲唑酮用于治疗SRMD的个案报道,关于盐酸曲唑酮用于治疗 SRMD 的确切疗效及其机制尚需进一步研究。近年,有学者发现多巴胺拮抗剂对SRMD效果显著[13] MFnI  

尽管有关SRMD的研究有限,随着长程视频脑电图的普及,患有各种发作性疾病的患者都有可能接受V-EEG监测,增加临床医生对癫痫及其他非痫性发作性疾病的认识,对于防止误诊误治至关重要,同时有利于临床医生进一步认识SRMD等其他发作性疾病的临床特点。  

利益冲突无

"""
response = """
// 节点更新
MERGE (n:Disease {name: '睡眠相关的节律性运动障碍'})
SET 
    n.description = coalesce(n.description, '与睡眠相关的，以身体多部位反复的节律性刻板样动作为表现的综合征'),
    n.severity = coalesce(n.severity, '中等');

MERGE (n:Symptom {name: '不自主摇头'})
SET 
    n.description = coalesce(n.description, '在睡眠中出现的人头部左右摆动'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '频繁');

MERGE (n:Symptom {name: '发作性摇头'})
SET 
    n.description = coalesce(n.description, '睡眠中头部不自主摆动'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '白天嗜睡'})
SET 
    n.description = coalesce(n.description, '白天感到困乏无力'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '抑郁状态'})
SET 
    n.description = coalesce(n.description, '伴随入睡障碍的抑郁表现'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Examination {name: '视频多导睡眠图'})
SET 
    n.description = coalesce(n.description, '用于监测睡眠相关运动障碍'),
    n.method = coalesce(n.method, '视频脑电图监测'),
    n.requirement = coalesce(n.requirement, '在安静环境中进行');

MERGE (n:Examination {name: '脑电图'})
SET 
    n.description = coalesce(n.description, '监测发作期间的脑电活动'),
    n.method = coalesce(n.method, '脑电图监测'),
    n.requirement = coalesce(n.requirement, '静止状态下进行');

// 关系更新
MATCH (from) WHERE from.name = '睡眠相关的节律性运动障碍'
MATCH (to) WHERE to.name = '不自主摇头'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '频繁'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '睡眠相关的节律性运动障碍'
MATCH (to) WHERE to.name = '发作性摇头'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.85),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '睡眠相关的节律性运动障碍'
MATCH (to) WHERE to.name = '白天嗜睡'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '睡眠相关的节律性运动障碍'
MATCH (to) WHERE to.name = '抑郁状态'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.75),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '睡眠相关的节律性运动障碍'
MATCH (to) WHERE to.name = '视频多导睡眠图'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '高'),
    r.mandatory = coalesce(r.mandatory, 'true');

MATCH (from) WHERE from.name = '睡眠相关的节律性运动障碍'
MATCH (to) WHERE to.name = '脑电图'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '中'),
    r.mandatory = coalesce(r.mandatory, 'false');

"""
