[metadata]
file_name = "绝经相关失眠临床管理中国专家共识.md"
processed_at = "2024-12-18 16:48:29"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-18 09:55:50"
message = """

[隶属文件名]
绝经相关失眠临床管理中国专家共识.md
[隶属文件分块名]
绝经相关失眠临床管理中国专家共识/001-完整文档.md
[文本块]
【本期执行主编】 白白文文佩佩,首都医科大学附属北京世纪坛医院领军人才、妇产科主任、教授、博士研究生导师。主要研究方向:妇科内分泌基础与临床研究。  

国家更年期保健特色专科负责人,北京市“登峰”人才,北京市“扬帆计划”重点培育专业负责人,首都医科大学妇产科学系副主任,首都医科大学“宫腔粘连诊疗和研究”中心副主任,北京大学全科医学硕士研究生导师,中华医学会生殖医学分会委员,中华医学会科普分会委员,中华预防医学会妇女保健分会委员,北京中西医结合学会更年期专业委员会主任委员,国家健康科普专家库首批成员,国家卫生健康委员会专家组成员。  

承担多项国家自然科学基金项目、北京市自然科学基金项目、首都医学发展基金项目、首都特色临床与应用项目等。作为第一作者或通信作者在国内外学术期刊发表论文二百余篇,牵头制订多部中国专家共识。
# 绝经相关失眠临床管理中国专家共识
中华预防医学会更年期保健分会,中国人体健康科技促进会妇科内分泌和生育力促进专委会,北京中西医结合学会更年期专业委员会  

【摘要】 绝经相关失眠是(围)绝经期女性常见的症状,临床多见却易被忽视,绝经相关失眠会影响女性(围)绝经期甚至老年期的健康水平。国内尚缺乏关于绝经相关失眠临床管理的共识及指南。为规范绝经相关失眠的管理,提高(围)绝经期女性睡眠健康管理水平,组织专家制订本共识。绝经相关失眠管理内容主要包括成立多学科专家团队、药物管理和非药物管理等,希望能对临床实践起到一定的指导作用。  

【关键词】 围绝经期;绝经期;失眠;药物治疗;非药物治疗;共识 【中图分类号】 R 711.5 【文献标识码】 A DOI:10.12114/j.issn.1007-9572.2023.0192  

失眠是睡眠不佳的症状之一,当该症状持续不能缓解时,就发展成一种疾病——失眠症。失眠症是指尽管有足够的睡眠机会和环境,但仍有持续的睡眠障碍,并伴有可归因于睡眠障碍的日间功能受损,且上述症状出现频次 ${>}3$ 次/ 周,持续3 个月以上[1]。  

绝经相关失眠是指与绝经相关的、不能归因于其他原因的失眠[2]。绝经相关失眠是常见的(围)绝经期症状之一,如果不及时干预,会演变成慢性失眠,导致更多的健康问题和更严重的功能损害,给女性(围)绝经期甚至老年期生活造成重大困扰。因此,绝经相关失眠管理是 (围)绝经期健康管理的重要内容之一。特组织相关专家,参考美国睡眠医学会、美国精神医学学会、中华医学会神经病学分会、中国睡眠研究会、意大利睡眠医学协会发布的最新绝经相关失眠临床诊疗指南及专家共识,通过对PubMed、Web of Science、万方数据知识服务平台、中国知网等数据库中有关绝经相关失眠文献进行筛选,结合临床经验,经过反复讨论和修改,撰写《绝经相关失眠临床管理中国专家共识》,以期对绝经相关失眠的管理起到一定的指导作用。
# 1 绝经相关失眠的流行病学
失眠是最常见的睡眠障碍,成人失眠发生率为$10\\%{\\sim}15\\%$ [3]。40 岁以上女性睡眠障碍发生率是年轻女性的4 倍左右[4]。在(围)绝经期女性群体中,失眠的发生率显著增加,为 $13.2\\%{\\sim}65.1\\%^{[\\,5-7\\,]}$ ,多导睡眠监测(PSG)结果显示总睡眠时间减少、快速眼动睡眠异常、睡眠潜伏期延长、睡眠效率下降,表现为入睡时间延长、夜间频繁觉醒、醒来时间长、睡眠维持困难[8-9]。 C
# 2 绝经相关失眠的发生机制
睡眠是一个复杂的生理过程。失眠的发生涉及个体行为、社会环境以及器官、细胞、分子等多个层面,是多个因素共同作用的结果。绝经相关失眠是在易感因素作用的基础上,受到促发因素作用时发生,在维持因素作用下持续存在[10],见图1。常见的易感因素为既往存在失眠或抑郁、性格追求完美、焦虑倾向、激素水平改变、失眠家族史等,促发因素有年龄增长、工作生活压力增大、发生应激事件(如丧亲等)、健康状况差、疼痛、轮值夜班、血管舒缩症状等,维持因素有错误的睡眠认知和睡眠卫生习惯、负面情绪、血管舒缩症状。
# 3 绝经相关失眠对女性的影响
绝经相关失眠与女性内分泌系统密切相关,绝经和失眠存在独立的相关性[10-11]。雌激素和孕激素能够调节和稳定昼夜节律系统,在绝经前后雌激素水平下降,下丘脑对雌激素的敏感性降低,引起昼夜节律紊乱[12-13],诱发失眠。雌二醇(E2)水平下降与入睡困难、夜间频繁觉醒显著相关,卵泡刺激素(FSH)水平增加与夜间频繁觉醒显著相关[14]。此外,由于生殖激素水平改变导致的血管舒缩症状(潮热、出汗等)、神经精神症状(焦虑、抑郁等)也会诱发失眠,且上述症状越严重,女性越可能失眠[15]。绝经相关失眠使正常的睡眠节律发生改变,对女性的生理、心理均会造成严重影响。短期失眠会引起注意力下降、记忆力减退。长期失眠不仅会增加肥胖、高血压、2 型糖尿病、恶性肿瘤、冠心病、脑卒中和认知功能障碍的患病风险[16-17],还会使人体自主神经功能紊乱,内分泌失调,骨密度降低,骨质疏松、骨折风险增加[18];更会导致或加重原有抑郁症、焦虑症、精神分裂症等精神性疾病的发生、发展[13,19-21]。  

图 1 绝经相关失眠的发生机制Figure 1 Mechanisms of menopause-related insomnia
# 4 绝经相关失眠的临床筛查与诊断
绝经相关失眠的临床筛查包括病史采集、主观测评、客观检查,见图2。其中病史采集是关键环节,只有得到详实的病例资料,才能帮助医师准确诊断。4.1 病史采集 采集病史需要注意沟通的态度与技巧,充分考虑患者的受教育程度和理解能力,引导患者陈述事实,除常规病史询问外,还应着重了解(围)绝经期和睡眠相关症状。(围)绝经期病史采集:(1)近1 年的月经情况,是否存在其他(围)绝经期症状;(2)是否行性激素治疗;(3)是否有其他慢性病史。失眠病史采集:(1)患者近1 个月的作息时间、睡眠状况、失眠的表现形式、对日间功能的影响;(2)失眠开始的时间、与(围)绝经期症状及月经出血模式变化是否存在关系;(3)是否合并其他的睡眠障碍,如阻塞性睡眠呼吸暂停、不宁腿综合征等;(4)是否有焦虑症、抑郁症等共患疾病;(5)有无神经  

活性药物使用及物质依赖。  

4.2 主观测评 临床采用患者自评量表进行筛查,常用的(围)绝经期症状评估量表有改良Kupperman评分、Greene 量表;常用的睡眠评估量表有匹兹堡睡眠质量指数(Pittsburgh Sleep Quality Index,PSQI)、失眠严重程度指数(Insomnia SeverityIndex,ISI)、阿森斯失眠量表(Athens InsomniaScale,AIS)、Epworth 嗜睡量表(Epworth SleepinessScale,ESS)。临床根据实际情况,选择1+1〔1 个(围)绝经期症状量表 $+1$ 个睡眠量表〕或1+2〔1 个(围)绝经期症状量表 $^{+2}$ 个睡眠量表〕进行评估。  

4.3 客观检查 睡眠评估,包括(1)PSG:实时监测患者佩戴期间的心电图、脑电图、肌肉活动、眼球活动、通气功能等,可以准确描述睡眠结构,是评估睡眠障碍尤其是阻塞性睡眠呼吸暂停的“金标准”,不仅可以作为失眠的辅助诊断和鉴别诊断,也可以评估认知行为疗法治疗失眠的效果。(2)腕部体动仪:相比于PSG,腕部体动仪小巧便携,能在居家环境中评估睡眠状态及时间,是估计总睡眠时间和睡眠中觉醒的有效方法,但缺乏特异性,不推荐作为PSG的替代品,可在PSG 无法实施或者大规模人群研究时使用[22-23]。(围)绝经期全项评估:生殖激素六项、盆腔彩超、乳腺彩超、薄层液基细胞学检查(TCT) $^+$ 人乳头瘤病毒(HPV)检测、生化全项、甲状腺功能五项、骨密度、心电图等。  

4.4 绝经相关失眠的诊断 通过病史采集、量表评估和实验室检查得到的结果,结合美国睡眠医学会第三版国际睡眠障碍分类1可以进行绝经  

条目 具体内容A:患者报告,(1)入睡困难;(2)难以维持睡眠;(3)醒或患者的父母或得比预想的要早;(4)在适当的时间不肯上床照顾者观察到以睡觉;(5)没有父母或照顾者的干预很难入睡。下1 条或多条:B:患者报告,(1)疲劳或萎靡不振;(2)注意力、专注力或或者患者的父母记忆力下降;(3)社交、家庭、职业或学业功或照顾者观察到能受损;(4)情绪紊乱或易激惹;(5)日间瞌睡;以下1 种或多种(6)行为问题(如活动过度、冲动、攻击性);(7)与夜间睡眠困难动力/ 精力/ 工作主动性降低;(8)容易出错/有关: 事故;(9)对睡眠的质量非常关切或不满意。C:报告的睡眠/ 唤醒主诉不能仅以不合适的睡眠机会(如充足的睡眠时间)或睡眠环境(即环境安全、黑暗、安静和舒适)来解释。D:睡眠障碍和相关的日间症状每周至少出现3 次。E:睡眠障碍和相关的日间症状已经存在至少3 个月。F:睡眠/ 觉醒困难不能用另一种睡眠障碍来更好地解释。  

注:ICSD- $.3{=}$ 第三版国际睡眠障碍分类;ICSD-3 失眠诊断标准为A\\~F 条均需满足。  

相关失眠的诊断[24]。
# 5 绝经相关失眠管理
5.1 成立多学科专家团队 绝经相关失眠女性常没有意识到绝经与失眠的相关性,往返就诊于医院多个科室,增加了时间、人力、物力、财力的消耗。应当成立包括妇科、睡眠医学科、精神科、内分泌科、心内科医师及护士、药师、心理治疗师、运动康复师、营养师在内的多学科专家团队,对可疑绝经相关失眠的患者,首诊即进行绝经相关失眠的系统评估,排除心理、甲状腺功能障碍等问题引起的失眠后通过多学科团队内的转诊体系转至妇科内分泌门诊,由妇科医师行进一步的评估和诊疗,制定个体化的治疗方案,最大限度保证方案的可行性、治疗的有效性和患者的依从性。绝经相关失眠管理流程见图3。  

注: $\\mathrm{{PSQI}\\!=}$ 匹兹堡睡眠质量指数, $\\mathrm{ISI}{=}$ 失眠严重程度指数,AIS= 阿森斯失眠量表,ESS=Epworth 嗜睡量表, $\\mathrm{TCT}{=}$ 薄层液基细胞学检查,$\\mathrm{HPV}{=}$ 人乳头瘤病毒,ICSD- $\\cdot3\\mathrm{=}$ 第三版国际睡眠障碍分类。  

图3 绝经相关失眠管理流程图Figure 3 Flow chart for the management of menopause-related insomnia
# 5.2 综合管理
5.2.1 药物管理 药物治疗失眠的短期疗效佳,但纠正失眠的主要方法是行为调整和心理调节,不宜长期依赖药物治疗。药物管理的总目标为患者能够知晓其所使用药物的作用、使用方法和途径,遵医嘱按时按量用药,不错服、漏服,定期监测相关实验室指标;学会自行观察常见的药物不良反应,做自我健康的第一责任人;按时复诊,根据用药效果动态调整药物用量,以最低的有效剂量达到最大的治疗效果,减少药物相关的不良反应。  

绝经相关失眠女性的药物管理主要涉及围绝经期相关用药、失眠相关用药以及其他合并疾病的用药管理。建立个体化的用药清单,形成个人药物使用档案,记录药物开始使用及停药的时间、不良反应、剂量变化的时间及个体反应。使用激素补充或替代治疗的患者,在开始前评估有无适应证、禁忌证及慎用情况,告知患者使用激素治疗的利弊,告知其按时服药、定期复诊的必要性。经充分沟通和评估后,针对适宜用药的患者,应根据其年龄、绝经年限、是否切除子宫、对药物性出血的期待等选择单用雌激素、单用孕激素、雌孕激素序贯、雌孕激素联合或替勃龙等方案进行治疗,具体请参照《中国绝经管理与绝经激素治疗指南2023 版》[25]。各种类型的激素均能改善(围)绝经期女性的慢性失眠症[25],但不同类型的激素和用法可能影响疗效,例如:雌激素中 $17\\,\\upbeta-$ 雌二醇和共轭雌激素(CEE)能改善睡眠质量,而戊酸雌二醇效果不明显,使用经皮雌激素效果优于口服[26]。微粉化孕酮可改善绝经后女性自我报告的睡眠质量和睡眠周期的各个方面,因为孕酮代谢物是 $\\upgamma-$ 氨基丁酸A 型受体的正构调节剂,能产生与苯二氮卓艹类药物相似的睡眠结构变化[27]。使用经皮 $17\\,\\upbeta-$ 雌二醇联合微粉化孕酮6 个月能够改善绝经相关失眠患者睡眠质量。替勃龙是一种具有雌激素、孕激素和雄激素作用的合成类固醇,通过刺激 $\\upbeta-$ 内啡肽的产生和释放来改善睡眠质量,且由于具有孕激素作用,其改善睡眠的作用较雌激素强[28]。如果性激素治疗失眠改善仍不明显,可以短期内适当加用治疗失眠的药物。  

目前临床常用的治疗失眠的药物主要有苯二氮卓受体激动剂、褪黑素受体激动剂和具有催眠作用的抗抑郁药物。(1)苯二氮卓艹受体激动剂按结构分为苯二氮卓艹类药物和非苯二氮卓艹类药物。 $\\textcircled{\\scriptsize{1}}$ 苯二氮卓艹类药物按 $\\mathbf{\\Deltat}_{1/2}$ 可分为短效、中效和长效。短效通常不用于治疗失眠;中效苯二氮艹卓类药物主要用于睡眠浅、易醒和晨起需要保持头脑清醒者,常用药物有艾司唑仑( $1{\\sim}2~\\mathrm{mg}/$ 晚)、阿普唑仑( $0.4{\\sim}0.8~\\mathrm{mg}/$ 晚)和劳拉西泮( $0.5{\\sim}1.0\\ \\mathrm{mg}/$ 晚)等;长效苯二氮卓艹类药物具有起效慢和 $\\mathbf{\\Deltat}_{1/2}$ 长的特点,主要用于早醒,常用药物有地西泮( $5{\\sim}10~\\mathrm{mg/}$ 晚)。苯二氮艹卓类药物可以增加总睡眠时间,减少夜间觉醒,常见不良反应包括嗜睡、头晕、乏力、遗忘、跌倒等,长期连续用药可产生依赖性和成瘾性,如突然停药可能发生撤药症状,使用时需注意。 $\\textcircled{2}$ 非苯二氮艹卓类药物如佐匹克隆、唑吡坦等具有起效快、 $\\mathbf{\\Deltat}_{1/2}$ 短的特点,主要用于入睡困难或不能耐受次晨残余作用的失眠者。该类药物安全性较好,次晨残余效应降低,一般不产生日间困倦,药物依赖性较传统苯二氮艹卓类药物低,常见不良反应包括味觉异常、口干、眩晕等。常用的药物为佐匹克隆( $3.75{\\sim}7.50\\;\\mathrm{mg/}$ 晚)、右佐匹克隆(1\\~3$\\mathrm{mg/}$ 晚)、唑吡坦( $5{\\sim}10~\\mathrm{mg}/$ 晚)、扎来普隆(5\\~10mg/ 晚),该类药物应临睡前服用,服药后须保证一定的睡眠时间,服药期间避免驾车、操作机器及危险作业,禁止饮酒及含酒精饮料。(2)褪黑素和褪黑素受体激动剂如雷美替胺、阿戈美拉汀用于治疗失眠尚缺乏共识[29],其在绝经相关失眠治疗中应用较少,作用机制、疗效有待进一步验证。(3)曲唑酮、米氮平等抗抑郁药物也能在一定程度上改善绝经相关失眠症状。  

患者病情严重或反复时,可通过多学科团队转诊体系将患者转至精神心理科或睡眠医学科,并告知相关专科医师患者近期诊疗情况,以便专科医师尽快熟悉患者病情。对于合并其他慢性疾病的患者,继续原有的治疗,不可自行停药,定期到相关专科就诊。5.2.2 非药物管理  

5.2.2.1 睡眠卫生教育和健康教育 发挥多学科团队优势,全面综合评估绝经相关失眠患者的身心状况,给予疾病知识指导,使其全方面的了解(围)绝经期和失眠,消除担心和恐惧的思想,调整自身心理状态,减轻抑郁和焦虑情绪,放松身心。帮助患者营造良好的睡眠氛围,保持室内温度在 $22{\\sim}26\\,^{\\circ}\\mathrm{C}$ ,湿度在 $40\\%$ 左右,睡前关灯,不看手机,选择合适的床具;戒烟限酒,睡前 $1{\\sim}2~\\mathrm{h}$ 避免情绪过度波动,不饮用咖啡、浓茶等,不过饱或饥饿入睡。睡眠卫生教育是非药物管理的基础,应当贯穿治疗全过程。  

5.2.2.2 心理疗法 心理疗法由受过专门训练的医护或心理治疗师开展。常用的心理疗法包括失眠的认知行为治疗(CBT-I)、正念疗法、催眠、中医心理疗法等,其中CBT-I 被多个指南推荐为绝经相关失眠的一线疗法[30-32]。CBT-I是一种多模式联合的疗法,包括睡眠卫生教育、行为疗法(睡眠限制和刺激控制)、放松训练(渐进式肌肉放松)以及认知疗法(认知重建和矛盾意向法),具体实施方式可参见《中国成人失眠诊断与治疗指南(2017 版)》。CBT-I 通常实施6\\~8 次, $30{\\sim}50\\mathrm{\\min/}$ 次,形式为一对一咨询、小组咨询、网络自助式,其效果在短期内是可见的,在长期内是持久的[33-34]。  

正念疗法是一种身心干预措施,简便易行,旨在通过训练让注意力重回当下,放下对不愉快体验的抗拒,不评判地与感受共处,有意识的行动,让患者接纳现在的自己及所处的环境,从而增加其对应激事件的应对方式。主要的正念疗法有正念呼吸、正念行走、正念观想法、正念观情绪、躯体扫描、正念瑜伽、葡萄干练习等,治疗周期一般为8\\~10 周,1 次/ 周, $120\\;\\mathrm{min}/$ 次。  

催眠是一种集中注意力和减少外围意识的特殊意识状态,其特点是对建议的反应能力增强。催眠主要针对绝经相关失眠和潮热,目标是教育和训练受试者进行自我催眠以减轻潜在症状。一个完整的催眠程序包括解释并建立治疗关系、催眠感受性测试、催眠诱导、实施催眠疗法和催眠唤醒5 个部分。催眠疗法有治疗师催眠和自我催眠2 种形式。自我催眠能够改变患者错误的睡眠认知,缓解潮热、盗汗症状,提高睡眠质量,延长睡眠时间,并且患者治疗满意度高、接受度较好,是一种有前景的失眠治疗方式[35]。  

中医心理疗法中的低阻抗意念导入疗法(TIP 技术)系现代催眠疗法、精神分析疗法、认知行为疗法与中医传统心理治疗融合而成[36],TIP 技术治疗慢性失眠具有疗效持久,不易复发的优势[37]。  

5.2.2.3 适当运动 运动在改善失眠的同时也能缓解其他(围)绝经期症状,降低骨质疏松、肥胖等的发生率,增加生活幸福感。(围)绝经期女性由于年龄增加、体力下降,对运动的耐受性可能有所降低,应鼓励女性根据自身兴趣爱好、能力、体力等选择合适的运动方式,推荐以有氧运动、抗阻运动为主,从低强度开始,循序渐进,每次进行热身- 运动- 放松的运动循环,运动以身体感到发热、微微出汗为度,但应注意睡前 $2~\\mathrm{{h}}$ 内避免剧烈运动。有条件者也可以根据运动康复师开具的运动处方进行运动。  

5.2.2.4 饮食与营养管理 给予患者饮食指导,保证营养均衡不过剩,BMI 保持在 $18.5{\\sim}23.9~\\mathrm{kg/m}^{2}$ ,腰围${<}80\\;\\mathrm{cm}$ 。增加蛋白质、含钙物质如肉类、蛋类、奶类的摄入,同时增加含益生菌酸奶的摄入[38];增加富含维生素的水果蔬菜类摄入,每日可适当增加西红柿的摄入,以促进褪黑素循环,改善睡眠质量[39];减少含咖啡因的物质如茶、咖啡、巧克力、冰激淋等摄入;减少煎炸、含糖类食物;每日少量多次饮水,总量达 $1\\ 500\\;\\mathrm{mL/d}$ 。  

5.2.2.5 中医管理 中医无失眠这一病名,认为本病属于“不寐”。不寐在《内经》称为“不得卧”“目不瞑”,认为是邪气客于脏腑,卫气行于阳,不能入阴所得。中医认为绝经相关失眠多由于肝郁、脾虚、肾精亏虚导致脏腑、气血、阴阳失衡而引起。女性绝经前后,肾气渐衰,天癸渐绝,冲任亏虚,致使阴阳失衡,脏腑功能失调,心肾不交、心神失养而夜不能寐。中医治疗可以分为辨证论治、中医外治法和其他疗法等。辨证论治根据患者的证型给予针对性的治疗用药,以补虚泻实、调整脏腑阴阳为原则。实证则泻其有余,如疏肝泻火、清热化痰等;虚证则补其不足,如健脾益气、补益肝肾等。目前外治法主要有针灸、艾灸、耳穴压豆等。针灸由临床医师进行评估后取穴,常用的穴位为三阴交、神门、百会、肾俞、太冲、心俞等;灸法包括艾灸、姜灸、雷火灸等,针刺也可以配合灸法进行治疗,对于虚寒证患者两者配合效果更佳;耳穴压豆指选用规格大致均一、质量优选的王不留行籽或磁珠等贴压于相应耳穴,并稍加压力使患者耳朵感到酸麻胀或发热,每耳保留 $72\\,\\mathrm{h}$ ,双耳交替贴压进行治疗。可通过按压、推拿和治疗性按摩的方式不断刺激耳位,疏通经络气血,调和阴阳,与全身脏腑产生联系,达到安神安眠的效果[40-41]。其他疗法有中药足浴、五行音乐疗法、芳香疗法、精油吸入、刮痧、药膳、药枕等,对绝经相关失眠也有一定的效果,应根据患者的实际情况和接受度,选择合适的方式。  

5.2.2.6 物理疗法 物理疗法是指使用物理因子(包括但不局限于磁、光、电、热)等对患者进行治疗,主要有经颅磁刺激疗法、光照疗法、脑电生物反馈疗法、小脑顶核电刺激、高压氧疗法等。目前,国内外关于失眠物理治疗的研究均较少,绝经相关失眠的物理疗法研究更少,其作用机制、效果等还需要进一步的发现与研究。  

5.3 定期随访 根据个人就诊和用药记录档案,制订随访计划,由专人进行随访登记。使用性激素治疗的患者应在初始用药的1、3、6 个月进行随访,重点观察患者用药后睡眠有无改善、有无不良反应。未使用激素类药物的患者,询问患者睡眠是否改善,如无变化,进一步评估是否更改治疗方案。
# 6 小结
绝经相关失眠发生率高,影响因素众多,在诊疗中需详细询问病史,全面评估患者的身心状况,建立多学科团队,充分发挥多学科诊疗模式的优势,早期识别绝经相关失眠。应根据患者的治疗意愿,制订个体化的药物治疗方案和非药物管理策略,提高(围)绝经期睡眠健康管理水平。

"""
response = """
// 节点更新
MERGE (n:Disease {name: '绝经相关失眠'});

MERGE (n:Symptom {name: '失眠'})
SET 
    n.description = coalesce(n.description, '睡眠不佳的症状'),
    n.severity = coalesce(n.severity, '中');

MERGE (n:NonDrugTreatment {name: '睡眠卫生教育'})
SET 
    n.description = coalesce(n.description, '帮助患者营造良好的睡眠氛围'),
    n.duration = coalesce(n.duration, '持续'),
    n.frequency = coalesce(n.frequency, '出院后持续关注');

MERGE (n:DrugTreatment {name: '激素治疗'})
SET 
    n.description = coalesce(n.description, '使用雌激素或孕激素改善睡眠质量'),
    n.dosage = coalesce(n.dosage, '依据患者情况'),
    n.frequency = coalesce(n.frequency, '按需'),
    n.duration = coalesce(n.duration, '根据疗效调整');

MERGE (n:Complication {name: '慢性失眠'})
SET 
    n.description = coalesce(n.description, '长期失眠可导致健康问题'),
    n.severity = coalesce(n.severity, '高');

// 关系更新
MATCH (from) WHERE from.name = '失眠'
MATCH (to) WHERE to.name = '绝经相关失眠'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中');

MATCH (from) WHERE from.name = '睡眠卫生教育'
MATCH (to) WHERE to.name = '绝经相关失眠'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.8),
    r.priority = coalesce(r.priority, '高'),
    r.stage = coalesce(r.stage, '全程管理');

MATCH (from) WHERE from.name = '激素治疗'
MATCH (to) WHERE to.name = '绝经相关失眠'
MERGE (from)-[r:TREATED_BY]->(to)
SET 
    r.effectiveness = coalesce(r.effectiveness, 0.85),
    r.priority = coalesce(r.priority, '中'),
    r.stage = coalesce(r.stage, '根据病情调整');

MATCH (from) WHERE from.name = '绝经相关失眠'
MATCH (to) WHERE to.name = '慢性失眠'
MERGE (from)-[r:MAY_CAUSE]->(to)
SET 
    r.probability = coalesce(r.probability, 0.7),
    r.timeframe = coalesce(r.timeframe, '长期');

MATCH (from) WHERE from.name = '绝经相关失眠'
MATCH (to) WHERE to.name = '激素治疗'
MERGE (from)-[r:INFLUENCED_BY]->(to)
SET 
    r.impact_level = coalesce(r.impact_level, '高'),
    r.evidence_level = coalesce(r.evidence_level, '强');

"""
