[metadata]
file_name = "脑卒中伴睡眠期周期性肢体运动患者的睡眠结构研究.md"
processed_at = "2024-12-27 20:09:32"
total_pairs = 1

[[message_pairs]]
timestamp = "2024-12-27 20:08:32"
message = """

[隶属文件名]
脑卒中伴睡眠期周期性肢体运动患者的睡眠结构研究.md
[隶属文件分块名]
脑卒中伴睡眠期周期性肢体运动患者的睡眠结构研究/001-完整文档.md
[文本块]
# 脑卒中伴睡眠期周期性肢体运动患者的睡眠结构研究
胡娅娅,朱宁\\*,薛孟周  

【摘要】 背景 睡眠障碍为脑卒中常见的并发症,临床表现多种多样,其中,以睡眠期间反复刻板的肢体运动为表现的称之为睡眠期周期性肢体运动(PLMS)。PLMS 发病机制及对脑卒中预后的影响仍处在探索阶段,临床资料较少,国内外鲜有PLMS 对脑卒中患者睡眠影响的研究。目的 探究脑卒中伴PLMS 患者的睡眠结构。方法 选取2020 年12 月至2022 年2 月于郑州大学第二附属医院就诊的伴睡眠障碍且行多导睡眠监测(PSG)的脑卒中患者81例。收集患者基本信息及PSG 监测数据后,依据周期性肢体运动指数(PLMI)将患者分为非PLMS 患者(对照组,PLMI<15 次/h)和PLMS 患者(试验组, $\\mathrm{PLMI}\\geqslant15$ 次/h)。比较两组清醒期PLMI、睡眠效率、N1 期睡眠占总睡眠时间比例、N2 期睡眠占总睡眠时间比例、N3 期睡眠占总睡眠时间比例、REM 期睡眠占总睡眠时间比例、睡眠呼吸暂停低通气指数(AHI)、睡眠潜伏期、觉醒指数、周期性肢体运动觉醒指数情况,分析PLMS 与睡眠结构及相关参数的相关性。结果 对照组42 例,试验组39 例。试验组清醒期PLMI、N1 期睡眠占总睡眠时间比例、N2 期睡眠占总睡眠时间比例、觉醒指数、周期性肢体运动觉醒指数高于对照组,睡眠效率、N3 期睡眠占总睡眠时间比例低于对照组( $P{<}0.05$ );两组患者睡眠潜伏期、AHI、REM 期睡眠占总睡眠时间比例比较,差异无统计学意义( $P{>}0.05$ )。Spearman 秩相关分析结果显示,PLMS 与清醒期PLMI、N2 期睡眠占总睡眠时间比例、睡眠潜伏期、觉醒指数、周期性肢体运动觉醒指数呈正相关( $r_{s}$ 值分别为0.619、0.250、0.271、0.312、0.828, $P$ 值分别为 $-0.001$ 、0.024、0.014、0.005、$<\\!0.001$ ),与睡眠效率( $r_{\\mathrm{s}}{=}{-0.345}$ , $P{=}0.002$ )呈负相关。结论 伴PLMS 的脑卒中患者客观存在睡眠紊乱,睡眠效率降低,其可能是脑卒中预后不良的标志之一。  

【关键词】  夜间性肌阵挛综合征;睡眠期周期性肢体运动;周期性肢体运动障碍;卒中;睡眠结构【中图分类号】 R 749.79 R 743 【文献标识码】 A DOI:10.12114/j.issn.1007-9572.2022.0468  

睡眠期周期性肢体运动(periodic limb movementsdisorder in sleep,PLMS)是指主要发生于非快速动眼睡眠期重复性肢体运动,其特点为睡眠期间短暂、刻板、重复性的踇趾伸直、足踝部背屈,有时累及膝部、髋部及上肢。周期性肢体运动指数(periodic limb movementof sleep index,PLMI)是在睡眠监测中发现规律性肢体运动的次数, $\\mathrm{PLMI}\\geqslant15$ 次 $/\\mathrm{h}$ 且排除其他疾病引起的睡眠症状则为周期性肢体运动障碍(periodic limbmovements disorder,PLMD)[1]。成年人PLMD 患病率为 $4\\%{\\sim}11\\%$ ,且随着年龄增加发病率增加[2-3]。有研究表明,PLMS 可能是脑卒中的危险因素,可加重脑卒中患者功能障碍〔美国国立卫生研究院卒中量表(NIHSS)评分升高〕[4]。LIN 等[5]研究支持并验证了上述结果。尽管PLMS 与脑卒中严重程度和复发率明显相关,但目前的横断面研究仍无法回答二者的时间顺序和因果关系[6]。因研究PLMS 对脑卒中患者睡眠影响的相关资料较少,本研究拟通过多导睡眠监测(polysomnography,PSG)观察脑卒中患者的睡眠结构,并对伴PLMS 的脑卒中患者进行睡眠结构分析。
# 1 资料与方法
1.1 一般资料 选取2020 年12 月至2022 年2 月于郑州大学第二附属医院就诊的伴睡眠障碍且行PSG 的脑卒中患者81 例。脑卒中诊断参考《中国急性缺血性脑卒中诊治指南2018》[7]中诊断标准。PLMS 诊断参考《国际睡眠疾病分类第三版》中睡眠相关运动障碍相关标准:至少连续4 次出现腿动事件;腿动事件最短周期(包括腿动事件)为 $5\\ \\mathrm{s}$ 、最大间隔(包括腿动事件)为 $90\\;\\mathrm{s}$ (若双腿腿动事件起始点间隔<5 s,计为单次腿动)[1]。符合上述诊断标准且伴有不同程度睡眠障碍的患者纳入此次试验。排除不宁腿综合征、快速动眼期睡眠行为障碍(rapid eye movement sleep behavior disorder,RBD)、发作性睡病、充血性心力衰竭、原发性高血压、终末期肾病、脊髓损伤、酒精依赖、帕金森病和Tourette 综合  

征者。  

本研究已获得郑州大学第二附属医院医学伦理委员会批准(批件号:2022174),患者本人或其法定代表人签署知情同意书。  

1.2 方法  

1.2.1 资料采集 由从事睡眠医学的医师收集患者基本信息(年龄、性别、身高、体质量、脑卒中类型)及PSG 监测数据,计算BMI。信息采集过程中严格保守患者隐私。  

1.2.2 PSG 方法 行PSG 前,告知患者监测当日禁服调节睡眠药物及饮用酒、咖啡、可乐、茶等;日间少睡,避免情绪波动等,保证夜间睡眠质量。在符合以上条件下,于19:00 前进入睡眠监测室,待患者适应环境后进行PSG,直至次日7:00 离开,记录时间 $\\geqslant7\\,\\mathrm{h}$ 。睡眠检测分析系统自动记录并分析脑电图、眼电图、下肢肌电图和口鼻气流等指标,再由经PSG 技术培训的医师根据美国睡眠医学会睡眠及其相关事件判读手册2.6 版进行修正[8],记录相关监测数据,包括清醒期PLMI、睡眠效率、N1 期睡眠占总睡眠时间比例、N2 期睡眠占总睡眠时间比例、N3 期睡眠占总睡眠时间比例、REM 期睡眠占总睡眠时间比例、睡眠呼吸暂停低通气指数(AHI)、睡眠潜伏期、觉醒指数、周期性肢体运动觉醒指数情况。  

依据PLMI 将患者分为非PLMS 患者(对照组,PLMI<15 次/h)和PLMS 患者(试验组, $\\mathrm{PLMI}\\geqslant15$ 次 $/\\mathrm{h}$ )。1.3 观察指标 比较两组患者睡眠结构及相关参数,分析PLMS 与睡眠结构及相关参数的相关性。  

1.4 统计学方法 应用SPSS 26.0 统计学软件进行数据分析。计量资料进行正态性检验,符合正态分布以( $\\overline{{x}}$$\\pm\\textbf{s}$ )表示,方差齐两组间比较采用成组 $t$ 检验,否则以$M$ ( $P_{25}$ , $P_{75}$ )表示,两组比较采用秩和检验;计数资料以相对数表示,两组间比较采用 $\\chi^{\\,2}$ 检验。相关性分析采用Spearman 秩相关分析。以 $P{<}0.05$ 为差异有统计  

学意义。
# 2 结果
2.1 两组患者一般资料比较 对照组42 例,试验组39例。两组患者年龄、性别、BMI、脑卒中类型比较,差异无统计学意义( $P{>}0.05$ ),见表1。  

2.2 试验组与对照组患者睡眠结构及相关参数比较试验组清醒期PLMI、N1 期睡眠占总睡眠时间比例、N2期睡眠占总睡眠时间比例、觉醒指数、周期性肢体运动觉醒指数高于对照组,睡眠效率、N3 期睡眠占总睡眠时间比例低于对照组,差异有统计学意义( $P{<}0.05$ );两组患者REM 期睡眠占总睡眠时间比例、AHI、睡眠潜伏期比较,差异无统计学意义( $P{>}0.05$ ),见表2。2.3 PLMS 与睡眠结构及相关参数的相关性分析PLMS 与清醒期PLMI、N2 期睡眠占总睡眠时间比例、睡眠潜伏期、觉醒指数、周期性肢体运动觉醒指数呈正相关,与睡眠效率呈负相关( $P{<}0.05$ ),见表3。
# 3 讨论
睡眠障碍为脑卒中常见的并发症,临床表现多样,是神经内科等诸多学科关注重点。PLMS 因其反复刻板性动作而进入大众视野,但病因尚不明确,有文献称其可能与多巴胺能系统受损相关,还可增加心脑血管疾病发病风险[9-10]。目前对于脑血管引发肢体运动的防治并未得到重视,相关报道较少,临床经验缺乏。当床伴发现患者睡眠期间肢体异常运动时,临床上常以脑血管并发症处理,未进一步探查病因,常因药物选择不佳而诱发或加重部分患者症状,延误病情。为此,本研究纳入了81 例患者,观察其睡眠结构,为临床提供理论支持及数据支撑,促进睡眠医学发展,科学指导用药,降低患者负担。  

研究发现,伴有PLMS 的患者睡眠效率降低、清醒次数增多、睡眠结构失调,PLMS 与周期性肢体运动觉醒指数有较强的相关性( $r_{s}{=}0.828$ )。BENBIR 等[4]调查评估了年龄为50\\~80 岁缺血性脑卒中患者,发现$54.3\\%$ 的患者在睡眠中会出现周期性的腿部运动,平均PLMI 较高。证实脑破坏性损伤会导致运动通路受损,造成大脑皮质下去抑制,引起A11 多巴胺能在脑干脊髓通路中功能减退,促进PLMS 进展[9]。这些通路还支配节前交感神经元,其功能减退可导致交感神经兴奋,造成心脏病和脑卒中发生风险增加[10]。在最新的一项前瞻性研究中,通过分析PLMS 与脑小血管病变的影像学关系,发现PLMS 升高与脑小血管疾病相关[11]。再次证实,对于脑卒中患者,脑的器质性病变会加重PLMS 发展,是心脑血管疾病一项重要的危险因素。  

表1 两组患者一般资料比较Table 1 Comparison of general information between two groups  

注:a 表示 $\\chi^{\\,2}$ 值;BMI= 体质指数  

表2 试验组与对照组患者睡眠结构及相关参数比较  

注:a 表示 $t$ 值;PLMI= 周期性肢体运动指数, $\\mathrm{AHI}=$ 睡眠呼吸暂停低通气指数  

表3 PLMS 与睡眠结构及相关参数的Spearman 秩相关分析Table 3 Spearman rank correlation analysis of PLMS with sleep structure and related parameters  

关于PLMS 患者脑神经功能方面,KIM 等[12]通过分析脑电图源定位的增量波段,根据delta 带的脑电图地形数据进行分析,发现在PLMS 发作之前,个体大脑中央周围区域首先发生变化,然后是额叶和顶叶区域。一项采用正电子发射断层扫描技术的研究表明,PLMS发生之前,个体双侧大脑中央周围和右后扣带回区域与运动相关运动想象激活相对应[13]。越来越多神经影像学和神经解剖学研究证据支持,PLMS 的启动与中央周围、前额叶背外侧和扣带回区域脑电活动有关,其中,前额叶背外侧皮质负责运动控制,后扣带皮质作为中心节点,在与额顶控制网络相关的执行运动控制中发挥作用[14-15]。监测睡眠时,笔者也观察到在发生PLMS 前,个体的脑电图会显示相应的波幅变化,支持PLMS 与皮质额叶、扣带回的相关性。  

在睡眠结构方面,普遍认为PLMS 是一种唤醒反应,是造成睡眠碎片化的原因[16-17]。然而,PLMS 睡眠结构紊乱的影响程度是有争议的[18]。PLMS 大致可分为两类,一类仅为PSG 观察的结果,与觉醒无关,无实际意义;一类与觉醒相关[19]。其中,伴有脑电图唤醒的PLMS 已被证明与交感神经介导的脉搏率和血压增加有关,影响缺血性脑卒中患者的预后[4,10,20]。总结本研究结果,可以看出PLMS 与PLMS 引起的觉醒存在较强的相关,与整体的觉醒呈弱相关;表明伴PLMS 的脑卒中患者虽有引起觉醒的肢体运动,又有无临床意义的肢体运动。本研究虽未统计预后相关的临床资料,但在PSG 结果报告中可以看出,试验组较对照组患者睡眠结构更加紊乱,与黄隽英等[21]研究结果一致。因此,本研究认为伴有觉醒的肢体运动会导致脑卒中患者睡眠结构紊乱程度加重,是脑卒中患者预后不良的标志。  

然而,PLMS 的发生原因是复杂的。一项药理学研究表明,普拉克索可明显减少PLMS 而不影响觉醒频率,而氯硝西泮可减少睡眠觉醒但对PLMS 无影响[22]。这一证据表明选择性药理学方法可以将PLMS 与唤醒事件分离。越来越多的研究指出PLMS 与觉醒可能没有直接因果关系,二者之间不是简单的相互关系,可能受到更复杂的调节机制,包括可能存在的其他睡眠阶段事件,是各种影响因素的综合表现[23-24]。分析本试验结果,发现患者睡眠结构紊乱可能是由阻塞性睡眠呼吸暂停、伴有觉醒的肢体运动、脑卒中及潜在的危险因素等综合原因引起的,而通过PLMI 显现。有研究显示,PLMI $\\geqslant15$ 次 $/\\mathrm{h}$ 是脑卒中复发的强预测因子,可使脑卒中患者BMI 和NIHSS 评分增加[4,25]。清醒次数增多,睡眠效率降低,二者叠加,则进一步加重患者的临床症状。  

本研究中PSG 结果显示,试验组患者较对照组患者N1、N2 期睡眠占总睡眠时间比例增多,N3 期睡眠占总睡眠时间比例减少。排除肢体运动引起的睡眠障碍,可能是脑卒中后患者脑血流减少和重新分布、中枢神经递质失调和细胞因子失衡、神经功能缺损等因素引起的睡眠结构紊乱[26-27]。同时,本研究还发现PLMS 与清醒期PLMI 和周期性肢体运动觉醒指数存在相关性,不排除病理性改变引起相应的肢体运动,但由于清醒时肢体运动受各种因素影响,未降低日常生活能力,因而受到临床的忽视,临床资料较少,要进一步完善相关临床资料的收集。需指出的是,本研究由于资料为刻板的监测数据,不能动态观察PLMS 与清醒之间因果关系。同时,参与本研究的患者仅来自一个睡眠障碍中心,这可能导致潜在的样本偏倚和抽样偏差。在今后的研究中需要更大规模、多中心的研究来探讨PLMS 对脑卒中患者的影响,为更好地识别、干预和治疗PLMS 提供新的理论支持。  

综上所述,PLMS 的发病机制尚未明确,PLMS 与各种条件的关联很难用单一的机制解释。但对于脑卒中患者来说,伴有PLMS 会增加脑卒中患者睡眠结构紊乱,增加脑卒中复发风险,是脑卒中预后不良的标志。因此,在治疗原发病的同时,应结合患者睡眠监测报告,分析睡眠障碍的类型,观察PLMI 及是否伴有觉醒的肢体运动,结合患者的临床需求选择合适的药物,并随访服药后是否出现其他不良反应等,改善睡眠状况的同时,降低脑卒中复发及加重的因素,从而提高生活质量。

"""
response = """
// 节点更新
MERGE (n:Disease {name: '脑卒中'})
SET 
    n.description = coalesce(n.description, '一种影响脑部的疾病，可以导致各种并发症'),
    n.severity = coalesce(n.severity, '严重');

MERGE (n:Symptom {name: '睡眠期周期性肢体运动'})
SET 
    n.description = coalesce(n.description, '在睡眠期间反复出现的刻板肢体运动'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '频繁');

MERGE (n:Symptom {name: '睡眠障碍'})
SET 
    n.description = coalesce(n.description, '影响睡眠质量的各种症状'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '清醒期PLMI'})
SET 
    n.description = coalesce(n.description, '清醒状态下的周期性肢体运动指数'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Symptom {name: '睡眠效率降低'})
SET 
    n.description = coalesce(n.description, '睡眠期间效率低下的表现'),
    n.severity = coalesce(n.severity, '严重'),
    n.frequency = coalesce(n.frequency, '普遍');

MERGE (n:Symptom {name: '觉醒指数增加'})
SET 
    n.description = coalesce(n.description, '夜间觉醒次数增多的现象'),
    n.severity = coalesce(n.severity, '中等'),
    n.frequency = coalesce(n.frequency, '常见');

MERGE (n:Examination {name: '多导睡眠监测'})
SET 
    n.description = coalesce(n.description, '用于评估睡眠质量的检测方法'),
    n.method = coalesce(n.method, '多导睡眠监测'),
    n.requirement = coalesce(n.requirement, '在安静环境中进行');

// 关系更新
MATCH (from) WHERE from.name = '脑卒中'
MATCH (to) WHERE to.name = '睡眠期周期性肢体运动'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.95),
    r.frequency = coalesce(r.frequency, '频繁'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '脑卒中'
MATCH (to) WHERE to.name = '睡眠障碍'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '脑卒中'
MATCH (to) WHERE to.name = '清醒期PLMI'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.85),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '脑卒中'
MATCH (to) WHERE to.name = '睡眠效率降低'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.9),
    r.frequency = coalesce(r.frequency, '普遍'),
    r.severity = coalesce(r.severity, '严重');

MATCH (from) WHERE from.name = '脑卒中'
MATCH (to) WHERE to.name = '觉醒指数增加'
MERGE (from)-[r:INDICATES]->(to)
SET 
    r.confidence = coalesce(r.confidence, 0.8),
    r.frequency = coalesce(r.frequency, '常见'),
    r.severity = coalesce(r.severity, '中等');

MATCH (from) WHERE from.name = '脑卒中'
MATCH (to) WHERE to.name = '多导睡眠监测'
MERGE (from)-[r:REQUIRES_EXAM]->(to)
SET 
    r.priority = coalesce(r.priority, '高'),
    r.mandatory = coalesce(r.mandatory, 'true');

"""
